export const OFFLINE_ITEM_VERSION=1 as const;
export const OFFLINE_ITEM_TTL_MS=48*60*60*1000;
const CONFLICT_REVIEW_TTL_MS=7*24*60*60*1000;
const DB_NAME="supported-accommodation-secure-drafts";
const DB_VERSION=1;
const ITEM_STORE="key-worker-items";
const KEY_STORE="device-keys";

export type OfflineOperation="key_worker_report"|"incident";
export type OfflineItemStatus="device_draft"|"queued"|"syncing"|"conflict"|"rejected";
export type OfflineEnvelope={idempotencyKey:string;clientVersion:1;clientCreatedAt:number;expiresAt:number;basePlacementUpdatedAt:number;operation:OfflineOperation;payload:Record<string,unknown>};
export type OfflineItem={id:string;operation:OfflineOperation;status:OfflineItemStatus;updatedAt:number;expiresAt:number;code?:string;message?:string;envelope:OfflineEnvelope};
type StoredItem={id:string;ownerKey:string;entityId:number;deviceId:string;operation:OfflineOperation;status:OfflineItemStatus;updatedAt:number;expiresAt:number;code?:string;message?:string;iv:string;ciphertext:string};
type StoredKey={id:string;key:CryptoKey;createdAt:number};

function openDb(){return new Promise<IDBDatabase>((resolve,reject)=>{const request=indexedDB.open(DB_NAME,DB_VERSION);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains(ITEM_STORE))db.createObjectStore(ITEM_STORE,{keyPath:"id"});if(!db.objectStoreNames.contains(KEY_STORE))db.createObjectStore(KEY_STORE,{keyPath:"id"});};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
function requestResult<T>(request:IDBRequest<T>){return new Promise<T>((resolve,reject)=>{request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
function transactionDone(tx:IDBTransaction){return new Promise<void>((resolve,reject)=>{tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error??new Error("Secure draft transaction was cancelled"));});}
function bytesToBase64(bytes:Uint8Array){let binary="";for(let index=0;index<bytes.length;index++)binary+=String.fromCharCode(bytes[index]);return btoa(binary);}
function base64ToBytes(value:string){const binary=atob(value);return Uint8Array.from(binary,character=>character.charCodeAt(0));}
function deviceId(){const key="supported-accommodation-device-id";let value=localStorage.getItem(key);if(!value){value=crypto.randomUUID();localStorage.setItem(key,value);}return value;}
function additionalData(item:{ownerKey:string;entityId:number;deviceId:string;id:string}){return new TextEncoder().encode(`${item.ownerKey}:${item.entityId}:${item.deviceId}:${item.id}:${OFFLINE_ITEM_VERSION}`);}
async function deviceKey(db:IDBDatabase,ownerKey:string,device:string){const id=`${ownerKey}:${device}`;const read=db.transaction(KEY_STORE,"readonly").objectStore(KEY_STORE);const existing=await requestResult(read.get(id) as IDBRequest<StoredKey|undefined>);if(existing)return existing.key;const key=await crypto.subtle.generateKey({name:"AES-GCM",length:256},false,["encrypt","decrypt"]);const tx=db.transaction(KEY_STORE,"readwrite");tx.objectStore(KEY_STORE).put({id,key,createdAt:Date.now()} satisfies StoredKey);await transactionDone(tx);return key;}

export function createOfflineEnvelope(operation:OfflineOperation,payload:Record<string,unknown>,basePlacementUpdatedAt:number):OfflineEnvelope{const now=Date.now();return{idempotencyKey:crypto.randomUUID(),clientVersion:OFFLINE_ITEM_VERSION,clientCreatedAt:now,expiresAt:now+OFFLINE_ITEM_TTL_MS,basePlacementUpdatedAt,operation,payload};}
export async function saveOfflineItem(ownerKey:string,entityId:number,envelope:OfflineEnvelope,status:OfflineItemStatus="queued"){const db=await openDb();const device=deviceId();const id=envelope.idempotencyKey;const key=await deviceKey(db,ownerKey,device);const iv=crypto.getRandomValues(new Uint8Array(12));const plaintext=new TextEncoder().encode(JSON.stringify(envelope));const ciphertext=await crypto.subtle.encrypt({name:"AES-GCM",iv:iv as Uint8Array<ArrayBuffer>,additionalData:additionalData({ownerKey,entityId,deviceId:device,id}) as Uint8Array<ArrayBuffer>},key,plaintext as Uint8Array<ArrayBuffer>);const record:StoredItem={id,ownerKey,entityId,deviceId:device,operation:envelope.operation,status,updatedAt:Date.now(),expiresAt:envelope.expiresAt,iv:bytesToBase64(iv),ciphertext:bytesToBase64(new Uint8Array(ciphertext))};const tx=db.transaction(ITEM_STORE,"readwrite");tx.objectStore(ITEM_STORE).put(record);await transactionDone(tx);return id;}
async function decryptItem(db:IDBDatabase,stored:StoredItem):Promise<OfflineItem>{const key=await deviceKey(db,stored.ownerKey,stored.deviceId);const iv=base64ToBytes(stored.iv);const ciphertext=base64ToBytes(stored.ciphertext);const plaintext=await crypto.subtle.decrypt({name:"AES-GCM",iv:iv as Uint8Array<ArrayBuffer>,additionalData:additionalData({ownerKey:stored.ownerKey,entityId:stored.entityId,deviceId:stored.deviceId,id:stored.id}) as Uint8Array<ArrayBuffer>},key,ciphertext as Uint8Array<ArrayBuffer>);return{id:stored.id,operation:stored.operation,status:stored.status,updatedAt:stored.updatedAt,expiresAt:stored.expiresAt,code:stored.code,message:stored.message,envelope:JSON.parse(new TextDecoder().decode(plaintext)) as OfflineEnvelope};}
export async function listOfflineItems(ownerKey:string,entityId:number){const db=await openDb();const read=db.transaction(ITEM_STORE,"readonly").objectStore(ITEM_STORE);const stored=(await requestResult(read.getAll() as IDBRequest<StoredItem[]>)).filter(item=>item.ownerKey===ownerKey&&item.entityId===entityId);const obsolete=stored.filter(item=>item.expiresAt+CONFLICT_REVIEW_TTL_MS<Date.now());if(obsolete.length){const tx=db.transaction(ITEM_STORE,"readwrite");for(const item of obsolete)tx.objectStore(ITEM_STORE).delete(item.id);await transactionDone(tx);}const obsoleteIds=new Set(obsolete.map(item=>item.id));const result:OfflineItem[]=[];for(const item of stored.filter(candidate=>!obsoleteIds.has(candidate.id))){try{result.push(await decryptItem(db,item));}catch{result.push({id:item.id,operation:item.operation,status:"rejected",updatedAt:item.updatedAt,expiresAt:item.expiresAt,code:"decryption_failed",message:"This device draft can no longer be decrypted and should be discarded.",envelope:{idempotencyKey:item.id,clientVersion:1,clientCreatedAt:item.updatedAt,expiresAt:item.expiresAt,basePlacementUpdatedAt:0,operation:item.operation,payload:{}}});}}return result.sort((a,b)=>b.updatedAt-a.updatedAt);}
export async function patchOfflineItem(id:string,patch:Partial<Pick<StoredItem,"status"|"code"|"message">>){const db=await openDb();const tx=db.transaction(ITEM_STORE,"readwrite");const store=tx.objectStore(ITEM_STORE);const record=await requestResult(store.get(id) as IDBRequest<StoredItem|undefined>);if(record)store.put({...record,...patch,updatedAt:Date.now()});await transactionDone(tx);}
export async function deleteOfflineItem(id:string){const db=await openDb();const tx=db.transaction(ITEM_STORE,"readwrite");tx.objectStore(ITEM_STORE).delete(id);await transactionDone(tx);}
