import { and,asc,desc,eq } from "drizzle-orm";
import { TRPCError } from "@trpc/server";
import { z } from "zod";
import { auditLogs,auditReceiptMirrors,auditVerificationRuns,documentScanJobs,identityAssuranceReviews,resilienceChecks,workPlanActions } from "../../drizzle/schema";
import { assertEntityCapability } from "../authz";
import { protectedProcedure,router } from "../_core/trpc";
import { writeAuditEvent } from "../services/audit";
import {auditReceiptBodyStatus,scanRetryAllowed} from "../services/assuranceRules";
import {storageGetSignedUrl} from "../storage";
import { requireDb } from "./shared";

const entityInput=z.object({entityId:z.number().int().positive()});
export const assuranceRouter=router({
  workspace:protectedProcedure.input(entityInput).query(async({ctx,input})=>{await assertEntityCapability(ctx.user.id,input.entityId,"audit.read");const db=await requireDb();const[identity,scans,resilience,verification,receipts]=await Promise.all([db.select().from(identityAssuranceReviews).where(eq(identityAssuranceReviews.entityId,input.entityId)).orderBy(desc(identityAssuranceReviews.createdAt)),db.select().from(documentScanJobs).where(eq(documentScanJobs.entityId,input.entityId)).orderBy(desc(documentScanJobs.createdAt)),db.select().from(resilienceChecks).where(eq(resilienceChecks.entityId,input.entityId)).orderBy(desc(resilienceChecks.createdAt)),db.select().from(auditVerificationRuns).where(eq(auditVerificationRuns.entityId,input.entityId)).orderBy(desc(auditVerificationRuns.startedAt)),db.select().from(auditReceiptMirrors).where(eq(auditReceiptMirrors.entityId,input.entityId)).orderBy(desc(auditReceiptMirrors.createdAt))]);return{identity,scans,resilience,verification,receiptHealth:{stored:receipts.filter(row=>row.status==="stored"||row.status==="verified").length,warning:receipts.filter(row=>row.status==="missing"||row.status==="mismatch").length}};}),
  createIdentityReview:protectedProcedure.input(entityInput.extend({userId:z.number().int().positive().optional(),assuranceType:z.enum(["mfa","sso","account_recovery","role_sign_off","access_review","break_glass","joiner_mover_leaver"]),provider:z.string().max(160).optional(),assuranceMethod:z.string().max(220).optional(),nextReviewAt:z.number().int().optional(),riskNotes:z.string().max(4000).optional()})).mutation(async({ctx,input})=>{await assertEntityCapability(ctx.user.id,input.entityId,"config.write");const db=await requireDb();const[record]=await db.insert(identityAssuranceReviews).values({...input,createdBy:ctx.user.id}).$returningId();await writeAuditEvent({actorUserId:ctx.user.id,entityId:input.entityId,action:"identity_assurance.created",resourceType:"identity_assurance_review",resourceId:record.id,sensitivity:"restricted",result:"success"});return record;}),
  decideIdentityReview:protectedProcedure.input(entityInput.extend({reviewId:z.number().int().positive(),status:z.enum(["passed","conditional","failed","revoked","expired"]),decisionNotes:z.string().min(5).max(4000),nextReviewAt:z.number().int().optional()})).mutation(async({ctx,input})=>{await assertEntityCapability(ctx.user.id,input.entityId,"config.write");const db=await requireDb();const[row]=await db.select().from(identityAssuranceReviews).where(and(eq(identityAssuranceReviews.id,input.reviewId),eq(identityAssuranceReviews.entityId,input.entityId))).limit(1);if(!row)throw new TRPCError({code:"NOT_FOUND"});if(row.createdBy===ctx.user.id)throw new TRPCError({code:"FORBIDDEN",message:"A different authorised user must approve the identity assurance review"});const now=Date.now();await db.update(identityAssuranceReviews).set({status:input.status,decisionNotes:input.decisionNotes,nextReviewAt:input.nextReviewAt,reviewedAt:now,reviewedBy:ctx.user.id,approvedBy:ctx.user.id}).where(eq(identityAssuranceReviews.id,row.id));await writeAuditEvent({actorUserId:ctx.user.id,entityId:input.entityId,action:"identity_assurance.decided",resourceType:"identity_assurance_review",resourceId:row.id,sensitivity:"restricted",result:"success",metadata:{status:input.status}});return{success:true};}),
  overrideScan:protectedProcedure.input(entityInput.extend({scanJobId:z.number().int().positive(),overrideReason:z.string().min(20).max(4000)})).mutation(async({ctx,input})=>{await assertEntityCapability(ctx.user.id,input.entityId,"document.write");const db=await requireDb();const[row]=await db.select().from(documentScanJobs).where(and(eq(documentScanJobs.id,input.scanJobId),eq(documentScanJobs.entityId,input.entityId))).limit(1);if(!row)throw new TRPCError({code:"NOT_FOUND"});if(!["quarantined","failed"].includes(row.status))throw new TRPCError({code:"BAD_REQUEST",message:"Only quarantined or failed scans can be overridden"});await db.update(documentScanJobs).set({status:"overridden",overrideReason:input.overrideReason,overriddenBy:ctx.user.id,completedAt:Date.now()}).where(eq(documentScanJobs.id,row.id));await writeAuditEvent({actorUserId:ctx.user.id,entityId:input.entityId,action:"document_scan.overridden",resourceType:"document_scan_job",resourceId:row.id,sensitivity:"restricted",result:"success"});return{success:true};}),
  retryScan:protectedProcedure.input(entityInput.extend({scanJobId:z.number().int().positive()})).mutation(async({ctx,input})=>{await assertEntityCapability(ctx.user.id,input.entityId,"document.write");const db=await requireDb();const[row]=await db.select().from(documentScanJobs).where(and(eq(documentScanJobs.id,input.scanJobId),eq(documentScanJobs.entityId,input.entityId))).limit(1);if(!row)throw new TRPCError({code:"NOT_FOUND"});if(!scanRetryAllowed(row.status))throw new TRPCError({code:"BAD_REQUEST",message:"Only failed or quarantined scan jobs can be resubmitted"});await db.update(documentScanJobs).set({status:"queued",attempts:row.attempts+1,lastAttemptAt:Date.now(),nextRetryAt:Date.now(),completedAt:null,verdict:null,threatName:null,overrideReason:null,overriddenBy:null}).where(eq(documentScanJobs.id,row.id));await writeAuditEvent({actorUserId:ctx.user.id,entityId:input.entityId,action:"document_scan.resubmitted",resourceType:"document_scan_job",resourceId:row.id,sensitivity:"restricted",result:"success"});return{success:true};}),
  createResilienceCheck:protectedProcedure.input(entityInput.extend({checkType:z.enum(["backup","restore","database","object_storage","notification","integration","scheduled_job","audit_chain","security_monitoring"]),title:z.string().min(3).max(220),frequencyDays:z.number().int().min(1).max(3650).optional(),ownerUserId:z.number().int().positive().optional(),nextDueAt:z.number().int().optional()})).mutation(async({ctx,input})=>{await assertEntityCapability(ctx.user.id,input.entityId,"config.write");const db=await requireDb();const[record]=await db.insert(resilienceChecks).values({...input,createdBy:ctx.user.id}).$returningId();return record;}),
  completeResilienceCheck:protectedProcedure.input(entityInput.extend({checkId:z.number().int().positive(),status:z.enum(["passed","warning","failed","waived"]),resultSummary:z.string().min(5).max(5000),durationMs:z.number().int().min(0).optional(),createCorrectiveAction:z.boolean().default(true)})).mutation(async({ctx,input})=>{await assertEntityCapability(ctx.user.id,input.entityId,"config.write");const db=await requireDb();const[row]=await db.select().from(resilienceChecks).where(and(eq(resilienceChecks.id,input.checkId),eq(resilienceChecks.entityId,input.entityId))).limit(1);if(!row)throw new TRPCError({code:"NOT_FOUND"});const now=Date.now();let correctiveWorkPlanId=row.correctiveWorkPlanId;await db.transaction(async tx=>{if(["failed","warning"].includes(input.status)&&input.createCorrectiveAction&&!correctiveWorkPlanId){const[action]=await tx.insert(workPlanActions).values({entityId:input.entityId,title:`Resolve ${row.title}`,description:input.resultSummary,sourceType:"manual",sourceId:row.id,ownerUserId:row.ownerUserId,priority:input.status==="failed"?"critical":"high",dueAt:now+(input.status==="failed"?3:14)*86_400_000,status:"open",createdBy:ctx.user.id}).$returningId();correctiveWorkPlanId=action.id;}await tx.update(resilienceChecks).set({status:input.status,resultSummary:input.resultSummary,durationMs:input.durationMs,lastCheckedAt:now,nextDueAt:row.frequencyDays?now+row.frequencyDays*86_400_000:null,correctiveWorkPlanId,completedBy:ctx.user.id}).where(eq(resilienceChecks.id,row.id));});return{success:true,correctiveWorkPlanId};}),
  verifyAuditChain:protectedProcedure.input(entityInput).mutation(async({ctx,input})=>{await assertEntityCapability(ctx.user.id,input.entityId,"audit.read");const db=await requireDb();const[events,receipts]=await Promise.all([db.select().from(auditLogs).orderBy(asc(auditLogs.id)),db.select().from(auditReceiptMirrors)]);let chainMismatches=0;for(let index=0;index<events.length;index++){const expected=index?events[index-1].eventHash:null;if(!events[index].eventHash||events[index].previousHash!==expected)chainMismatches++;}const receiptByEvent=new Map(receipts.map(row=>[row.auditEventId,row]));const scoped=events.filter(row=>row.entityId===input.entityId);let missingReceipts=0,verifiedReceipts=0,mismatchedReceipts=0;for(const event of scoped){const receipt=receiptByEvent.get(event.id);if(!receipt){missingReceipts++;continue;}let receiptStatus:"verified"|"missing"|"mismatch"="missing";try{const url=await storageGetSignedUrl(receipt.storageKey);const response=await fetch(url,{cache:"no-store"});if(response.ok)receiptStatus=auditReceiptBodyStatus(await response.json(),{id:event.id,eventHash:event.eventHash??""});else receiptStatus=response.status===404?"missing":"mismatch";}catch{receiptStatus="missing";}if(receiptStatus==="verified")verifiedReceipts++;else if(receiptStatus==="missing")missingReceipts++;else mismatchedReceipts++;await db.update(auditReceiptMirrors).set({status:receiptStatus,lastVerifiedAt:Date.now()}).where(eq(auditReceiptMirrors.id,receipt.id));}const receiptIssues=missingReceipts+mismatchedReceipts;const status=chainMismatches?"failed":receiptIssues?"warning":"passed";const[run]=await db.insert(auditVerificationRuns).values({entityId:input.entityId,rangeStartId:events[0]?.id,rangeEndId:events.at(-1)?.id,checkedEvents:events.length,chainMismatches,missingReceipts:receiptIssues,status,summary:`Verified ${events.length} linked audit events and ${verifiedReceipts} object receipts; ${chainMismatches} link mismatches, ${missingReceipts} missing and ${mismatchedReceipts} mismatched receipts.`,manifest:{scope:"global_chain_entity_object_receipts",entityEvents:scoped.length,verifiedReceipts,missingReceipts,mismatchedReceipts},startedAt:Date.now(),completedAt:Date.now(),createdBy:ctx.user.id}).$returningId();return{id:run.id,status,checkedEvents:events.length,chainMismatches,missingReceipts:receiptIssues,verifiedReceipts,mismatchedReceipts};}),
});
