import {beforeEach,describe,expect,it,vi} from "vitest";

const state=vi.hoisted(()=>({db:null as any,denied:false,placementUpdatedAt:1_000,nextReceipt:undefined as any,receipts:[] as any[],reports:[] as any[],incidents:[] as any[],transactionCount:0,currentTransaction:0}));
vi.mock("../authz",()=>({assertPlacementCapability:vi.fn(async()=>{if(state.denied)throw new Error("You are not assigned to this young person");return{placement:{id:3,entityId:1,propertyId:2,status:"active",updatedAt:new Date(state.placementUpdatedAt)}};})}));
vi.mock("./shared",()=>({requireDb:async()=>state.db}));
vi.mock("../services/audit",()=>({writeAuditEvent:vi.fn(async()=>undefined)}));

import {incidents,keyWorkerReports,offlineSyncReceipts} from "../../drizzle/schema";
import {offlineSyncRouter} from "./offlineSync";

function thenableReturning(id:number){return{$returningId:async()=>[{id}],then:(resolve:(value:unknown)=>unknown,reject:(reason:unknown)=>unknown)=>Promise.resolve(undefined).then(resolve,reject)};}
function buildDb(){const db:any={select:()=>({from:()=>({where:()=>({limit:async()=>state.nextReceipt?[state.nextReceipt]:[]})})}),insert:(table:unknown)=>({values:(value:any)=>{const write={...value,transactionId:state.currentTransaction};if(table===offlineSyncReceipts)state.receipts.push(write);if(table===keyWorkerReports)state.reports.push(write);if(table===incidents)state.incidents.push(write);return thenableReturning(table===incidents?202:table===keyWorkerReports?101:state.receipts.length);}}),transaction:async(callback:(tx:any)=>Promise<unknown>)=>{state.transactionCount+=1;state.currentTransaction=state.transactionCount;try{return await callback(db);}finally{state.currentTransaction=0;}}};return db;}
function item(operation:"key_worker_report"|"incident",key:string,basePlacementUpdatedAt=1_000){const now=Date.now();const common={operation,idempotencyKey:key,clientVersion:1 as const,clientCreatedAt:now,expiresAt:now+60_000,basePlacementUpdatedAt};if(operation==="incident")return{...common,payload:{entityId:1,propertyId:2,placementId:3,category:"safeguarding" as const,severity:"medium" as const,occurredAt:now,summary:"Factual summary",details:"A sufficiently detailed neutral chronology."}};return{...common,payload:{entityId:1,propertyId:2,placementId:3,reportType:"daily" as const,reportDate:now,discussions:"A factual discussion record",plan:"Follow up tomorrow",status:"submitted" as const}};}
function caller(){return offlineSyncRouter.createCaller({user:{id:7,openId:"worker-7",name:"Worker",email:null,loginMethod:null,role:"user",createdAt:new Date(),updatedAt:new Date(),lastSignedIn:new Date()},req:{} as any,res:{} as any} as any);}

describe("offline sync router integration",()=>{beforeEach(()=>{state.db=buildDb();state.denied=false;state.placementUpdatedAt=1_000;state.nextReceipt=undefined;state.receipts=[];state.reports=[];state.incidents=[];state.transactionCount=0;state.currentTransaction=0;});it("atomically applies reports and incidents, then returns a duplicate without reinserting",async()=>{const report=item("key_worker_report","11111111-1111-4111-8111-111111111111");const applied=await caller().syncBatch({entityId:1,items:[report]});expect(applied.results[0]).toMatchObject({status:"applied",resourceId:101});expect(state.reports).toHaveLength(1);expect(state.receipts).toHaveLength(1);expect(state.reports[0].transactionId).toBe(state.receipts[0].transactionId);expect(state.reports[0].transactionId).toBeGreaterThan(0);const receipt=state.receipts[0];state.nextReceipt={...receipt,status:"applied",resourceId:101};const duplicate=await caller().syncBatch({entityId:1,items:[report]});expect(duplicate.results[0].status).toBe("already_applied");expect(state.reports).toHaveLength(1);state.nextReceipt=undefined;const incident=item("incident","22222222-2222-4222-8222-222222222222");const incidentResult=await caller().syncBatch({entityId:1,items:[incident]});expect(incidentResult.results[0]).toMatchObject({status:"applied",resourceId:202});expect(state.incidents[0].transactionId).toBe(state.receipts[1].transactionId);});it("persists rejected and stale-conflict receipts without creating business records",async()=>{state.denied=true;const rejected=await caller().syncBatch({entityId:1,items:[item("key_worker_report","33333333-3333-4333-8333-333333333333")]});expect(rejected.results[0]).toMatchObject({status:"rejected",code:"access_changed"});expect(state.receipts[0]).toMatchObject({status:"rejected",conflictCode:"access_changed",transactionId:0});state.denied=false;state.nextReceipt=undefined;state.placementUpdatedAt=2_000;const conflict=await caller().syncBatch({entityId:1,items:[item("incident","44444444-4444-4444-8444-444444444444",1_000)]});expect(conflict.results[0]).toMatchObject({status:"conflict",code:"placement_changed"});expect(state.receipts[1]).toMatchObject({status:"conflict",conflictCode:"placement_changed"});expect(state.reports).toHaveLength(0);expect(state.incidents).toHaveLength(0);});});
