import { and, eq } from "drizzle-orm";
import { TRPCError } from "@trpc/server";
import { z } from "zod";
import {
  clockEvents, curfewChecks, handovers, incidents, keyWorkerReports, loneWorkerCheckIns, loneWorkerSessions,
  maintenanceJobs, medicationAdministrations, medications, missingEpisodes, offlineSyncReceipts, propertyChecks,
  propertyVisitors, residentFinanceAccounts, residentFinanceTransactions, shifts,
} from "../../drizzle/schema";
import { assertPlacementCapability } from "../authz";
import { protectedProcedure, router } from "../_core/trpc";
import { writeAuditEvent } from "../services/audit";
import { encryptSensitive } from "../services/crypto";
import { assessIdempotency, assessOfflineEnvelope, offlinePayloadHash, OFFLINE_SCHEMA_VERSION } from "../services/offlineSyncRules";
import { calculateSignedAmount } from "../services/staffWorkspacePolicy";
import { requireAttendanceOverride } from "../services/workspaceGuards";
import { requireDb } from "./shared";

const id = z.number().int().positive();
const scope = z.object({ entityId: id, propertyId: id, placementId: id });
const envelope = z.object({ idempotencyKey: z.string().uuid(), clientVersion: z.literal(OFFLINE_SCHEMA_VERSION), clientCreatedAt: z.number().int(), expiresAt: z.number().int(), basePlacementUpdatedAt: z.number().int() });
const reportPayload = scope.extend({ reportType: z.enum(["daily", "weekly", "monthly_review"]), reportDate: z.number().int(), mood: z.string().max(80).optional(), attitude: z.string().max(120).optional(), learning: z.string().max(8000).optional(), enthusiasm: z.string().max(120).optional(), discussions: z.string().max(8000).optional(), pointsToNote: z.string().max(8000).optional(), plan: z.string().max(8000).optional(), nextReviewAt: z.number().int().optional(), suggestions: z.string().max(8000).optional(), status: z.enum(["draft", "submitted"]) }).strict();
const incidentPayload = scope.extend({ category: z.enum(["safeguarding", "missing", "exploitation", "police", "abuse_allegation", "child_protection_enquiry", "restraint", "health_safety", "complaint", "other"]), severity: z.enum(["low", "medium", "high", "critical"]), occurredAt: z.number().int(), summary: z.string().min(5).max(240), details: z.string().min(20).max(12000), immediateActions: z.string().max(8000).optional() }).strict();
const clockPayload = scope.extend({ shiftId: id, eventType: z.enum(["clock_in", "clock_out"]), occurredAt: z.number().int(), latitude: z.number().min(-90).max(90).optional(), longitude: z.number().min(-180).max(180).optional(), accuracyMetres: z.number().nonnegative().max(10000).optional(), distanceMetres: z.number().nonnegative().max(100000).optional(), locationState: z.enum(["on_site", "off_site", "unavailable", "manual"]), overrideReason: z.string().max(2000).optional() }).strict().superRefine((value, context) => { if (value.locationState !== "on_site" && !value.overrideReason?.trim()) context.addIssue({ code: "custom", path: ["overrideReason"], message: "An off-site, manual or unavailable location requires a reason." }); });
const handoverPayload = scope.extend({ shiftId: id.optional(), summary: z.string().min(5).max(10000), risks: z.string().max(8000).optional(), outstandingActions: z.string().max(8000).optional(), sensitivity: z.enum(["operational", "safeguarding", "restricted"]).default("operational") }).strict();
const visitorPayload = scope.extend({ visitorType: z.enum(["friend", "relative", "professional", "contractor", "public_official", "other"]), name: z.string().min(2).max(180), relationship: z.string().max(220).optional(), purpose: z.string().min(2).max(2000), idCheckStatus: z.enum(["not_required", "not_checked", "verified", "declined", "unavailable"]), identityDocumentId: id.optional(), arrivedAt: z.number().int(), expectedDepartureAt: z.number().int().optional(), notes: z.string().max(4000).optional() }).strict();
const curfewPayload = scope.extend({ curfewPlanId: id, expectedAt: z.number().int(), actualAt: z.number().int().optional(), status: z.enum(["met", "late", "absent", "authorised_away", "not_applicable", "pending"]), contactAttempts: z.string().max(5000).optional(), reason: z.string().max(5000).optional(), escalationRequired: z.boolean(), actionTaken: z.string().max(5000).optional() }).strict();
const missingPayload = scope.extend({ incidentId: id.optional(), missingAt: z.number().int(), discoveredAt: z.number().int(), policeContactedAt: z.number().int().optional(), policeReference: z.string().max(120).optional(), riskLevel: z.enum(["low", "medium", "high", "critical"]), circumstances: z.string().min(10).max(12000), actions: z.string().min(5).max(12000), notifications: z.record(z.string(), z.unknown()).optional() }).strict();
const medicationPayload = scope.extend({ medicationId: id, outcome: z.enum(["taken", "refused", "omitted", "unavailable", "asleep", "away", "other"]), doseAcknowledged: z.string().max(120).optional(), reason: z.string().max(5000).optional(), actionTaken: z.string().max(5000).optional(), escalationRequired: z.boolean() }).strict();
const checkPayload = scope.extend({ unitId: id.optional(), shiftId: id.optional(), checkType: z.enum(["room_check", "property_check", "fire_check", "night_check", "health_safety", "welfare", "other"]), authorityBasis: z.enum(["scheduled", "consent", "risk_assessment", "emergency", "policy", "other"]), checklist: z.array(z.object({ key: z.string().min(1).max(80), label: z.string().min(1).max(180), result: z.enum(["pass", "fail", "not_applicable"]), note: z.string().max(1000).optional() })).min(1).max(100), findings: z.string().max(6000).optional(), privacyNotes: z.string().max(4000).optional(), youngPersonPresent: z.boolean(), result: z.enum(["pass", "issues_found", "urgent_action"]) }).strict();
const maintenancePayload = scope.extend({ unitId: id.optional(), propertyCheckId: id.optional(), incidentId: id.optional(), title: z.string().min(3).max(220), category: z.enum(["plumbing", "electrical", "heating", "fire_safety", "security", "furniture", "appliance", "fabric", "pest", "cleaning", "other"]), priority: z.enum(["routine", "urgent", "emergency"]), description: z.string().min(5).max(6000), accessNotes: z.string().max(4000).optional(), targetAt: z.number().int().optional() }).strict();
const financePayload = scope.extend({ accountId: id, transactionType: z.enum(["deposit", "withdrawal", "purchase", "refund", "adjustment", "reversal"]), amount: z.number().positive().max(1_000_000), purpose: z.string().min(2).max(5000), counterparty: z.string().max(2000).optional(), receiptDocumentId: id.optional(), expectedAccountVersion: z.number().int().positive(), occurredAt: z.number().int() }).strict();
const loneWorkerPayload = scope.extend({ sessionId: id, checkInType: z.enum(["scheduled", "manual", "help_requested", "session_end"]), wellbeingStatus: z.enum(["safe", "concern", "help_required"]), occurredAt: z.number().int(), latitude: z.number().min(-90).max(90).optional(), longitude: z.number().min(-180).max(180).optional(), accuracyMetres: z.number().nonnegative().max(10000).optional(), locationState: z.enum(["on_site", "off_site", "unavailable", "manual"]), note: z.string().max(4000).optional(), expectedSessionVersion: z.number().int().positive() }).strict();

export const offlineSyncItemSchema = z.discriminatedUnion("operation", [
  envelope.extend({ operation: z.literal("key_worker_report"), payload: reportPayload }).strict(),
  envelope.extend({ operation: z.literal("incident"), payload: incidentPayload }).strict(),
  envelope.extend({ operation: z.literal("clock_event"), payload: clockPayload }).strict(),
  envelope.extend({ operation: z.literal("handover"), payload: handoverPayload }).strict(),
  envelope.extend({ operation: z.literal("visitor_entry"), payload: visitorPayload }).strict(),
  envelope.extend({ operation: z.literal("curfew_check"), payload: curfewPayload }).strict(),
  envelope.extend({ operation: z.literal("missing_episode"), payload: missingPayload }).strict(),
  envelope.extend({ operation: z.literal("medication_administration"), payload: medicationPayload }).strict(),
  envelope.extend({ operation: z.literal("property_check"), payload: checkPayload }).strict(),
  envelope.extend({ operation: z.literal("maintenance_job"), payload: maintenancePayload }).strict(),
  envelope.extend({ operation: z.literal("resident_finance_transaction"), payload: financePayload }).strict(),
  envelope.extend({ operation: z.literal("lone_worker_check_in"), payload: loneWorkerPayload }).strict(),
]);

type SyncItem = z.infer<typeof offlineSyncItemSchema>;
type AppliedResult = { resourceId: number; resourceType: string };

async function storeOutcome(userId: number, item: SyncItem, hash: string, status: "conflict" | "rejected", code: string, message: string) {
  const db = await requireDb();
  await db.insert(offlineSyncReceipts).values({ entityId: item.payload.entityId, userId, idempotencyKey: item.idempotencyKey, operation: item.operation, payloadHash: hash, clientCreatedAt: item.clientCreatedAt, clientVersion: item.clientVersion, status, conflictCode: code, conflictMessage: message });
  return { idempotencyKey: item.idempotencyKey, status, code, message };
}

async function applyItem(userId: number, item: SyncItem, db: any): Promise<AppliedResult | { conflictCode: string; conflictMessage: string }> {
  // Every payload has already passed the strict operation-specific Zod schema above.
  // A local structural view avoids TypeScript losing the discriminant after aliasing.
  const p = item.payload as Record<string, any>;
  if (item.operation === "key_worker_report") { const [row] = await db.insert(keyWorkerReports).values({ entityId: p.entityId, propertyId: p.propertyId, placementId: p.placementId, reportType: p.reportType, reportDate: p.reportDate, mood: p.mood, attitude: p.attitude, learning: p.learning, enthusiasm: p.enthusiasm, discussions: p.discussions, pointsToNote: p.pointsToNote, plan: p.plan, nextReviewAt: p.nextReviewAt, suggestions: p.suggestions, status: p.status, authorUserId: userId }).$returningId(); return { resourceId: row.id, resourceType: "key_worker_report" }; }
  if (item.operation === "incident") { const review = ["exploitation", "police", "abuse_allegation", "child_protection_enquiry", "restraint"].includes(p.category) || p.severity === "critical"; const [row] = await db.insert(incidents).values({ entityId: p.entityId, propertyId: p.propertyId, placementId: p.placementId, category: p.category, severity: p.severity, occurredAt: p.occurredAt, summary: p.summary, details: p.details, immediateActions: p.immediateActions, createdBy: userId, notifiability: review ? "unreviewed" : "not_notifiable", notificationDueAt: review ? Date.now() : null, status: review ? "under_review" : "open" }).$returningId(); return { resourceId: row.id, resourceType: "incident" }; }
  if (item.operation === "clock_event") { const [shift] = await db.select().from(shifts).where(and(eq(shifts.id, p.shiftId), eq(shifts.propertyId, p.propertyId), eq(shifts.assignedUserId, userId))).limit(1); if (!shift) return { conflictCode: "shift_assignment_changed", conflictMessage: "The shift is no longer assigned to this worker." }; requireAttendanceOverride({ locationState: p.locationState, overrideReason: p.overrideReason }); const [row] = await db.insert(clockEvents).values({ entityId: p.entityId, propertyId: p.propertyId, shiftId: p.shiftId, userId, eventType: p.eventType, occurredAt: p.occurredAt, latitude: p.latitude?.toString(), longitude: p.longitude?.toString(), accuracyMetres: p.accuracyMetres?.toString(), distanceMetres: p.distanceMetres?.toString(), locationState: p.locationState, overrideReason: p.overrideReason }).$returningId(); return { resourceId: row.id, resourceType: "clock_event" }; }
  if (item.operation === "handover") { const [row] = await db.insert(handovers).values({ entityId: p.entityId, propertyId: p.propertyId, shiftId: p.shiftId, summary: p.summary, risks: p.risks, outstandingActions: p.outstandingActions, sensitivity: p.sensitivity, createdBy: userId }).$returningId(); return { resourceId: row.id, resourceType: "handover" }; }
  if (item.operation === "visitor_entry") { const [row] = await db.insert(propertyVisitors).values({ entityId: p.entityId, propertyId: p.propertyId, placementId: p.placementId, visitorType: p.visitorType, nameCiphertext: encryptSensitive(p.name), relationshipCiphertext: p.relationship ? encryptSensitive(p.relationship) : undefined, purposeCiphertext: encryptSensitive(p.purpose), idCheckStatus: p.idCheckStatus, identityDocumentId: p.identityDocumentId, arrivedAt: p.arrivedAt, expectedDepartureAt: p.expectedDepartureAt, notesCiphertext: p.notes ? encryptSensitive(p.notes) : undefined, createdBy: userId }).$returningId(); return { resourceId: row.id, resourceType: "property_visitor" }; }
  if (item.operation === "curfew_check") { const [row] = await db.insert(curfewChecks).values({ entityId: p.entityId, placementId: p.placementId, curfewPlanId: p.curfewPlanId, expectedAt: p.expectedAt, actualAt: p.actualAt, status: p.status, contactAttemptsCiphertext: p.contactAttempts ? encryptSensitive(p.contactAttempts) : undefined, reasonCiphertext: p.reason ? encryptSensitive(p.reason) : undefined, escalationRequired: p.escalationRequired ? 1 : 0, actionTakenCiphertext: p.actionTaken ? encryptSensitive(p.actionTaken) : undefined, createdBy: userId }).$returningId(); return { resourceId: row.id, resourceType: "curfew_check" }; }
  if (item.operation === "missing_episode") { const [row] = await db.insert(missingEpisodes).values({ entityId: p.entityId, propertyId: p.propertyId, placementId: p.placementId, incidentId: p.incidentId, missingAt: p.missingAt, discoveredAt: p.discoveredAt, policeContactedAt: p.policeContactedAt, policeReference: p.policeReference, riskLevel: p.riskLevel, circumstancesCiphertext: encryptSensitive(p.circumstances), actionsCiphertext: encryptSensitive(p.actions), notifications: p.notifications, createdBy: userId }).$returningId(); return { resourceId: row.id, resourceType: "missing_episode" }; }
  if (item.operation === "medication_administration") { const [medicine] = await db.select().from(medications).where(and(eq(medications.id, p.medicationId), eq(medications.placementId, p.placementId))).limit(1); if (!medicine) return { conflictCode: "medication_changed", conflictMessage: "The medication is no longer available for this placement." }; const now = p.outcome === "taken" ? item.clientCreatedAt : undefined; const [row] = await db.insert(medicationAdministrations).values({ entityId: p.entityId, placementId: p.placementId, medicationId: p.medicationId, scheduledAt: medicine.nextDueAt ?? item.clientCreatedAt, administeredAt: now, outcome: p.outcome, doseAcknowledged: p.doseAcknowledged, reasonCiphertext: p.reason ? encryptSensitive(p.reason) : undefined, actionTakenCiphertext: p.actionTaken ? encryptSensitive(p.actionTaken) : undefined, escalationRequired: p.escalationRequired ? 1 : 0, createdBy: userId }).$returningId(); return { resourceId: row.id, resourceType: "medication_administration" }; }
  if (item.operation === "property_check") { const [row] = await db.insert(propertyChecks).values({ entityId: p.entityId, propertyId: p.propertyId, unitId: p.unitId, placementId: p.placementId, shiftId: p.shiftId, checkType: p.checkType, authorityBasis: p.authorityBasis, checklistSnapshot: p.checklist, findingsCiphertext: p.findings ? encryptSensitive(p.findings) : undefined, privacyNotesCiphertext: p.privacyNotes ? encryptSensitive(p.privacyNotes) : undefined, youngPersonPresent: p.youngPersonPresent ? 1 : 0, result: p.result, status: "submitted", completedAt: item.clientCreatedAt, createdBy: userId }).$returningId(); return { resourceId: row.id, resourceType: "property_check" }; }
  if (item.operation === "maintenance_job") { const [row] = await db.insert(maintenanceJobs).values({ entityId: p.entityId, propertyId: p.propertyId, unitId: p.unitId, propertyCheckId: p.propertyCheckId, incidentId: p.incidentId, title: p.title, category: p.category, priority: p.priority, descriptionCiphertext: encryptSensitive(p.description), accessNotesCiphertext: p.accessNotes ? encryptSensitive(p.accessNotes) : undefined, targetAt: p.targetAt, createdBy: userId }).$returningId(); return { resourceId: row.id, resourceType: "maintenance_job" }; }
  if (item.operation === "resident_finance_transaction") { const [account] = await db.select().from(residentFinanceAccounts).where(and(eq(residentFinanceAccounts.id, p.accountId), eq(residentFinanceAccounts.placementId, p.placementId))).limit(1); if (!account || account.version !== p.expectedAccountVersion) return { conflictCode: "account_version_changed", conflictMessage: "The resident balance changed while this item was offline. Review the account before resubmitting." }; const nextBalance = Number(account.balance) + calculateSignedAmount(p.transactionType, p.amount); if (nextBalance < 0) return { conflictCode: "negative_balance", conflictMessage: "The transaction would make the resident account negative." }; const [row] = await db.insert(residentFinanceTransactions).values({ entityId: p.entityId, placementId: p.placementId, accountId: p.accountId, transactionType: p.transactionType, amount: p.amount.toFixed(2), balanceAfter: nextBalance.toFixed(2), purposeCiphertext: encryptSensitive(p.purpose), counterpartyCiphertext: p.counterparty ? encryptSensitive(p.counterparty) : undefined, receiptDocumentId: p.receiptDocumentId, occurredAt: p.occurredAt, createdBy: userId }).$returningId(); await db.update(residentFinanceAccounts).set({ balance: nextBalance.toFixed(2), version: account.version + 1 }).where(eq(residentFinanceAccounts.id, account.id)); return { resourceId: row.id, resourceType: "resident_finance_transaction" }; }
  const [session] = await db.select().from(loneWorkerSessions).where(and(eq(loneWorkerSessions.id, p.sessionId), eq(loneWorkerSessions.userId, userId))).limit(1); if (!session || session.version !== p.expectedSessionVersion) return { conflictCode: "session_version_changed", conflictMessage: "The lone-worker session changed while this item was offline." }; const [row] = await db.insert(loneWorkerCheckIns).values({ entityId: p.entityId, sessionId: p.sessionId, checkInType: p.checkInType, wellbeingStatus: p.wellbeingStatus, occurredAt: p.occurredAt, latitude: p.latitude?.toString(), longitude: p.longitude?.toString(), accuracyMetres: p.accuracyMetres?.toString(), locationState: p.locationState, noteCiphertext: p.note ? encryptSensitive(p.note) : undefined, createdBy: userId }).$returningId(); await db.update(loneWorkerSessions).set({ lastCheckInAt: p.occurredAt, nextCheckInDueAt: p.occurredAt + session.checkInIntervalMinutes * 60_000, status: p.checkInType === "session_end" ? "completed" : p.wellbeingStatus === "help_required" ? "escalated" : "active", completedAt: p.checkInType === "session_end" ? p.occurredAt : session.completedAt, escalatedAt: p.wellbeingStatus === "help_required" ? p.occurredAt : session.escalatedAt, version: session.version + 1 }).where(eq(loneWorkerSessions.id, session.id)); return { resourceId: row.id, resourceType: "lone_worker_check_in" };
}

async function reconcile(userId: number, item: SyncItem) {
  const db = await requireDb(); const hash = offlinePayloadHash(item);
  const [prior] = await db.select().from(offlineSyncReceipts).where(and(eq(offlineSyncReceipts.userId, userId), eq(offlineSyncReceipts.idempotencyKey, item.idempotencyKey))).limit(1);
  const idempotency = assessIdempotency(prior?.payloadHash, hash);
  if (idempotency === "key_reused") return { idempotencyKey: item.idempotencyKey, status: "conflict" as const, code: "idempotency_key_reused", message: "This submission key was already used for different content. Review and re-queue it." };
  if (prior) return { idempotencyKey: item.idempotencyKey, status: prior.status === "applied" ? "already_applied" as const : prior.status, code: prior.conflictCode ?? undefined, message: prior.conflictMessage ?? undefined, resourceId: prior.resourceId ?? undefined };
  const capability = item.operation === "incident" || item.operation === "missing_episode" ? "incident.write" : item.operation === "medication_administration" ? "medication.write" : item.operation === "resident_finance_transaction" ? "resident_finance.write" : item.operation === "key_worker_report" ? "young_person.write" : "frontline.write";
  let guarded; try { guarded = await assertPlacementCapability(userId, item.payload.placementId, capability); } catch (error) { return storeOutcome(userId, item, hash, "rejected", "access_changed", error instanceof Error ? error.message : "Current placement access was denied"); }
  const placement = guarded.placement;
  if (placement.entityId !== item.payload.entityId || placement.propertyId !== item.payload.propertyId) return storeOutcome(userId, item, hash, "conflict", "scope_changed", "The placement no longer belongs to the selected entity and property.");
  const issue = assessOfflineEnvelope({ clientVersion: item.clientVersion, clientCreatedAt: item.clientCreatedAt, expiresAt: item.expiresAt, basePlacementUpdatedAt: item.basePlacementUpdatedAt, placementUpdatedAt: placement.updatedAt.getTime(), placementStatus: placement.status, now: Date.now() });
  if (issue) return storeOutcome(userId, item, hash, "conflict", issue.code, issue.message);
  try {
    const applied = await db.transaction(async (tx: any) => {
      const result = await applyItem(userId, item, tx);
      if ("conflictCode" in result) return result;
      await tx.insert(offlineSyncReceipts).values({ entityId: item.payload.entityId, userId, idempotencyKey: item.idempotencyKey, operation: item.operation, payloadHash: hash, clientCreatedAt: item.clientCreatedAt, clientVersion: item.clientVersion, status: "applied", resourceType: result.resourceType, resourceId: result.resourceId });
      return result;
    });
    if ("conflictCode" in applied) return storeOutcome(userId, item, hash, "conflict", applied.conflictCode, applied.conflictMessage);
    await writeAuditEvent({ actorUserId: userId, entityId: item.payload.entityId, propertyId: item.payload.propertyId, action: "offline_sync.applied", resourceType: applied.resourceType, resourceId: applied.resourceId, sensitivity: "safeguarding", result: "success", metadata: { operation: item.operation, idempotencyKey: item.idempotencyKey, clientCreatedAt: item.clientCreatedAt } });
    return { idempotencyKey: item.idempotencyKey, status: "applied" as const, resourceId: applied.resourceId };
  } catch (error) {
    const [winner] = await db.select().from(offlineSyncReceipts).where(and(eq(offlineSyncReceipts.userId, userId), eq(offlineSyncReceipts.idempotencyKey, item.idempotencyKey))).limit(1);
    if (winner?.payloadHash === hash) return { idempotencyKey: item.idempotencyKey, status: winner.status === "applied" ? "already_applied" as const : winner.status, resourceId: winner.resourceId ?? undefined, code: winner.conflictCode ?? undefined, message: winner.conflictMessage ?? undefined };
    throw error;
  }
}

export const offlineSyncRouter = router({
  syncBatch: protectedProcedure.input(z.object({ entityId: id, items: z.array(offlineSyncItemSchema).min(1).max(20) }).strict()).mutation(async ({ ctx, input }) => {
    if (input.items.some(item => item.payload.entityId !== input.entityId)) throw new TRPCError({ code: "BAD_REQUEST", message: "Every queued item must match the selected entity" });
    const results = []; for (const item of input.items) results.push(await reconcile(ctx.user.id, item)); return { serverTime: Date.now(), results };
  }),
});
