import{beforeEach,describe,expect,it,vi}from"vitest";
const state=vi.hoisted(()=>({db:null as any,propertyDenied:false,eligible:true,current:null as any,shiftRows:[] as any[]}));
vi.mock("../authz",()=>({assertPropertyCapability:vi.fn(async()=>{if(state.propertyDenied)throw new Error("Property access denied");return{role:"registered_manager",allProperties:false};}),assertEntityCapability:vi.fn(async()=>({role:"registered_manager"})),getUserAccess:vi.fn(async()=>({user:{operationalRole:"registered_manager"},memberships:[]})),listAccessiblePropertyIds:vi.fn(async()=>[10])}));
vi.mock("./shared",()=>({requireDb:async()=>state.db}));vi.mock("../services/audit",()=>({writeAuditEvent:vi.fn(async()=>undefined)}));vi.mock("../services/crypto",()=>({encryptSensitive:vi.fn((value:string)=>`encrypted:${value}`)}));vi.mock("../services/rotaPolicyRules",()=>({evaluateWorkingTime:vi.fn(()=>[])}));
import{entityMemberships,propertyAssignments,shifts,workingTimePolicies}from"../../drizzle/schema";import{operationsRouter}from"./operations";
function thenable<T>(value:T){return{then:(resolve:(value:T)=>unknown,reject:(reason:unknown)=>unknown)=>Promise.resolve(value).then(resolve,reject)};}
function buildDb(){return{select:()=>({from:(table:unknown)=>({where:()=>{const rows=table===shifts?state.shiftRows:table===entityMemberships?(state.eligible?[{userId:7,operationalRole:"support_worker",allProperties:0}]:[]):table===propertyAssignments?(state.eligible?[{userId:7}]:[]):table===workingTimePolicies?[]:[];return Object.assign(thenable(rows),{limit:async()=>table===shifts?[state.current]:rows.slice(0,1),orderBy:()=>({limit:async()=>[]})});}})})};}
function caller(){return operationsRouter.createCaller({user:{id:1,openId:"manager-1",name:"Manager",email:null,loginMethod:null,role:"user",operationalRole:"registered_manager",accountStatus:"active",createdAt:new Date(),updatedAt:new Date(),lastSignedIn:new Date()},req:{} as any,res:{} as any}as any);}
const input=()=>({entityId:1,shiftId:4,propertyId:10,assignedUserId:7,startsAt:200_000,endsAt:240_000,expectedUpdatedAt:10_000});
describe("operations.rescheduleShift router",()=>{beforeEach(()=>{state.propertyDenied=false;state.eligible=true;state.current={id:4,entityId:1,propertyId:10,assignedUserId:2,title:"Support",startsAt:100_000,endsAt:140_000,requiredRole:null,status:"assigned",coverageState:"covered",updatedAt:new Date(10_000)};state.shiftRows=[state.current];state.db=buildDb();});it("rejects a stale drag proposal before scheduling checks",async()=>{await expect(caller().rescheduleShift({...input(),expectedUpdatedAt:1_000})).rejects.toThrow(/changed by another user/);});it("denies a manager outside the source or target property scope",async()=>{state.propertyDenied=true;await expect(caller().rescheduleShift(input())).rejects.toThrow(/Property access denied/);});it("rejects a worker without active entity and target-property eligibility",async()=>{state.eligible=false;await expect(caller().rescheduleShift(input())).rejects.toThrow(/active Key Worker/);});it("requires a meaningful override when an overlap remains",async()=>{state.shiftRows=[state.current,{...state.current,id:99,assignedUserId:7,startsAt:210_000,endsAt:250_000}];await expect(caller().rescheduleShift(input())).rejects.toThrow(/needs manager review/);await expect(caller().rescheduleShift({...input(),overrideReason:"short"})).rejects.toThrow(/at least 20/);});});
