import {and,desc,eq,inArray} from "drizzle-orm";
import {TRPCError} from "@trpc/server";
import {z} from "zod";
import {qualityReviewConsultations,qualityReviewEvidence,qualityReviews} from "../../drizzle/schema";
import {assertEntityCapability,assertPropertyCapability,listAccessiblePropertyIds} from "../authz";
import {protectedProcedure,router} from "../_core/trpc";
import {writeAuditEvent} from "../services/audit";
import {independentReviewAllowed,missingReviewAudiences,qualityPeriodError} from "../services/upgradeRules";
import {requireDb} from "./shared";

const entity=z.object({entityId:z.number().int().positive()});
async function reviewForWrite(userId:number,entityId:number,reviewId:number){const db=await requireDb();const[row]=await db.select().from(qualityReviews).where(and(eq(qualityReviews.id,reviewId),eq(qualityReviews.entityId,entityId))).limit(1);if(!row)throw new TRPCError({code:"NOT_FOUND"});if(row.propertyId)await assertPropertyCapability(userId,entityId,row.propertyId,"compliance.write");else await assertEntityCapability(userId,entityId,"compliance.write");return{db,row};}
export const qualityRouter=router({
  workspace:protectedProcedure.input(entity).query(async({ctx,input})=>{const access=await assertEntityCapability(ctx.user.id,input.entityId,"compliance.read");const propertyIds=await listAccessiblePropertyIds(ctx.user.id,input.entityId,"property.read");const db=await requireDb();const all=await db.select().from(qualityReviews).where(eq(qualityReviews.entityId,input.entityId)).orderBy(desc(qualityReviews.periodEnd));const reviews=all.filter(row=>row.propertyId?propertyIds.includes(row.propertyId):access.role==="owner"||access.allProperties);const ids=reviews.map(row=>row.id);const consultations=ids.length?await db.select().from(qualityReviewConsultations).where(inArray(qualityReviewConsultations.qualityReviewId,ids)):[];const evidence=ids.length?await db.select().from(qualityReviewEvidence).where(inArray(qualityReviewEvidence.qualityReviewId,ids)):[];return{reviews,consultations,evidence};}),
  createReview:protectedProcedure.input(entity.extend({propertyId:z.number().int().positive().optional(),title:z.string().min(3).max(220),periodStart:z.number().int(),periodEnd:z.number().int(),ownerUserId:z.number().int().positive().optional()})).mutation(async({ctx,input})=>{const periodError=qualityPeriodError(input.periodStart,input.periodEnd);if(periodError)throw new TRPCError({code:"BAD_REQUEST",message:periodError});if(input.propertyId)await assertPropertyCapability(ctx.user.id,input.entityId,input.propertyId,"compliance.write");else await assertEntityCapability(ctx.user.id,input.entityId,"compliance.write");const db=await requireDb();const[record]=await db.insert(qualityReviews).values({...input,submissionDueAt:input.periodEnd+28*86_400_000,nextReviewDueAt:input.periodEnd+183*86_400_000,createdBy:ctx.user.id}).$returningId();return record;}),
  addConsultation:protectedProcedure.input(entity.extend({reviewId:z.number().int().positive(),audience:z.enum(["young_person","placing_authority","staff","professional","family_advocate","other"]),participantReference:z.string().max(180).optional(),method:z.enum(["conversation","meeting","telephone","email","survey","written","advocate","other"]),responseStatus:z.enum(["planned","invited","responded","declined","no_response","not_applicable"]),accessibilityNeeds:z.string().max(3000).optional(),responseSummary:z.string().max(6000).optional(),noResponseReason:z.string().max(3000).optional()})).mutation(async({ctx,input})=>{const{db,row}=await reviewForWrite(ctx.user.id,input.entityId,input.reviewId);const{reviewId,...values}=input;const[record]=await db.insert(qualityReviewConsultations).values({...values,qualityReviewId:reviewId,invitedAt:Date.now(),respondedAt:input.responseStatus==="responded"?Date.now():undefined,recordedBy:ctx.user.id}).$returningId();if(row.status==="draft")await db.update(qualityReviews).set({status:"consultation"}).where(eq(qualityReviews.id,row.id));return record;}),
  addEvidence:protectedProcedure.input(entity.extend({reviewId:z.number().int().positive(),category:z.enum(["outcomes","safeguarding","staffing","placement_stability","complaints","incidents","compliance","feedback","education_health","independence","other"]),title:z.string().min(3).max(220),status:z.enum(["identified","collected","reviewed","excluded"]).default("identified"),analysis:z.string().max(6000).optional(),exclusionReason:z.string().max(3000).optional(),documentId:z.number().int().positive().optional()})).mutation(async({ctx,input})=>{const{db,row}=await reviewForWrite(ctx.user.id,input.entityId,input.reviewId);const{reviewId,...values}=input;const[record]=await db.insert(qualityReviewEvidence).values({...values,qualityReviewId:reviewId,addedBy:ctx.user.id,reviewedAt:input.status==="reviewed"?Date.now():undefined,reviewedBy:input.status==="reviewed"?ctx.user.id:undefined}).$returningId();if(["draft","consultation"].includes(row.status))await db.update(qualityReviews).set({status:"evidence_review"}).where(eq(qualityReviews.id,row.id));return record;}),
  completeReview:protectedProcedure.input(entity.extend({reviewId:z.number().int().positive(),methodology:z.string().min(20).max(8000),strengths:z.string().min(10).max(8000),shortfalls:z.string().min(10).max(8000),outcomesSummary:z.string().min(10).max(8000),youngPeopleSummary:z.string().min(10).max(8000),consultationSummary:z.string().min(10).max(8000),managementEvaluation:z.string().min(10).max(8000)})).mutation(async({ctx,input})=>{const{db,row}=await reviewForWrite(ctx.user.id,input.entityId,input.reviewId);const consultations=await db.select().from(qualityReviewConsultations).where(eq(qualityReviewConsultations.qualityReviewId,row.id));const missing=missingReviewAudiences(consultations);if(missing.length)throw new TRPCError({code:"BAD_REQUEST",message:`Consultation evidence is incomplete: ${missing.join(", ")}`});const evidence=await db.select().from(qualityReviewEvidence).where(eq(qualityReviewEvidence.qualityReviewId,row.id));if(!evidence.some(item=>item.status==="reviewed"))throw new TRPCError({code:"BAD_REQUEST",message:"At least one evidence item must be reviewed"});const{reviewId,...values}=input;await db.update(qualityReviews).set({...values,status:"report_draft",completedAt:Date.now(),completedBy:ctx.user.id}).where(eq(qualityReviews.id,reviewId));return{success:true};}),
  approveReview:protectedProcedure.input(entity.extend({reviewId:z.number().int().positive(),reportDocumentId:z.number().int().positive().optional()})).mutation(async({ctx,input})=>{const{db,row}=await reviewForWrite(ctx.user.id,input.entityId,input.reviewId);if(!independentReviewAllowed(ctx.user.id,[row.createdBy,row.completedBy]))throw new TRPCError({code:"FORBIDDEN",message:"A different authorised manager must approve the review"});if(row.status!=="report_draft")throw new TRPCError({code:"BAD_REQUEST",message:"Complete the report before approval"});await db.update(qualityReviews).set({status:"approved",approvedAt:Date.now(),approvedBy:ctx.user.id,reportDocumentId:input.reportDocumentId}).where(eq(qualityReviews.id,row.id));await writeAuditEvent({actorUserId:ctx.user.id,entityId:input.entityId,action:"reg32.approved",resourceType:"quality_review",resourceId:row.id,sensitivity:"restricted",result:"success"});return{success:true};}),
  submitReview:protectedProcedure.input(entity.extend({reviewId:z.number().int().positive(),submissionMethod:z.enum(["email","portal","secure_link","post","other"]),submissionReference:z.string().max(180).optional(),submissionEvidenceDocumentId:z.number().int().positive().optional()})).mutation(async({ctx,input})=>{const{db,row}=await reviewForWrite(ctx.user.id,input.entityId,input.reviewId);if(row.status!=="approved")throw new TRPCError({code:"BAD_REQUEST",message:"Only an approved review can be recorded as submitted"});await db.update(qualityReviews).set({status:"submitted",submittedAt:Date.now(),submittedBy:ctx.user.id,submissionMethod:input.submissionMethod,submissionReference:input.submissionReference,submissionEvidenceDocumentId:input.submissionEvidenceDocumentId}).where(eq(qualityReviews.id,row.id));return{success:true};}),
});
