import {and,desc,eq,inArray} from "drizzle-orm";
import {TRPCError} from "@trpc/server";
import {z} from "zod";
import {localAuthorities,placementNotifications,placements,processingRestrictions,properties,youngPeople} from "../../drizzle/schema";
import {assertPlacementCapability,listAccessiblePropertyIds} from "../authz";
import {protectedProcedure,router} from "../_core/trpc";
import {writeAuditEvent} from "../services/audit";
import {encryptSensitive} from "../services/crypto";
import {requireDb} from "./shared";
import {blocksReg28Sharing,notificationStatusForDecision} from "../services/assuranceRules";
const entity=z.object({entityId:z.number().int().positive()});
async function notificationForWrite(userId:number,entityId:number,id:number){const db=await requireDb();const[row]=await db.select().from(placementNotifications).where(and(eq(placementNotifications.id,id),eq(placementNotifications.entityId,entityId))).limit(1);if(!row)throw new TRPCError({code:"NOT_FOUND"});await assertPlacementCapability(userId,row.placementId,"young_person.write");return{db,row};}
export const regulation28Router=router({
  workspace:protectedProcedure.input(entity).query(async({ctx,input})=>{const propertyIds=await listAccessiblePropertyIds(ctx.user.id,input.entityId,"young_person.read");const db=await requireDb();const placementRows=propertyIds.length?await db.select({id:placements.id,propertyId:placements.propertyId,status:placements.status,reference:youngPeople.reference,propertyName:properties.name,localAuthorityId:placements.localAuthorityId}).from(placements).innerJoin(youngPeople,eq(youngPeople.id,placements.youngPersonId)).leftJoin(properties,eq(properties.id,placements.propertyId)).where(and(eq(placements.entityId,input.entityId),inArray(placements.propertyId,propertyIds))):[];const notifications=propertyIds.length?await db.select().from(placementNotifications).where(and(eq(placementNotifications.entityId,input.entityId),inArray(placementNotifications.propertyId,propertyIds))).orderBy(desc(placementNotifications.dueAt)):[];const authorities=await db.select({id:localAuthorities.id,name:localAuthorities.name,placementEmail:localAuthorities.placementEmail}).from(localAuthorities).where(eq(localAuthorities.entityId,input.entityId));return{placements:placementRows,notifications,authorities};}),
  create:protectedProcedure.input(entity.extend({placementId:z.number().int().positive(),notificationType:z.enum(["admission","discharge"]),eventAt:z.number().int(),dischargeDestinationType:z.enum(["family","independent_living","supported_accommodation","semi_independent","custody","hospital","homeless","unknown","other"]).optional(),dischargeReason:z.enum(["planned_transition","placement_end","safeguarding","placement_breakdown","custody","hospital","young_person_choice","other"]).optional()})).mutation(async({ctx,input})=>{const{placement}=await assertPlacementCapability(ctx.user.id,input.placementId,"young_person.write");if(placement.entityId!==input.entityId||!placement.propertyId)throw new TRPCError({code:"BAD_REQUEST",message:"Placement scope is incomplete"});if(input.notificationType==="discharge"&&(!input.dischargeDestinationType||!input.dischargeReason))throw new TRPCError({code:"BAD_REQUEST",message:"Discharge destination and reason are required"});const db=await requireDb();const[record]=await db.insert(placementNotifications).values({...input,propertyId:placement.propertyId,placingAuthorityId:placement.localAuthorityId,dueAt:input.eventAt+24*60*60*1000,createdBy:ctx.user.id}).$returningId();return record;}),
  recordDecision:protectedProcedure.input(entity.extend({notificationId:z.number().int().positive(),decision:z.enum(["notify_host_authority","same_authority_exempt","not_required"]),decisionReason:z.string().min(10).max(4000),hostAuthorityId:z.number().int().positive().optional(),recipientName:z.string().max(220).optional(),recipientEmail:z.string().email().max(320).optional(),factsSnapshot:z.string().min(20).max(10000),dischargeDetails:z.string().max(8000).optional()})).mutation(async({ctx,input})=>{const{db,row}=await notificationForWrite(ctx.user.id,input.entityId,input.notificationId);await db.update(placementNotifications).set({decision:input.decision,decisionReason:input.decisionReason,hostAuthorityId:input.hostAuthorityId,recipientName:input.recipientName,recipientEmail:input.recipientEmail,factsSnapshotCiphertext:encryptSensitive(input.factsSnapshot),dischargeDetailsCiphertext:input.dischargeDetails?encryptSensitive(input.dischargeDetails):undefined,status:notificationStatusForDecision(input.decision),decisionBy:ctx.user.id,decisionAt:Date.now()}).where(eq(placementNotifications.id,row.id));await writeAuditEvent({actorUserId:ctx.user.id,entityId:input.entityId,propertyId:row.propertyId??undefined,action:`reg28.${row.notificationType}.decision`,resourceType:"placement_notification",resourceId:row.id,sensitivity:"safeguarding",result:"success",metadata:{decision:input.decision}});return{success:true};}),
  submit:protectedProcedure.input(entity.extend({notificationId:z.number().int().positive(),submissionMethod:z.enum(["email","portal","secure_link","post","other"]),submissionReference:z.string().max(180).optional(),submissionEvidenceDocumentId:z.number().int().positive().optional()})).mutation(async({ctx,input})=>{const{db,row}=await notificationForWrite(ctx.user.id,input.entityId,input.notificationId);if(!["decision_recorded","pack_ready"].includes(row.status))throw new TRPCError({code:"BAD_REQUEST",message:"Record the routing decision before submission"});const restrictions=await db.select().from(processingRestrictions).where(and(eq(processingRestrictions.placementId,row.placementId),inArray(processingRestrictions.status,["active","review_due"])));if(blocksReg28Sharing(restrictions))throw new TRPCError({code:"FORBIDDEN",message:"An active processing or sharing restriction blocks submission"});await db.update(placementNotifications).set({status:"submitted",submittedAt:Date.now(),submittedBy:ctx.user.id,submissionMethod:input.submissionMethod,submissionReference:input.submissionReference,submissionEvidenceDocumentId:input.submissionEvidenceDocumentId}).where(eq(placementNotifications.id,row.id));await writeAuditEvent({actorUserId:ctx.user.id,entityId:input.entityId,propertyId:row.propertyId??undefined,action:`reg28.${row.notificationType}.submitted`,resourceType:"placement_notification",resourceId:row.id,sensitivity:"safeguarding",result:"success"});return{success:true};}),
});
