import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

const root = new URL("../../", import.meta.url);
const signInSource = readFileSync(new URL("client/src/components/DashboardLayout.tsx", root), "utf8");
const localAuthSource = readFileSync(new URL("server/routers/localAuth.ts", root), "utf8");

describe("local authentication recovery route", () => {
  it("accepts the canonical resetToken link generated by the local-auth router", () => {
    expect(localAuthSource).toContain('url.searchParams.set("resetToken", token)');
    expect(signInSource).toContain('params.get("resetToken") ?? params.get("reset") ?? ""');
    expect(signInSource).toContain('params.delete("resetToken")');
  });

  it("retains legacy reset compatibility while keeping the password form in reset-confirm mode", () => {
    expect(signInSource).toContain('params.get("reset")');
    expect(signInSource).toContain('resetToken ? "reset-confirm" : "sign-in"');
    expect(signInSource).toContain('resetPassword.mutate({ token: resetToken, password })');
  });
});
