-- The built-in roles keep their navigation in the database from here on, so the admin screen
-- lists and edits real rows instead of a hard-coded table. server/services/roleDefinitions.ts
-- still enforces the code-level ceiling, so these lists can be narrowed but never widened.
UPDATE `roles` SET `visiblePaths` = JSON_ARRAY('/','/properties','/workforce','/access-control','/manager-app','/staff','/placements','/rota','/rota-controls','/compliance-dashboard','/compliance','/governance','/work-plans','/finance','/documents','/assurance','/quality-reviews','/regulation-28','/care','/safeguarding','/keyworker-app','/nominated-individual','/role-management') WHERE `isBuiltIn` = 1 AND `slug` IN ('platform_admin','owner');--> statement-breakpoint
UPDATE `roles` SET `visiblePaths` = JSON_ARRAY('/','/properties','/workforce','/manager-app','/staff','/placements','/rota','/compliance-dashboard','/compliance','/governance','/work-plans','/finance','/documents','/assurance','/quality-reviews','/regulation-28','/care','/safeguarding','/keyworker-app') WHERE `isBuiltIn` = 1 AND `slug` = 'registered_manager';--> statement-breakpoint
UPDATE `roles` SET `visiblePaths` = JSON_ARRAY('/keyworker-app','/properties','/care','/staff') WHERE `isBuiltIn` = 1 AND `slug` = 'support_worker';--> statement-breakpoint
UPDATE `roles` SET `visiblePaths` = JSON_ARRAY('/','/properties','/workforce','/staff','/rota','/compliance-dashboard','/compliance','/governance','/documents','/assurance','/quality-reviews','/regulation-28') WHERE `isBuiltIn` = 1 AND `slug` = 'hr_compliance';--> statement-breakpoint
UPDATE `roles` SET `visiblePaths` = JSON_ARRAY('/','/properties','/compliance-dashboard','/compliance','/finance','/documents') WHERE `isBuiltIn` = 1 AND `slug` = 'finance';--> statement-breakpoint
UPDATE `roles` SET `visiblePaths` = JSON_ARRAY('/','/properties','/workforce','/rota','/compliance-dashboard','/compliance','/documents') WHERE `isBuiltIn` = 1 AND `slug` = 'read_only';
