ALTER TABLE `keyWorkerReports`
  MODIFY COLUMN `status` enum('draft','submitted','reviewed','returned','approved','locked') NOT NULL DEFAULT 'draft',
  ADD COLUMN `reviewNotesCiphertext` text,
  ADD COLUMN `approvedBy` int,
  ADD COLUMN `approvedAt` bigint,
  ADD COLUMN `lockedBy` int,
  ADD COLUMN `lockedAt` bigint,
  ADD COLUMN `version` int NOT NULL DEFAULT 1;
--> statement-breakpoint
ALTER TABLE `keyWorkerReports`
  ADD CONSTRAINT `fk_kw_report_approved_by` FOREIGN KEY (`approvedBy`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action,
  ADD CONSTRAINT `fk_kw_report_locked_by` FOREIGN KEY (`lockedBy`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE `incidents`
  ADD COLUMN `managerReviewState` enum('pending','in_review','returned','approved','closed') NOT NULL DEFAULT 'pending',
  ADD COLUMN `managerReviewNotesCiphertext` text,
  ADD COLUMN `reviewedBy` int,
  ADD COLUMN `reviewedAt` bigint,
  ADD COLUMN `version` int NOT NULL DEFAULT 1;
--> statement-breakpoint
ALTER TABLE `incidents`
  ADD CONSTRAINT `fk_incident_reviewed_by` FOREIGN KEY (`reviewedBy`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE `offlineSyncReceipts`
  MODIFY COLUMN `operation` enum('key_worker_report','incident','clock_event','handover','visitor_entry','curfew_check','missing_episode','medication_administration','property_check','maintenance_job','resident_finance_transaction','lone_worker_check_in') NOT NULL;
--> statement-breakpoint
CREATE TABLE `propertyVisitors` (
  `id` int AUTO_INCREMENT NOT NULL,
  `entityId` int NOT NULL,
  `propertyId` int NOT NULL,
  `placementId` int,
  `visitorType` enum('friend','relative','professional','contractor','public_official','other') NOT NULL,
  `nameCiphertext` text NOT NULL,
  `relationshipCiphertext` text,
  `purposeCiphertext` text NOT NULL,
  `idCheckStatus` enum('not_required','not_checked','verified','declined','unavailable') NOT NULL DEFAULT 'not_checked',
  `identityDocumentId` int,
  `vehicleRegistrationCiphertext` text,
  `arrivedAt` bigint NOT NULL,
  `expectedDepartureAt` bigint,
  `departedAt` bigint,
  `status` enum('on_site','departed','overdue','refused') NOT NULL DEFAULT 'on_site',
  `notesCiphertext` text,
  `version` int NOT NULL DEFAULT 1,
  `createdBy` int NOT NULL,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  `updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `propertyVisitors_id` PRIMARY KEY(`id`),
  CONSTRAINT `fk_visitor_entity` FOREIGN KEY (`entityId`) REFERENCES `entities`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `fk_visitor_property` FOREIGN KEY (`propertyId`) REFERENCES `properties`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `fk_visitor_placement` FOREIGN KEY (`placementId`) REFERENCES `placements`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `fk_visitor_identity_doc` FOREIGN KEY (`identityDocumentId`) REFERENCES `documents`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `fk_visitor_created_by` FOREIGN KEY (`createdBy`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action,
  INDEX `property_visitor_status_idx` (`entityId`,`propertyId`,`status`,`arrivedAt`)
);
--> statement-breakpoint
CREATE TABLE `propertyChecks` (
  `id` int AUTO_INCREMENT NOT NULL,
  `entityId` int NOT NULL,
  `propertyId` int NOT NULL,
  `unitId` int,
  `placementId` int,
  `shiftId` int,
  `checkType` enum('room_check','property_check','fire_check','night_check','health_safety','welfare','other') NOT NULL,
  `authorityBasis` enum('scheduled','consent','risk_assessment','emergency','policy','other') NOT NULL,
  `checklistSnapshot` json NOT NULL,
  `findingsCiphertext` text,
  `privacyNotesCiphertext` text,
  `youngPersonPresent` int NOT NULL DEFAULT 0,
  `result` enum('pass','issues_found','urgent_action') NOT NULL,
  `status` enum('draft','submitted','reviewed','returned','closed') NOT NULL DEFAULT 'draft',
  `completedAt` bigint,
  `reviewedBy` int,
  `reviewedAt` bigint,
  `reviewNotesCiphertext` text,
  `version` int NOT NULL DEFAULT 1,
  `createdBy` int NOT NULL,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  `updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `propertyChecks_id` PRIMARY KEY(`id`),
  CONSTRAINT `fk_property_check_entity` FOREIGN KEY (`entityId`) REFERENCES `entities`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `fk_property_check_property` FOREIGN KEY (`propertyId`) REFERENCES `properties`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `fk_property_check_unit` FOREIGN KEY (`unitId`) REFERENCES `propertyUnits`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `fk_property_check_placement` FOREIGN KEY (`placementId`) REFERENCES `placements`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `fk_property_check_shift` FOREIGN KEY (`shiftId`) REFERENCES `shifts`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `fk_property_check_reviewed` FOREIGN KEY (`reviewedBy`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `fk_property_check_created` FOREIGN KEY (`createdBy`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action,
  INDEX `property_check_status_idx` (`entityId`,`propertyId`,`status`,`createdAt`)
);
--> statement-breakpoint
CREATE TABLE `maintenanceJobs` (
  `id` int AUTO_INCREMENT NOT NULL,
  `entityId` int NOT NULL,
  `propertyId` int NOT NULL,
  `unitId` int,
  `propertyCheckId` int,
  `incidentId` int,
  `title` varchar(220) NOT NULL,
  `category` enum('plumbing','electrical','heating','fire_safety','security','furniture','appliance','fabric','pest','cleaning','other') NOT NULL,
  `priority` enum('routine','urgent','emergency') NOT NULL DEFAULT 'routine',
  `descriptionCiphertext` text NOT NULL,
  `accessNotesCiphertext` text,
  `assignedUserId` int,
  `contractorName` varchar(220),
  `status` enum('reported','triaged','assigned','scheduled','in_progress','completed','verified','cancelled','reopened') NOT NULL DEFAULT 'reported',
  `targetAt` bigint,
  `appointmentStart` bigint,
  `appointmentEnd` bigint,
  `completedAt` bigint,
  `verifiedBy` int,
  `verifiedAt` bigint,
  `version` int NOT NULL DEFAULT 1,
  `createdBy` int NOT NULL,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  `updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `maintenanceJobs_id` PRIMARY KEY(`id`),
  CONSTRAINT `fk_maintenance_entity` FOREIGN KEY (`entityId`) REFERENCES `entities`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `fk_maintenance_property` FOREIGN KEY (`propertyId`) REFERENCES `properties`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `fk_maintenance_unit` FOREIGN KEY (`unitId`) REFERENCES `propertyUnits`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `fk_maintenance_check` FOREIGN KEY (`propertyCheckId`) REFERENCES `propertyChecks`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `fk_maintenance_incident` FOREIGN KEY (`incidentId`) REFERENCES `incidents`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `fk_maintenance_assignee` FOREIGN KEY (`assignedUserId`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `fk_maintenance_verified` FOREIGN KEY (`verifiedBy`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `fk_maintenance_created` FOREIGN KEY (`createdBy`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action,
  INDEX `maintenance_job_queue_idx` (`entityId`,`propertyId`,`status`,`priority`)
);
--> statement-breakpoint
CREATE TABLE `maintenanceUpdates` (
  `id` int AUTO_INCREMENT NOT NULL,
  `entityId` int NOT NULL,
  `maintenanceJobId` int NOT NULL,
  `updateType` enum('note','status_change','appointment','contractor_visit','evidence','completion','reopen') NOT NULL,
  `statusFrom` varchar(40),
  `statusTo` varchar(40),
  `noteCiphertext` text,
  `documentId` int,
  `occurredAt` bigint NOT NULL,
  `createdBy` int NOT NULL,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  CONSTRAINT `maintenanceUpdates_id` PRIMARY KEY(`id`),
  CONSTRAINT `fk_maintenance_update_entity` FOREIGN KEY (`entityId`) REFERENCES `entities`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `fk_maintenance_update_job` FOREIGN KEY (`maintenanceJobId`) REFERENCES `maintenanceJobs`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `fk_maintenance_update_doc` FOREIGN KEY (`documentId`) REFERENCES `documents`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `fk_maintenance_update_user` FOREIGN KEY (`createdBy`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action,
  INDEX `maintenance_update_job_idx` (`maintenanceJobId`,`occurredAt`)
);
--> statement-breakpoint
CREATE TABLE `loneWorkerSessions` (
  `id` int AUTO_INCREMENT NOT NULL,
  `entityId` int NOT NULL,
  `propertyId` int NOT NULL,
  `shiftId` int NOT NULL,
  `userId` int NOT NULL,
  `startsAt` bigint NOT NULL,
  `expectedEndAt` bigint NOT NULL,
  `checkInIntervalMinutes` int NOT NULL DEFAULT 60,
  `escalationAfterMinutes` int NOT NULL DEFAULT 15,
  `nextCheckInDueAt` bigint NOT NULL,
  `lastCheckInAt` bigint,
  `status` enum('active','overdue','escalated','completed','cancelled') NOT NULL DEFAULT 'active',
  `escalatedAt` bigint,
  `escalationNoteCiphertext` text,
  `completedAt` bigint,
  `version` int NOT NULL DEFAULT 1,
  `createdBy` int NOT NULL,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  `updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `loneWorkerSessions_id` PRIMARY KEY(`id`),
  CONSTRAINT `lone_worker_shift_user_uq` UNIQUE(`shiftId`,`userId`),
  CONSTRAINT `fk_lone_entity` FOREIGN KEY (`entityId`) REFERENCES `entities`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `fk_lone_property` FOREIGN KEY (`propertyId`) REFERENCES `properties`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `fk_lone_shift` FOREIGN KEY (`shiftId`) REFERENCES `shifts`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `fk_lone_user` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `fk_lone_created` FOREIGN KEY (`createdBy`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action,
  INDEX `lone_worker_due_idx` (`entityId`,`status`,`nextCheckInDueAt`)
);
--> statement-breakpoint
CREATE TABLE `loneWorkerCheckIns` (
  `id` int AUTO_INCREMENT NOT NULL,
  `entityId` int NOT NULL,
  `sessionId` int NOT NULL,
  `checkInType` enum('scheduled','manual','help_requested','session_end') NOT NULL,
  `wellbeingStatus` enum('safe','concern','help_required') NOT NULL DEFAULT 'safe',
  `occurredAt` bigint NOT NULL,
  `latitude` decimal(10,7),
  `longitude` decimal(10,7),
  `accuracyMetres` decimal(10,2),
  `locationState` enum('on_site','off_site','unavailable','manual') NOT NULL,
  `noteCiphertext` text,
  `createdBy` int NOT NULL,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  CONSTRAINT `loneWorkerCheckIns_id` PRIMARY KEY(`id`),
  CONSTRAINT `fk_lone_checkin_entity` FOREIGN KEY (`entityId`) REFERENCES `entities`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `fk_lone_checkin_session` FOREIGN KEY (`sessionId`) REFERENCES `loneWorkerSessions`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `fk_lone_checkin_created` FOREIGN KEY (`createdBy`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action,
  INDEX `lone_worker_checkin_idx` (`sessionId`,`occurredAt`)
);
--> statement-breakpoint
CREATE TABLE `residentFinanceAccounts` (
  `id` int AUTO_INCREMENT NOT NULL,
  `entityId` int NOT NULL,
  `placementId` int NOT NULL,
  `accountType` enum('cash_allowance','savings','personal_budget','petty_cash','other') NOT NULL,
  `name` varchar(180) NOT NULL,
  `currency` varchar(3) NOT NULL DEFAULT 'GBP',
  `balance` decimal(12,2) NOT NULL DEFAULT '0.00',
  `status` enum('active','frozen','closed') NOT NULL DEFAULT 'active',
  `version` int NOT NULL DEFAULT 1,
  `createdBy` int NOT NULL,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  `updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `residentFinanceAccounts_id` PRIMARY KEY(`id`),
  CONSTRAINT `fk_resident_account_entity` FOREIGN KEY (`entityId`) REFERENCES `entities`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `fk_resident_account_placement` FOREIGN KEY (`placementId`) REFERENCES `placements`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `fk_resident_account_created` FOREIGN KEY (`createdBy`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action,
  INDEX `resident_finance_account_idx` (`entityId`,`placementId`,`status`)
);
--> statement-breakpoint
CREATE TABLE `residentFinanceTransactions` (
  `id` int AUTO_INCREMENT NOT NULL,
  `entityId` int NOT NULL,
  `placementId` int NOT NULL,
  `accountId` int NOT NULL,
  `transactionType` enum('deposit','withdrawal','purchase','refund','adjustment','reversal') NOT NULL,
  `amount` decimal(12,2) NOT NULL,
  `balanceAfter` decimal(12,2) NOT NULL,
  `purposeCiphertext` text NOT NULL,
  `counterpartyCiphertext` text,
  `receiptDocumentId` int,
  `occurredAt` bigint NOT NULL,
  `status` enum('draft','submitted','approved','returned','reversed') NOT NULL DEFAULT 'submitted',
  `reviewNotesCiphertext` text,
  `approvedBy` int,
  `approvedAt` bigint,
  `reversedBy` int,
  `reversedAt` bigint,
  `reversalReasonCiphertext` text,
  `createdBy` int NOT NULL,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  CONSTRAINT `residentFinanceTransactions_id` PRIMARY KEY(`id`),
  CONSTRAINT `fk_resident_tx_entity` FOREIGN KEY (`entityId`) REFERENCES `entities`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `fk_resident_tx_placement` FOREIGN KEY (`placementId`) REFERENCES `placements`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `fk_resident_tx_account` FOREIGN KEY (`accountId`) REFERENCES `residentFinanceAccounts`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `fk_resident_tx_receipt` FOREIGN KEY (`receiptDocumentId`) REFERENCES `documents`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `fk_resident_tx_approved` FOREIGN KEY (`approvedBy`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `fk_resident_tx_reversed` FOREIGN KEY (`reversedBy`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `fk_resident_tx_created` FOREIGN KEY (`createdBy`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action,
  INDEX `resident_finance_transaction_idx` (`accountId`,`occurredAt`,`status`)
);
--> statement-breakpoint
CREATE TABLE `residentValuables` (
  `id` int AUTO_INCREMENT NOT NULL,
  `entityId` int NOT NULL,
  `placementId` int NOT NULL,
  `reference` varchar(80) NOT NULL,
  `descriptionCiphertext` text NOT NULL,
  `quantity` int NOT NULL DEFAULT 1,
  `receivedAt` bigint NOT NULL,
  `releasedAt` bigint,
  `status` enum('held','released','missing','disposed') NOT NULL DEFAULT 'held',
  `witnessUserId` int,
  `documentId` int,
  `createdBy` int NOT NULL,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  `updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `residentValuables_id` PRIMARY KEY(`id`),
  CONSTRAINT `resident_valuable_reference_uq` UNIQUE(`entityId`,`reference`),
  CONSTRAINT `fk_valuable_entity` FOREIGN KEY (`entityId`) REFERENCES `entities`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `fk_valuable_placement` FOREIGN KEY (`placementId`) REFERENCES `placements`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `fk_valuable_witness` FOREIGN KEY (`witnessUserId`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `fk_valuable_document` FOREIGN KEY (`documentId`) REFERENCES `documents`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `fk_valuable_created` FOREIGN KEY (`createdBy`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action,
  INDEX `resident_valuable_placement_idx` (`placementId`,`status`)
);
--> statement-breakpoint
CREATE TABLE `staffRequests` (
  `id` int AUTO_INCREMENT NOT NULL,
  `entityId` int NOT NULL,
  `staffProfileId` int NOT NULL,
  `userId` int NOT NULL,
  `requestType` enum('contact_change','certificate_submission','sickness','holiday','availability_change') NOT NULL,
  `startsAt` bigint,
  `endsAt` bigint,
  `detailsCiphertext` text NOT NULL,
  `proposedChanges` json,
  `evidenceDocumentId` int,
  `status` enum('draft','submitted','approved','declined','returned','withdrawn') NOT NULL DEFAULT 'submitted',
  `reviewNotesCiphertext` text,
  `reviewedBy` int,
  `reviewedAt` bigint,
  `version` int NOT NULL DEFAULT 1,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  `updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `staffRequests_id` PRIMARY KEY(`id`),
  CONSTRAINT `fk_staff_request_entity` FOREIGN KEY (`entityId`) REFERENCES `entities`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `fk_staff_request_profile` FOREIGN KEY (`staffProfileId`) REFERENCES `staffProfiles`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `fk_staff_request_user` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `fk_staff_request_evidence` FOREIGN KEY (`evidenceDocumentId`) REFERENCES `documents`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `fk_staff_request_reviewed` FOREIGN KEY (`reviewedBy`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action,
  INDEX `staff_request_queue_idx` (`entityId`,`status`,`requestType`,`createdAt`),
  INDEX `staff_request_user_idx` (`userId`,`status`,`createdAt`)
);
--> statement-breakpoint
CREATE TABLE `supervisionSessions` (
  `id` int AUTO_INCREMENT NOT NULL,
  `entityId` int NOT NULL,
  `staffProfileId` int NOT NULL,
  `managerUserId` int NOT NULL,
  `templateId` int,
  `scheduledAt` bigint NOT NULL,
  `completedAt` bigint,
  `location` varchar(220),
  `sharedNotesCiphertext` text,
  `managerNotesCiphertext` text,
  `actions` json,
  `acknowledgementRequired` int NOT NULL DEFAULT 1,
  `acknowledgedBy` int,
  `acknowledgedAt` bigint,
  `status` enum('scheduled','draft','submitted','acknowledged','completed','cancelled') NOT NULL DEFAULT 'scheduled',
  `version` int NOT NULL DEFAULT 1,
  `createdBy` int NOT NULL,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  `updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `supervisionSessions_id` PRIMARY KEY(`id`),
  CONSTRAINT `fk_supervision_entity` FOREIGN KEY (`entityId`) REFERENCES `entities`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `fk_supervision_profile` FOREIGN KEY (`staffProfileId`) REFERENCES `staffProfiles`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `fk_supervision_manager` FOREIGN KEY (`managerUserId`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `fk_supervision_template` FOREIGN KEY (`templateId`) REFERENCES `documentTemplates`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `fk_supervision_acknowledged` FOREIGN KEY (`acknowledgedBy`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `fk_supervision_created` FOREIGN KEY (`createdBy`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action,
  INDEX `supervision_due_idx` (`entityId`,`staffProfileId`,`status`,`scheduledAt`)
);
--> statement-breakpoint
CREATE TABLE `medicationStockTransactions` (
  `id` int AUTO_INCREMENT NOT NULL,
  `entityId` int NOT NULL,
  `placementId` int NOT NULL,
  `medicationId` int NOT NULL,
  `administrationId` int,
  `transactionType` enum('receipt','administration','return','disposal','correction','count') NOT NULL,
  `quantity` decimal(10,3) NOT NULL,
  `balanceAfter` decimal(10,3) NOT NULL,
  `unit` varchar(60) NOT NULL,
  `batchReference` varchar(120),
  `expiresAt` bigint,
  `occurredAt` bigint NOT NULL,
  `reasonCiphertext` text,
  `witnessUserId` int,
  `documentId` int,
  `status` enum('recorded','review_required','approved') NOT NULL DEFAULT 'recorded',
  `reviewedBy` int,
  `reviewedAt` bigint,
  `createdBy` int NOT NULL,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  CONSTRAINT `medicationStockTransactions_id` PRIMARY KEY(`id`),
  CONSTRAINT `fk_med_stock_entity` FOREIGN KEY (`entityId`) REFERENCES `entities`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `fk_med_stock_placement` FOREIGN KEY (`placementId`) REFERENCES `placements`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `fk_med_stock_medication` FOREIGN KEY (`medicationId`) REFERENCES `medications`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `fk_med_stock_administration` FOREIGN KEY (`administrationId`) REFERENCES `medicationAdministrations`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `fk_med_stock_witness` FOREIGN KEY (`witnessUserId`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `fk_med_stock_document` FOREIGN KEY (`documentId`) REFERENCES `documents`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `fk_med_stock_reviewed` FOREIGN KEY (`reviewedBy`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `fk_med_stock_created` FOREIGN KEY (`createdBy`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action,
  INDEX `medication_stock_idx` (`medicationId`,`occurredAt`,`status`)
);
--> statement-breakpoint
CREATE TABLE `incidentPeople` (
  `id` int AUTO_INCREMENT NOT NULL,
  `entityId` int NOT NULL,
  `incidentId` int NOT NULL,
  `personType` enum('young_person','staff','professional','visitor','public','other') NOT NULL,
  `placementId` int,
  `userId` int,
  `nameCiphertext` text,
  `contactCiphertext` text,
  `roleDescription` varchar(180),
  `involvement` enum('affected','witness','reporter','person_of_concern','responding_professional','other') NOT NULL,
  `createdBy` int NOT NULL,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  CONSTRAINT `incidentPeople_id` PRIMARY KEY(`id`),
  CONSTRAINT `fk_incident_people_entity` FOREIGN KEY (`entityId`) REFERENCES `entities`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `fk_incident_people_incident` FOREIGN KEY (`incidentId`) REFERENCES `incidents`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `fk_incident_people_placement` FOREIGN KEY (`placementId`) REFERENCES `placements`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `fk_incident_people_user` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `fk_incident_people_created` FOREIGN KEY (`createdBy`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action,
  INDEX `incident_people_idx` (`incidentId`,`involvement`)
);
--> statement-breakpoint
CREATE TABLE `incidentReferences` (
  `id` int AUTO_INCREMENT NOT NULL,
  `entityId` int NOT NULL,
  `incidentId` int NOT NULL,
  `referenceType` enum('police','nhs','local_authority','ofsted','lado','insurance','other') NOT NULL,
  `referenceValueCiphertext` text NOT NULL,
  `organisation` varchar(220),
  `notesCiphertext` text,
  `createdBy` int NOT NULL,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  CONSTRAINT `incidentReferences_id` PRIMARY KEY(`id`),
  CONSTRAINT `fk_incident_ref_entity` FOREIGN KEY (`entityId`) REFERENCES `entities`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `fk_incident_ref_incident` FOREIGN KEY (`incidentId`) REFERENCES `incidents`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `fk_incident_ref_created` FOREIGN KEY (`createdBy`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action,
  INDEX `incident_reference_idx` (`incidentId`,`referenceType`)
);
--> statement-breakpoint
CREATE TABLE `recordDocumentLinks` (
  `id` int AUTO_INCREMENT NOT NULL,
  `entityId` int NOT NULL,
  `documentId` int NOT NULL,
  `resourceType` varchar(80) NOT NULL,
  `resourceId` varchar(80) NOT NULL,
  `linkType` enum('evidence','photo','id_document','receipt','certificate','statement','completion','other') NOT NULL,
  `createdBy` int NOT NULL,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  CONSTRAINT `recordDocumentLinks_id` PRIMARY KEY(`id`),
  CONSTRAINT `record_document_link_uq` UNIQUE(`documentId`,`resourceType`,`resourceId`,`linkType`),
  CONSTRAINT `fk_record_doc_entity` FOREIGN KEY (`entityId`) REFERENCES `entities`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `fk_record_doc_document` FOREIGN KEY (`documentId`) REFERENCES `documents`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `fk_record_doc_created` FOREIGN KEY (`createdBy`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action,
  INDEX `record_document_resource_idx` (`resourceType`,`resourceId`)
);
--> statement-breakpoint
CREATE TABLE `keyWorkerReportReviews` (
  `id` int AUTO_INCREMENT NOT NULL,
  `entityId` int NOT NULL,
  `reportId` int NOT NULL,
  `decision` enum('returned','reviewed','approved','locked','addendum_requested') NOT NULL,
  `notesCiphertext` text,
  `createdBy` int NOT NULL,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  CONSTRAINT `keyWorkerReportReviews_id` PRIMARY KEY(`id`),
  CONSTRAINT `fk_kw_review_entity` FOREIGN KEY (`entityId`) REFERENCES `entities`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `fk_kw_review_report` FOREIGN KEY (`reportId`) REFERENCES `keyWorkerReports`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `fk_kw_review_created` FOREIGN KEY (`createdBy`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action,
  INDEX `key_worker_report_review_idx` (`reportId`,`createdAt`)
);
--> statement-breakpoint
CREATE TABLE `incidentReviews` (
  `id` int AUTO_INCREMENT NOT NULL,
  `entityId` int NOT NULL,
  `incidentId` int NOT NULL,
  `decision` enum('started','returned','approved','follow_up','closed') NOT NULL,
  `notesCiphertext` text,
  `notificationAssessment` enum('unchanged','not_notifiable','regulation_27','other_notification') NOT NULL DEFAULT 'unchanged',
  `createdBy` int NOT NULL,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  CONSTRAINT `incidentReviews_id` PRIMARY KEY(`id`),
  CONSTRAINT `fk_incident_review_entity` FOREIGN KEY (`entityId`) REFERENCES `entities`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `fk_incident_review_incident` FOREIGN KEY (`incidentId`) REFERENCES `incidents`(`id`) ON DELETE no action ON UPDATE no action,
  CONSTRAINT `fk_incident_review_created` FOREIGN KEY (`createdBy`) REFERENCES `users`(`id`) ON DELETE no action ON UPDATE no action,
  INDEX `incident_review_idx` (`incidentId`,`createdAt`)
);
