import { trpc } from "@/lib/trpc";
import { createOfflineEnvelope,deleteOfflineItem,listOfflineItems,OfflineItem,OfflineOperation,patchOfflineItem,saveOfflineItem } from "@/lib/offlineKeyWorker";
import { useCallback,useEffect,useRef,useState } from "react";
import { toast } from "sonner";

type SyncResult={idempotencyKey:string;status:string;code?:string;message?:string;resourceId?:number};
export function useOfflineKeyWorkerQueue(ownerKey:string|undefined,entityId:number|undefined){
  const [items,setItems]=useState<OfflineItem[]>([]);const [online,setOnline]=useState(()=>typeof navigator==="undefined"?true:navigator.onLine);const syncMutation=trpc.offlineSync.syncBatch.useMutation();const itemsRef=useRef(items);const initialSyncAttempted=useRef(false);itemsRef.current=items;
  const refresh=useCallback(async()=>{if(!ownerKey||!entityId){setItems([]);return;}setItems(await listOfflineItems(ownerKey,entityId));},[ownerKey,entityId]);
  useEffect(()=>{void refresh();},[refresh]);
  const applyResults=useCallback(async(results:SyncResult[])=>{for(const result of results){if(result.status==="applied"||result.status==="already_applied")await deleteOfflineItem(result.idempotencyKey);else await patchOfflineItem(result.idempotencyKey,{status:result.status==="rejected"?"rejected":"conflict",code:result.code,message:result.message});}await refresh();},[refresh]);
  const syncItems=useCallback(async(targets?:OfflineItem[])=>{if(!ownerKey||!entityId||!navigator.onLine)return;const queued=(targets??itemsRef.current).filter(item=>item.status==="queued"||item.status==="syncing").slice(0,20);if(!queued.length)return;for(const item of queued)await patchOfflineItem(item.id,{status:"syncing",code:undefined,message:undefined});await refresh();try{const response=await syncMutation.mutateAsync({entityId,items:queued.map(item=>item.envelope) as any});await applyResults(response.results);const applied=response.results.filter(result=>result.status==="applied"||result.status==="already_applied").length;const conflicts=response.results.length-applied;if(applied)toast.success(`${applied} secure offline ${applied===1?"record":"records"} synchronised.`);if(conflicts)toast.warning(`${conflicts} offline ${conflicts===1?"record needs":"records need"} review before re-queuing.`);}catch(error){for(const item of queued)await patchOfflineItem(item.id,{status:"queued",message:error instanceof Error?error.message:"Synchronisation failed"});await refresh();toast.error("Offline records remain encrypted on this device. Synchronisation will retry when connectivity returns.");}},[applyResults,entityId,ownerKey,refresh,syncMutation]);
  useEffect(()=>{const onlineHandler=()=>{setOnline(true);void syncItems();};const offlineHandler=()=>setOnline(false);window.addEventListener("online",onlineHandler);window.addEventListener("offline",offlineHandler);return()=>{window.removeEventListener("online",onlineHandler);window.removeEventListener("offline",offlineHandler);};},[syncItems]);
  useEffect(()=>{if(initialSyncAttempted.current||!online||!items.some(item=>item.status==="queued"))return;initialSyncAttempted.current=true;void syncItems(items);},[items,online,syncItems]);
  const saveDraft=useCallback(async(operation:OfflineOperation,payload:Record<string,unknown>,basePlacementUpdatedAt:number)=>{if(!ownerKey||!entityId)throw new Error("Authenticated device ownership is required");for(const item of itemsRef.current.filter(candidate=>candidate.status==="device_draft"&&candidate.operation===operation&&candidate.envelope.payload.placementId===payload.placementId))await deleteOfflineItem(item.id);const envelope=createOfflineEnvelope(operation,payload,basePlacementUpdatedAt);await saveOfflineItem(ownerKey,entityId,envelope,"device_draft");await refresh();toast.success("Encrypted device draft saved for up to 48 hours.");return envelope.idempotencyKey;},[entityId,ownerKey,refresh]);
  const queueSubmission=useCallback(async(operation:OfflineOperation,payload:Record<string,unknown>,basePlacementUpdatedAt:number)=>{if(!ownerKey||!entityId)throw new Error("Authenticated device ownership is required");const envelope=createOfflineEnvelope(operation,payload,basePlacementUpdatedAt);await saveOfflineItem(ownerKey,entityId,envelope,"queued");const target:OfflineItem={id:envelope.idempotencyKey,operation,status:"queued",updatedAt:Date.now(),expiresAt:envelope.expiresAt,envelope};await refresh();if(navigator.onLine)await syncItems([target]);else toast.info("Submission queued securely on this device and will synchronise when connectivity returns.");return envelope.idempotencyKey;},[entityId,ownerKey,refresh,syncItems]);
  const discard=useCallback(async(id:string)=>{await deleteOfflineItem(id);await refresh();},[refresh]);
  const requeue=useCallback(async(item:OfflineItem,newBasePlacementUpdatedAt:number)=>{if(!ownerKey||!entityId)throw new Error("Authenticated device ownership is required");const envelope=createOfflineEnvelope(item.operation,item.envelope.payload,newBasePlacementUpdatedAt);await saveOfflineItem(ownerKey,entityId,envelope,"queued");await deleteOfflineItem(item.id);await refresh();if(navigator.onLine)await syncItems([{...item,id:envelope.idempotencyKey,status:"queued",updatedAt:Date.now(),expiresAt:envelope.expiresAt,envelope}]);},[entityId,ownerKey,refresh,syncItems]);
  return{items,online,isSyncing:syncMutation.isPending,saveDraft,queueSubmission,syncNow:()=>syncItems(),discard,requeue,refresh};
}
