import { EmptyState, PageHeader, StatusBadge } from "@/components/app/Primitives";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { DictationTextarea } from "@/components/DictationFields";
import { EvidenceFilePicker, fileToBase64, normaliseEvidenceMimeType } from "@/components/EvidenceFilePicker";
import { useWorkspace } from "@/contexts/WorkspaceContext";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { DocumentRegisterExportDialog } from "@/components/PrintableRecordExports";
import { Archive, CheckCheck, Copy, Download, FileCheck2, FilePlus2, FileStack, FolderPlus, Loader2, PackagePlus, Plus, ShieldCheck, Upload } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

type DocumentRecord = { id: number; entityId: number; propertyId: number | null; folderId: number | null; title: string; documentType: string; classification: string; status: string; currentVersion: number; reviewDueAt: number | null; retentionUntil: number | null; retentionBasis: string | null; legalHold: number };

export default function DocumentsPage() {
  const { entityId } = useWorkspace();
  const { user } = useAuth();
  const [selected, setSelected] = useState<DocumentRecord | null>(null);
  const docs = trpc.documents.list.useQuery({ entityId: entityId! }, { enabled: Boolean(entityId), retry: false });
  const packs = trpc.documents.packs.useQuery({ entityId: entityId! }, { enabled: Boolean(entityId), retry: false });
  const folders = trpc.governance.folders.useQuery({ entityId: entityId! }, { enabled: Boolean(entityId), retry: false });
  const templates = trpc.governance.templates.useQuery({ entityId: entityId! }, { enabled: Boolean(entityId), retry: false });
  const acknowledgements = trpc.governance.myAcknowledgements.useQuery({ entityId: entityId! }, { enabled: Boolean(entityId), retry: false });
  const retention = trpc.governance.retentionReviews.useQuery({ entityId: entityId! }, { enabled: Boolean(entityId), retry: false });
  const exports = trpc.governance.exports.useQuery({ entityId: entityId! }, { enabled: Boolean(entityId), retry: false });
  const properties = trpc.entities.properties.useQuery({ entityId: entityId! }, { enabled: Boolean(entityId), retry: false });
  if (!entityId) return <EmptyState title="Create an entity first" description="Documents and packs must carry the correct legal and access scope." icon={FileStack} />;
  if (docs.error || packs.error) return <EmptyState title="Document access is restricted" description={(docs.error || packs.error)?.message ?? "Access denied"} icon={ShieldCheck} />;
  const folderName = (id: number | null) => folders.data?.find(folder => folder.id === id)?.name ?? "Unfiled";
  const canExportRegister = ["owner", "registered_manager", "hr_compliance"].includes(user?.operationalRole ?? "");
  return <div className="mx-auto max-w-[1480px] pb-20"><PageHeader eyebrow="Controlled content" title="Documents & evidence" description="Classified files, version history, policy acknowledgements, retention decisions and generated evidence exports remain connected to the records they support." action={canExportRegister ? <DocumentRegisterExportDialog entityId={entityId} properties={properties.data ?? []} /> : undefined} />
    <Tabs defaultValue="documents"><TabsList className="mb-5 grid h-auto w-full grid-cols-2 gap-1 rounded-xl bg-muted p-1 sm:inline-flex sm:w-auto"><TabsTrigger value="documents" className="rounded-lg">Library</TabsTrigger><TabsTrigger value="policies" className="rounded-lg">Policies</TabsTrigger><TabsTrigger value="packs" className="rounded-lg">Authority packs</TabsTrigger><TabsTrigger value="governance" className="rounded-lg">Governance</TabsTrigger></TabsList>
      <TabsContent value="documents"><div className="mb-4 flex flex-wrap justify-end gap-2"><CreateFolderDialog entityId={entityId} /><CreateDocumentDialog entityId={entityId} folders={folders.data ?? []} /></div>{docs.data?.length ? <div className="surface divide-y divide-border/60">{docs.data.map(document => <button key={document.id} onClick={() => setSelected(document as DocumentRecord)} className="operational-row operational-row-action"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-secondary"><FileStack className="h-4 w-4" /></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-extrabold">{document.title}</p><p className="mt-0.5 truncate text-xs capitalize text-muted-foreground">{folderName(document.folderId)} · {document.documentType} · {document.classification} · v{document.currentVersion}</p>{document.retentionUntil && <p className="mt-0.5 truncate text-[0.68rem] text-muted-foreground">Retention review by {new Date(document.retentionUntil).toLocaleDateString("en-GB")}{document.legalHold ? " · legal hold" : ""}</p>}</div><StatusBadge status={document.status} /></button>)}</div> : <EmptyState title="No controlled documents" description="Create a classified record, then upload the first immutable file version." actionLabel="Create document record" onAction={() => document.getElementById("create-document-trigger")?.click()} icon={FilePlus2} />}</TabsContent>
      <TabsContent value="policies"><PolicyAcknowledgements entityId={entityId} rows={acknowledgements.data ?? []} /></TabsContent>
      <TabsContent value="packs"><div className="mb-4 flex justify-end"><CreatePackDialog entityId={entityId} /></div>{packs.data?.length ? <div className="grid gap-4 md:grid-cols-2">{packs.data.map(pack => <PackCard key={pack.id} entityId={entityId} pack={pack} />)}</div> : <EmptyState title="No provider packs" description="Generate a dated provider snapshot, then share it using an expiring, view-limited link." actionLabel="Prepare provider pack" onAction={() => document.getElementById("create-pack-trigger")?.click()} icon={PackagePlus} />}</TabsContent>
      <TabsContent value="governance"><div className="grid gap-6 xl:grid-cols-3"><TemplatesPanel entityId={entityId} rows={templates.data ?? []} /><RetentionPanel entityId={entityId} rows={retention.data ?? []} documents={(docs.data ?? []) as DocumentRecord[]} /><ExportsPanel entityId={entityId} rows={exports.data ?? []} /></div></TabsContent>
    </Tabs>
    {selected && <DocumentManager entityId={entityId} document={selected} onClose={() => setSelected(null)} />}
  </div>;
}

function CreateDocumentDialog({ entityId, folders }: { entityId: number; folders: Array<{ id: number; name: string }> }) {
  const [open, setOpen] = useState(false); const [title, setTitle] = useState(""); const [type, setType] = useState("policy"); const [classification, setClassification] = useState("general"); const [folderId, setFolderId] = useState("unfiled"); const [reviewDate, setReviewDate] = useState(""); const [retentionDate, setRetentionDate] = useState(""); const [retentionBasis, setRetentionBasis] = useState(""); const [legalHold, setLegalHold] = useState("no"); const utils = trpc.useUtils();
  const create = trpc.documents.createMetadata.useMutation({ onSuccess: async () => { await utils.documents.list.invalidate(); setOpen(false); toast.success("Document record created", { description: "Open it to upload the first controlled version." }); }, onError: error => toast.error(error.message) });
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button id="create-document-trigger" className="rounded-xl"><Plus className="mr-2 h-4 w-4" />New document</Button></DialogTrigger><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>Create controlled document</DialogTitle><DialogDescription>Choose the minimum classification, folder and retention basis that protect the content.</DialogDescription></DialogHeader><div className="grid gap-4 py-3 sm:grid-cols-2"><Field label="Title" value={title} onChange={setTitle} /><SelectField label="Type" value={type} onChange={setType} options={["policy", "template", "certificate", "contract", "plan", "evidence", "generated", "other"]} /><SelectField label="Classification" value={classification} onChange={setClassification} options={["general", "hr", "finance", "safeguarding", "bank", "restricted"]} /><ScopeSelect label="Folder" value={folderId} onChange={setFolderId} allLabel="Unfiled" allValue="unfiled" options={folders.map(folder => ({ value: String(folder.id), label: folder.name }))} /><Field label="Review due" value={reviewDate} onChange={setReviewDate} type="date" /><Field label="Retain until" value={retentionDate} onChange={setRetentionDate} type="date" /><Field label="Retention basis" value={retentionBasis} onChange={setRetentionBasis} /><SelectField label="Legal hold" value={legalHold} onChange={setLegalHold} options={["no", "yes"]} /></div><DialogFooter><Button variant="outline" onClick={() => setOpen(false)}>Cancel</Button><Button onClick={() => create.mutate({ entityId, folderId: folderId === "unfiled" ? undefined : Number(folderId), title, documentType: type as any, classification: classification as any, reviewDueAt: dateValue(reviewDate), retentionUntil: dateValue(retentionDate), retentionBasis: retentionBasis || undefined, legalHold: legalHold === "yes" })} disabled={!title || create.isPending}>{create.isPending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}Create record</Button></DialogFooter></DialogContent></Dialog>;
}

function CreateFolderDialog({ entityId }: { entityId: number }) { const [open, setOpen] = useState(false); const [name, setName] = useState(""); const [classification, setClassification] = useState("general"); const utils = trpc.useUtils(); const create = trpc.governance.createFolder.useMutation({ onSuccess: async () => { await utils.governance.folders.invalidate(); setOpen(false); setName(""); toast.success("Folder added"); }, onError: error => toast.error(error.message) }); return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button variant="outline"><FolderPlus className="mr-2 h-4 w-4" />New folder</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Create classified folder</DialogTitle><DialogDescription>Folder classification is guidance; every document continues to enforce its own classification.</DialogDescription></DialogHeader><div className="grid gap-4 py-3"><Field label="Folder name" value={name} onChange={setName} /><SelectField label="Classification" value={classification} onChange={setClassification} options={["general", "hr", "finance", "safeguarding", "bank", "restricted"]} /></div><DialogFooter><Button variant="outline" onClick={() => setOpen(false)}>Cancel</Button><Button onClick={() => create.mutate({ entityId, name, classification: classification as any })} disabled={!name || create.isPending}>Create folder</Button></DialogFooter></DialogContent></Dialog>; }

function DocumentManager({ entityId, document, onClose }: { entityId: number; document: DocumentRecord; onClose: () => void }) {
  const versions = trpc.governance.versions.useQuery({ documentId: document.id }); const utils = trpc.useUtils(); const [files, setFiles] = useState<File[]>([]); const [summary, setSummary] = useState(""); const [ackDue, setAckDue] = useState("");
  const upload = trpc.governance.uploadVersion.useMutation();
  const download = trpc.governance.downloadVersion.useMutation({ onSuccess: result => window.open(result.url, "_blank", "noopener,noreferrer"), onError: error => toast.error(error.message) });
  const approve = trpc.governance.approveDocument.useMutation({ onSuccess: async () => { await Promise.all([utils.documents.list.invalidate(), utils.governance.myAcknowledgements.invalidate()]); toast.success("Document approved", { description: document.documentType === "policy" ? "Acknowledgements were assigned to active entity members." : "The approved version is now controlled." }); }, onError: error => toast.error(error.message) });
  const submitUpload = async () => { if (!files.length) return; try { for (const file of files) await upload.mutateAsync({ documentId: document.id, fileName: file.name, mimeType: normaliseEvidenceMimeType(file), base64: await fileToBase64(file), changeSummary: summary || undefined }); await Promise.all([utils.governance.versions.invalidate(), utils.documents.list.invalidate()]); const uploaded = files.length; setFiles([]); setSummary(""); toast.success(`${uploaded} controlled file${uploaded === 1 ? " was" : "s were"} uploaded`, { description: "Review every page and version before approval. Automated malware scanning status remains visible." }); } catch (error) { toast.error("File upload could not be completed", { description: error instanceof Error ? error.message : "Review the selected files and try again." }); } };
  return <Dialog open onOpenChange={open => !open && onClose()}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>{document.title}</DialogTitle><DialogDescription>{document.classification} classification · version {document.currentVersion} · {document.retentionBasis || "retention basis not yet recorded"}</DialogDescription></DialogHeader><div className="space-y-6 py-3"><section className="rounded-2xl bg-muted p-4"><p className="eyebrow">Upload immutable file pages</p><div className="mt-3 grid gap-3"><EvidenceFilePicker files={files} onChange={setFiles} disabled={upload.isPending} label="Scanned document pages or photos" description="Add multiple scans or photos in order. Each file becomes a separately hashed controlled version." /><Input value={summary} onChange={event => setSummary(event.target.value)} placeholder="Change summary for these files" /><Button className="justify-self-end" onClick={() => void submitUpload()} disabled={!files.length || upload.isPending}><Upload className="mr-2 h-4 w-4" />{upload.isPending ? "Uploading…" : "Upload selected files"}</Button></div><p className="mt-2 text-xs text-muted-foreground">Maximum 8 MB per file. Uploaded evidence records a SHA-256 hash. Automated malware scanning is marked unavailable until an approved scanner is connected.</p></section><section><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="eyebrow">Version history</p><h3 className="mt-1 font-extrabold">Stored files</h3></div>{document.documentType === "policy" && <Field label="Acknowledgement due" value={ackDue} onChange={setAckDue} type="date" />}</div>{versions.data?.length ? <div className="mt-3 space-y-2">{versions.data.map(version => <div key={version.id} className="flex items-center gap-3 rounded-xl border border-border/70 p-3"><FileCheck2 className="h-4 w-4" /><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">v{version.version} · {version.fileName}</p><p className="text-xs text-muted-foreground">{version.changeSummary || "No change summary"} · {version.scanStatus.replaceAll("_", " ")}</p></div><Button size="sm" variant="outline" onClick={() => download.mutate({ documentId: document.id, versionId: version.id })}><Download className="h-4 w-4" /></Button></div>)}</div> : <p className="thin-copy mt-3">No file version has been uploaded.</p>}</section></div><DialogFooter><Button variant="outline" onClick={onClose}>Close</Button><Button onClick={() => approve.mutate({ entityId, documentId: document.id, acknowledgementDueAt: dateValue(ackDue) })} disabled={!versions.data?.length || approve.isPending}><CheckCheck className="mr-2 h-4 w-4" />Approve current version</Button></DialogFooter></DialogContent></Dialog>;
}

function PolicyAcknowledgements({ entityId, rows }: { entityId: number; rows: Array<{ acknowledgement: { id: number; status: string; documentVersion: number; dueAt: number | null }; title: string }> }) { const utils = trpc.useUtils(); const acknowledge = trpc.governance.acknowledgePolicy.useMutation({ onSuccess: async () => { await Promise.all([utils.governance.myAcknowledgements.invalidate(), utils.workspace.notifications.invalidate()]); toast.success("Policy acknowledged"); }, onError: error => toast.error(error.message) }); if (!rows.length) return <EmptyState title="Nothing awaiting acknowledgement" description="When an approved policy version is assigned, it will appear here with its due date." icon={CheckCheck} />; return <div className="surface divide-y divide-border/60">{rows.map(row => <div key={row.acknowledgement.id} className="operational-row flex-wrap"><div className="min-w-0 flex-1"><p className="truncate text-sm font-extrabold">{row.title}</p><p className="mt-0.5 truncate text-xs text-muted-foreground">Version {row.acknowledgement.documentVersion}{row.acknowledgement.dueAt ? ` · due ${new Date(row.acknowledgement.dueAt).toLocaleDateString("en-GB")}` : ""}</p></div><StatusBadge status={row.acknowledgement.status} />{row.acknowledgement.status !== "acknowledged" && <Button size="sm" className="h-9 rounded-lg" onClick={() => acknowledge.mutate({ id: row.acknowledgement.id })}>Acknowledge</Button>}</div>)}</div>; }

function TemplatesPanel({ entityId, rows }: { entityId: number; rows: Array<{ id: number; title: string; category: string; version: number }> }) { return <section><div className="mb-3 flex items-center justify-between gap-3"><div><p className="eyebrow">Reusable content</p><h2 className="mt-1 text-xl font-extrabold">Templates</h2></div><CreateTemplateDialog entityId={entityId} /></div>{rows.length ? <div className="surface divide-y divide-border/60">{rows.map(row => <div key={row.id} className="p-4"><p className="text-sm font-extrabold">{row.title}</p><p className="mt-1 text-xs capitalize text-muted-foreground">{row.category.replaceAll("_", " ")} · v{row.version}</p></div>)}</div> : <EmptyState title="No templates" description="Create reusable structured content for packs, plans, risk assessments, notifications, supervisions and commencement records." icon={FileStack} />}</section>; }

function CreateTemplateDialog({ entityId }: { entityId: number }) { const [open, setOpen] = useState(false); const [title, setTitle] = useState(""); const [key, setKey] = useState(""); const [category, setCategory] = useState("support_plan"); const [body, setBody] = useState(""); const utils = trpc.useUtils(); const create = trpc.governance.createTemplate.useMutation({ onSuccess: async result => { await utils.governance.templates.invalidate(); setOpen(false); toast.success(`Template version ${result.version} activated`); }, onError: error => toast.error(error.message) }); return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button size="sm" variant="outline"><Plus className="h-4 w-4" /></Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Create reusable template</DialogTitle><DialogDescription>Use braces for reviewed source fields, for example {'{{property.address}}'}. Generated content must still be checked before approval.</DialogDescription></DialogHeader><div className="grid gap-4 py-3"><Field label="Template title" value={title} onChange={setTitle} /><Field label="Stable template key" value={key} onChange={setKey} /><SelectField label="Category" value={category} onChange={setCategory} options={["provider_pack", "support_plan", "pathway_plan", "risk_assessment", "incident_notification", "supervision", "placement_commencement", "inspection_export", "other"]} /><div className="grid gap-2"><Label>Template body</Label><DictationTextarea value={body} onChange={event => setBody(event.target.value)} rows={8} /></div></div><DialogFooter><Button variant="outline" onClick={() => setOpen(false)}>Cancel</Button><Button onClick={() => create.mutate({ entityId, title, templateKey: key, category: category as any, bodyTemplate: body })} disabled={!title || !key || body.length < 20 || create.isPending}>Activate template</Button></DialogFooter></DialogContent></Dialog>; }

function RetentionPanel({ entityId, rows, documents }: { entityId: number; rows: Array<{ id: number; resourceType: string; resourceId: number; status: string; reviewDueAt: number; legalHold: number; retentionBasis: string }>; documents: DocumentRecord[] }) { const utils = trpc.useUtils(); const decide = trpc.governance.decideRetentionReview.useMutation({ onSuccess: async () => { await utils.governance.retentionReviews.invalidate(); toast.success("Retention decision recorded"); }, onError: error => toast.error(error.message) }); return <section><div className="mb-3 flex items-center justify-between gap-3"><div><p className="eyebrow">Retention</p><h2 className="mt-1 text-xl font-extrabold">Review queue</h2></div><CreateRetentionDialog entityId={entityId} documents={documents} /></div>{rows.length ? <div className="surface divide-y divide-border/60">{rows.map(row => <div key={row.id} className="p-4"><div className="flex items-start justify-between gap-2"><div><p className="text-sm font-extrabold">{row.resourceType} #{row.resourceId}</p><p className="mt-1 text-xs text-muted-foreground">Review {new Date(row.reviewDueAt).toLocaleDateString("en-GB")} · {row.retentionBasis}</p></div><StatusBadge status={row.status} /></div>{row.status === "pending" && <div className="mt-3 flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={() => decide.mutate({ entityId, id: row.id, decision: "hold", notes: "Placed on legal hold pending further review." })}>Hold</Button><Button size="sm" variant="outline" onClick={() => decide.mutate({ entityId, id: row.id, decision: "approved_transfer", notes: "Approved for controlled transfer with export manifest." })}>Transfer</Button><Button size="sm" variant="outline" className="text-destructive" onClick={() => decide.mutate({ entityId, id: row.id, decision: "approved_delete", notes: "Retention period and purpose reviewed; approved for controlled deletion." })}>Approve deletion</Button></div>}</div>)}</div> : <EmptyState title="No retention reviews" description="Create a review before any transfer or deletion. Legal holds prevent deletion approval." icon={Archive} />}</section>; }

function CreateRetentionDialog({ entityId, documents }: { entityId: number; documents: DocumentRecord[] }) { const [open, setOpen] = useState(false); const [documentId, setDocumentId] = useState(""); const [basis, setBasis] = useState(""); const [until, setUntil] = useState(""); const [review, setReview] = useState(""); const [hold, setHold] = useState("no"); const selected = documents.find(item => item.id === Number(documentId)); const utils = trpc.useUtils(); const create = trpc.governance.createRetentionReview.useMutation({ onSuccess: async () => { await utils.governance.retentionReviews.invalidate(); setOpen(false); toast.success("Retention review created"); }, onError: error => toast.error(error.message) }); return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button size="sm" variant="outline"><Plus className="h-4 w-4" /></Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Create retention review</DialogTitle><DialogDescription>Approval does not delete a record. Destruction requires a separate confirmed completion after independent approval.</DialogDescription></DialogHeader><div className="grid gap-4 py-3"><ScopeSelect label="Document" value={documentId || "none"} onChange={value => setDocumentId(value === "none" ? "" : value)} allLabel="Choose document" allValue="none" options={documents.map(item => ({ value: String(item.id), label: item.title }))} /><Field label="Retention basis" value={basis} onChange={setBasis} /><Field label="Retain until" value={until} onChange={setUntil} type="date" /><Field label="Review due" value={review} onChange={setReview} type="date" /><SelectField label="Legal hold" value={hold} onChange={setHold} options={["no", "yes"]} /></div><DialogFooter><Button variant="outline" onClick={() => setOpen(false)}>Cancel</Button><Button onClick={() => selected && create.mutate({ entityId, resourceType: "document", resourceId: selected.id, classification: selected.classification as any, retentionBasis: basis, retentionUntil: dateValue(until)!, reviewDueAt: dateValue(review)!, legalHold: hold === "yes" })} disabled={!selected || !basis || !until || !review || create.isPending}>Create review</Button></DialogFooter></DialogContent></Dialog>; }

function ExportsPanel({ entityId, rows }: { entityId: number; rows: Array<{ id: number; status: string; exportType: string; completedAt: number | null; expiresAt: number | null }> }) { const download = trpc.governance.downloadExport.useMutation({ onSuccess: result => window.open(result.url, "_blank", "noopener,noreferrer"), onError: error => toast.error(error.message) }); return <section><div className="mb-3 flex items-center justify-between gap-3"><div><p className="eyebrow">Evidence sharing</p><h2 className="mt-1 text-xl font-extrabold">Inspection exports</h2></div><CreateExportDialog entityId={entityId} /></div>{rows.length ? <div className="surface divide-y divide-border/60">{rows.map(row => <div key={row.id} className="flex items-center gap-3 p-4"><div className="min-w-0 flex-1"><p className="text-sm font-extrabold capitalize">{row.exportType.replaceAll("_", " ")} #{row.id}</p><p className="mt-1 text-xs text-muted-foreground">{row.completedAt ? `Ready ${new Date(row.completedAt).toLocaleString("en-GB")}` : "Preparing"}{row.expiresAt ? ` · expires ${new Date(row.expiresAt).toLocaleDateString("en-GB")}` : ""}</p></div><StatusBadge status={row.status} />{row.status === "ready" && <Button size="sm" variant="outline" onClick={() => download.mutate({ entityId, id: row.id })}><Download className="h-4 w-4" /></Button>}</div>)}</div> : <EmptyState title="No exports" description="Generate a scoped, redaction-labelled JSON evidence pack with a section manifest and auditable download." icon={Download} />}</section>; }

function CreateExportDialog({ entityId }: { entityId: number }) { const [open, setOpen] = useState(false); const [propertyId, setPropertyId] = useState("all"); const properties = trpc.entities.properties.useQuery({ entityId }); const utils = trpc.useUtils(); const create = trpc.governance.createInspectionExport.useMutation({ onSuccess: async () => { await Promise.all([utils.governance.exports.invalidate(), utils.documents.list.invalidate()]); setOpen(false); toast.success("Inspection export prepared", { description: "The manifest records scope, redaction settings and section counts." }); }, onError: error => toast.error(error.message) }); return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button size="sm"><Download className="mr-2 h-4 w-4" />Export</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Prepare inspection export</DialogTitle><DialogDescription>Young-person references are redacted by default. The export contains a record index and operational evidence, not unrestricted case narratives.</DialogDescription></DialogHeader><div className="py-3"><ScopeSelect label="Property scope" value={propertyId} onChange={setPropertyId} allLabel="All authorised properties" allValue="all" options={(properties.data ?? []).map(item => ({ value: String(item.id), label: `${item.name} — ${item.postcode}` }))} /></div><DialogFooter><Button variant="outline" onClick={() => setOpen(false)}>Cancel</Button><Button onClick={() => create.mutate({ entityId, propertyId: propertyId === "all" ? undefined : Number(propertyId), includeDocumentIndex: true, redactYoungPersonReferences: true })} disabled={create.isPending}>{create.isPending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}Generate export</Button></DialogFooter></DialogContent></Dialog>; }

function CreatePackDialog({ entityId }: { entityId: number }) { const [open, setOpen] = useState(false); const [title, setTitle] = useState(""); const [propertyId, setPropertyId] = useState("none"); const [authorityId, setAuthorityId] = useState("none"); const [templateId, setTemplateId] = useState("none"); const [bank, setBank] = useState("no"); const properties = trpc.entities.properties.useQuery({ entityId }); const authorities = trpc.entities.authorities.useQuery({ entityId }); const templates = trpc.governance.templates.useQuery({ entityId }, { enabled: open }); const packTemplates = (templates.data ?? []).filter(item => item.category === "provider_pack"); const utils = trpc.useUtils(); const create = trpc.documents.createPack.useMutation({ onSuccess: async () => { await utils.documents.packs.invalidate(); setOpen(false); toast.success("Provider pack prepared", { description: "The selected template and current facts were preserved in a dated snapshot." }); }, onError: error => toast.error(error.message) }); return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button id="create-pack-trigger" className="rounded-xl"><PackagePlus className="mr-2 h-4 w-4" />Prepare pack</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Prepare local-authority pack</DialogTitle><DialogDescription>Entity, property, vacancy, effective fee and authority details are reused. Unresolved template placeholders remain visible for review.</DialogDescription></DialogHeader><div className="grid gap-5 py-3"><Field label="Pack title" value={title} onChange={setTitle} /><ScopeSelect label="Provider-pack template" value={templateId} onChange={setTemplateId} allLabel="Structured snapshot only" allValue="none" options={packTemplates.map(item => ({ value: String(item.id), label: `${item.title} · v${item.version}` }))} /><ScopeSelect label="Property" value={propertyId} onChange={setPropertyId} allLabel="No property" allValue="none" options={(properties.data ?? []).map(item => ({ value: String(item.id), label: `${item.name} — ${item.postcode}` }))} /><ScopeSelect label="Local authority" value={authorityId} onChange={setAuthorityId} allLabel="No authority" allValue="none" options={(authorities.data ?? []).map(item => ({ value: String(item.id), label: item.name }))} /><SelectField label="Include encrypted bank details" value={bank} onChange={setBank} options={["no", "yes"]} /></div><DialogFooter><Button variant="outline" onClick={() => setOpen(false)}>Cancel</Button><Button onClick={() => create.mutate({ entityId, title, templateId: templateId === "none" ? undefined : Number(templateId), propertyId: propertyId === "none" ? undefined : Number(propertyId), localAuthorityId: authorityId === "none" ? undefined : Number(authorityId), includeBankDetails: bank === "yes" })} disabled={!title || create.isPending}>{create.isPending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}Generate snapshot</Button></DialogFooter></DialogContent></Dialog>; }

function PackCard({ entityId, pack }: { entityId: number; pack: { id: number; title: string; status: string; updatedAt: Date } }) { const create = trpc.documents.createSecureLink.useMutation({ onSuccess: async result => { const url = `${window.location.origin}${result.path}`; await navigator.clipboard.writeText(url); toast.success("Secure link copied", { description: "The link expires in 72 hours and is limited to 10 views." }); }, onError: error => toast.error(error.message) }); return <article className="surface p-5"><div className="flex items-start justify-between gap-4"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-accent"><PackagePlus className="h-5 w-5" /></div><StatusBadge status={pack.status} /></div><h2 className="mt-6 text-lg font-extrabold">{pack.title}</h2><p className="mt-1 text-xs text-muted-foreground">Snapshot updated {new Date(pack.updatedAt).toLocaleDateString("en-GB")}</p><Button variant="outline" className="mt-5 w-full rounded-xl" onClick={() => create.mutate({ entityId, providerPackId: pack.id, expiresInHours: 72, maxViews: 10 })} disabled={create.isPending}><Copy className="mr-2 h-4 w-4" />Create secure link</Button></article>; }

function Field({ label, value, onChange, type = "text" }: { label: string; value: string; onChange: (value: string) => void; type?: string }) { const id = `doc-${label.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`; return <div className="grid gap-2"><Label htmlFor={id}>{label}</Label><Input id={id} value={value} onChange={event => onChange(event.target.value)} type={type} className="h-11 rounded-xl" /></div>; }
function SelectField({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: string[] }) { return <div className="grid gap-2"><Label>{label}</Label><Select value={value} onValueChange={onChange}><SelectTrigger className="h-11 rounded-xl"><SelectValue /></SelectTrigger><SelectContent>{options.map(option => <SelectItem key={option} value={option}>{option.replaceAll("_", " ")}</SelectItem>)}</SelectContent></Select></div>; }
function ScopeSelect({ label, value, onChange, options, allLabel, allValue }: { label: string; value: string; onChange: (value: string) => void; options: Array<{ value: string; label: string }>; allLabel: string; allValue: string }) { return <div className="grid gap-2"><Label>{label}</Label><Select value={value} onValueChange={onChange}><SelectTrigger className="h-11 rounded-xl"><SelectValue /></SelectTrigger><SelectContent><SelectItem value={allValue}>{allLabel}</SelectItem>{options.map(option => <SelectItem key={option.value} value={option.value}>{option.label}</SelectItem>)}</SelectContent></Select></div>; }
function dateValue(value: string) { return value ? new Date(`${value}T12:00:00`).getTime() : undefined; }
