import { EmptyState, PageHeader, StatusBadge } from "@/components/app/Primitives";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { useWorkspace } from "@/contexts/WorkspaceContext";
import { trpc } from "@/lib/trpc";
import { BarChart3, ClipboardCheck, FileKey2, LineChart, Plus, Scale, ShieldCheck } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";

const day = 86_400_000;
const isoDate = (value: number | null | undefined) => value ? new Date(value).toISOString().slice(0, 10) : "—";
const dateToMs = (value: string) => new Date(`${value}T12:00:00Z`).getTime();
const governanceTabs = ["rights", "frameworks", "outcomes"] as const;
export type GovernanceTab = (typeof governanceTabs)[number];
export function governanceTabFromSearch(search: string): GovernanceTab {
  const tab = new URLSearchParams(search).get("tab");
  return governanceTabs.includes(tab as GovernanceTab) ? tab as GovernanceTab : "rights";
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="grid gap-2"><Label>{label}</Label>{children}</div>; }
function Choice({ label, value, onChange, options }: { label: string; value: string; onChange: (next: string) => void; options: string[] }) { return <Field label={label}><Select value={value} onValueChange={onChange}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{options.map(option => <SelectItem key={option} value={option}>{option.replaceAll("_", " ")}</SelectItem>)}</SelectContent></Select></Field>; }

export default function GovernanceHub() {
  const { entityId } = useWorkspace();
  const [tab, setTab] = useState<GovernanceTab>(() => governanceTabFromSearch(window.location.search));
  const query = trpc.governanceHub.workspace.useQuery({ entityId: entityId! }, { enabled: Boolean(entityId), retry: false });
  useEffect(() => {
    const requested = governanceTabFromSearch(window.location.search);
    if (requested !== tab) setTab(requested);
  }, [tab]);
  const selectTab = (value: string) => {
    const next = governanceTabs.includes(value as GovernanceTab) ? value as GovernanceTab : "rights";
    const params = new URLSearchParams(window.location.search);
    params.set("tab", next);
    window.history.replaceState(null, "", `${window.location.pathname}?${params.toString()}`);
    setTab(next);
  };
  if (!entityId) return <EmptyState icon={Scale} title="Create an entity first" description="Information rights, regulatory frameworks and outcomes measures belong to an accountable legal entity." />;
  if (query.isLoading) return <div className="surface h-72 animate-pulse" aria-label="Loading governance workspace" />;
  if (query.error) return <EmptyState icon={ShieldCheck} title="Governance workspace restricted" description={query.error.message} />;
  const data = query.data!;
  return <div className="space-y-6">
    <PageHeader eyebrow="Controlled governance" title="Information rights & outcomes" description="Run auditable data-rights cases, controlled regulatory-framework approval and defined outcome measures without treating a dashboard state as legal advice." action={<CaseDialog entityId={entityId} />} />
    <Tabs value={tab} onValueChange={selectTab} className="space-y-5">
      <TabsList className="h-auto w-full justify-start gap-1 overflow-x-auto rounded-xl bg-muted p-1">
        <TabsTrigger value="rights" className="min-h-10 rounded-lg"><FileKey2 className="mr-2 h-4 w-4" />Information rights</TabsTrigger>
        <TabsTrigger value="frameworks" className="min-h-10 rounded-lg"><ClipboardCheck className="mr-2 h-4 w-4" />Frameworks</TabsTrigger>
        <TabsTrigger value="outcomes" className="min-h-10 rounded-lg"><LineChart className="mr-2 h-4 w-4" />Outcomes</TabsTrigger>
      </TabsList>
      <TabsContent value="rights"><RightsPanel entityId={entityId} cases={data.cases} /></TabsContent>
      <TabsContent value="frameworks"><FrameworkPanel entityId={entityId} regimes={data.regimes} /></TabsContent>
      <TabsContent value="outcomes"><OutcomesPanel entityId={entityId} measures={data.measures} observations={data.observations} placements={data.placementOptions} /></TabsContent>
    </Tabs>
  </div>;
}

function RightsPanel({ entityId, cases }: { entityId: number; cases: any[] }) {
  return <section className="space-y-4"><div><p className="eyebrow">Data protection workflow</p><h2 className="text-xl font-extrabold">Information-rights cases</h2></div>{!cases.length ? <EmptyState icon={FileKey2} title="No data-rights cases" description="Open a controlled case when a request is received. Requester details remain encrypted and approval is independent." /> : <div className="grid gap-4">{cases.map(record => <CaseCard key={record.id} entityId={entityId} record={record} />)}</div>}</section>;
}

function CaseCard({ entityId, record }: { entityId: number; record: any }) {
  const utils = trpc.useUtils();
  const invalidate = () => utils.governanceHub.workspace.invalidate({ entityId });
  const transition = trpc.governanceHub.transitionCase.useMutation({ onSuccess: () => { toast.success("Case status updated."); invalidate(); }, onError: error => toast.error(error.message) });
  const approve = trpc.governanceHub.approveCase.useMutation({ onSuccess: () => { toast.success("Case independently approved."); invalidate(); }, onError: error => toast.error(error.message) });
  const close = () => transition.mutate({ entityId, caseId: record.id, status: "closed", reasonCode: "case_closed" });
  const advance = (status: "collecting" | "redacting" | "awaiting_approval", reasonCode: "scope_confirmed" | "records_collected" | "redaction_complete" | "approval_requested") => transition.mutate({ entityId, caseId: record.id, status, reasonCode });
  return <article className="surface p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="eyebrow">{record.caseReference} · {record.requestType.replaceAll("_", " ")}</p><h3 className="mt-2 text-lg font-extrabold">{record.requesterName ?? "Restricted requester"}</h3><p className="mt-1 text-xs text-muted-foreground">Received {isoDate(record.receivedAt)} · response due {isoDate(record.dueAt)}</p></div><StatusBadge status={record.status} /></div><div className="mt-4 grid gap-3 text-sm sm:grid-cols-3"><div className="rounded-xl bg-muted/60 p-3"><span className="text-xs text-muted-foreground">Identity</span><p className="mt-1 font-bold">{record.identityStatus.replaceAll("_", " ")}</p></div><div className="rounded-xl bg-muted/60 p-3"><span className="text-xs text-muted-foreground">Scope</span><p className="mt-1 font-bold">{Array.isArray(record.scope?.areas) ? record.scope.areas.join(", ").replaceAll("_", " ") : "Restricted"}</p></div><div className="rounded-xl bg-muted/60 p-3"><span className="text-xs text-muted-foreground">Case state</span><p className="mt-1 font-bold">{record.status.replaceAll("_", " ")}</p></div></div><div className="mt-5 flex flex-wrap gap-2">{["not_started", "pending"].includes(record.identityStatus) && <IdentityDialog entityId={entityId} caseId={record.id} />}{record.status === "scoping" && <Button size="sm" variant="outline" onClick={() => advance("collecting", "scope_confirmed")}>Start collection</Button>}{record.status === "collecting" && <Button size="sm" variant="outline" onClick={() => advance("redacting", "records_collected")}>Begin redaction</Button>}{record.status === "redacting" && <Button size="sm" variant="outline" onClick={() => advance("awaiting_approval", "redaction_complete")}>Request approval</Button>}{record.status === "awaiting_approval" && <Button size="sm" onClick={() => approve.mutate({ entityId, caseId: record.id })} disabled={approve.isPending}>Approve independently</Button>}{record.status === "ready" && <DeliveryDialog entityId={entityId} caseId={record.id} />}{record.status === "delivered" && <Button size="sm" variant="outline" onClick={close} disabled={transition.isPending}>Close case</Button>}</div></article>;
}

function CaseDialog({ entityId }: { entityId: number }) {
  const [open, setOpen] = useState(false); const [reference, setReference] = useState(`DR-${new Date().toISOString().slice(0, 10).replaceAll("-", "")}`); const [requestType, setRequestType] = useState("access"); const [requesterType, setRequesterType] = useState("young_person"); const [name, setName] = useState(""); const [contact, setContact] = useState(""); const [scope, setScope] = useState("all_records"); const [received, setReceived] = useState(isoDate(Date.now())); const [due, setDue] = useState(isoDate(Date.now() + 30 * day));
  const utils = trpc.useUtils(); const mutation = trpc.governanceHub.createCase.useMutation({ onSuccess: () => { setOpen(false); toast.success("Data-rights case opened for independent identity verification."); utils.governanceHub.workspace.invalidate({ entityId }); }, onError: error => toast.error(error.message) });
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button className="rounded-xl"><Plus className="mr-2 h-4 w-4" />New case</Button></DialogTrigger><DialogContent className="max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>Open data-rights case</DialogTitle><DialogDescription>Enter only the information needed to begin the request. Requester details are encrypted; identity verification and case approval require a different authorised user.</DialogDescription></DialogHeader><Field label="Case reference"><Input value={reference} onChange={event => setReference(event.target.value.toUpperCase())} /></Field><Choice label="Request type" value={requestType} onChange={setRequestType} options={["access", "rectification", "restriction", "objection", "erasure", "portability", "sharing_review", "complaint"]} /><Choice label="Requester type" value={requesterType} onChange={setRequesterType} options={["young_person", "parent", "representative", "professional", "staff", "other"]} /><Field label="Requester name"><Input value={name} onChange={event => setName(event.target.value)} /></Field><Field label="Secure contact (optional)"><Input value={contact} onChange={event => setContact(event.target.value)} /></Field><Choice label="Initial scope" value={scope} onChange={setScope} options={["all_records", "placement_records", "safeguarding", "workforce", "finance", "documents", "other"]} /><Field label="Received date"><Input type="date" value={received} onChange={event => setReceived(event.target.value)} /></Field><Field label="Response due date"><Input type="date" value={due} onChange={event => setDue(event.target.value)} /></Field><DialogFooter><Button onClick={() => mutation.mutate({ entityId, caseReference: reference, requestType: requestType as any, requesterType: requesterType as any, requesterName: name, requesterContact: contact || undefined, scope: [scope as any], receivedAt: dateToMs(received), dueAt: dateToMs(due) })} disabled={name.trim().length < 2 || !reference}>Open controlled case</Button></DialogFooter></DialogContent></Dialog>;
}

function IdentityDialog({ entityId, caseId }: { entityId: number; caseId: number }) { const [open, setOpen] = useState(false); const [method, setMethod] = useState("Secure identity check"); const [reference, setReference] = useState(""); const utils = trpc.useUtils(); const mutation = trpc.governanceHub.verifyCaseIdentity.useMutation({ onSuccess: () => { setOpen(false); toast.success("Identity decision recorded."); utils.governanceHub.workspace.invalidate({ entityId }); }, onError: error => toast.error(error.message) }); return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button size="sm" variant="outline">Verify identity</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Record identity decision</DialogTitle><DialogDescription>Only a user other than the case creator can verify or refuse identity. Do not place identity document contents in this field.</DialogDescription></DialogHeader><Field label="Method"><Input value={method} onChange={event => setMethod(event.target.value)} /></Field><Field label="Evidence reference (optional)"><Input value={reference} onChange={event => setReference(event.target.value)} /></Field><DialogFooter><Button onClick={() => mutation.mutate({ entityId, caseId, status: "verified", method, reference: reference || undefined })} disabled={method.trim().length < 3}>Record verification</Button></DialogFooter></DialogContent></Dialog>; }

function DeliveryDialog({ entityId, caseId }: { entityId: number; caseId: number }) { const [open, setOpen] = useState(false); const [method, setMethod] = useState("secure_link"); const [reference, setReference] = useState(""); const utils = trpc.useUtils(); const mutation = trpc.governanceHub.recordCaseDelivery.useMutation({ onSuccess: () => { setOpen(false); toast.success("Delivery evidence recorded."); utils.governanceHub.workspace.invalidate({ entityId }); }, onError: error => toast.error(error.message) }); return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button size="sm">Record delivery</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Record delivery evidence</DialogTitle><DialogDescription>This records evidence of an external delivery; it does not transmit personal data from the application.</DialogDescription></DialogHeader><Choice label="Delivery method" value={method} onChange={setMethod} options={["secure_link", "secure_email", "post", "collection", "other"]} /><Field label="Delivery reference"><Input value={reference} onChange={event => setReference(event.target.value)} /></Field><DialogFooter><Button onClick={() => mutation.mutate({ entityId, caseId, method: method as any, reference })} disabled={reference.trim().length < 3}>Record delivery</Button></DialogFooter></DialogContent></Dialog>; }

function FrameworkPanel({ entityId, regimes }: { entityId: number; regimes: any[] }) { return <section className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="eyebrow">Source-controlled policy</p><h2 className="text-xl font-extrabold">Regulatory frameworks</h2></div><RegimeDialog entityId={entityId} /></div>{!regimes.length ? <EmptyState icon={ClipboardCheck} title="No framework records" description="Create a source-linked draft before review, independent approval and activation." /> : <div className="grid gap-4">{regimes.map(record => <RegimeCard key={record.id} entityId={entityId} record={record} />)}</div>}</section>; }
function RegimeCard({ entityId, record }: { entityId: number; record: any }) { const utils = trpc.useUtils(); const refresh = () => utils.governanceHub.workspace.invalidate({ entityId }); const submit = trpc.governanceHub.submitRegimeForReview.useMutation({ onSuccess: () => { toast.success("Framework sent for review."); refresh(); }, onError: error => toast.error(error.message) }); const approve = trpc.governanceHub.approveRegime.useMutation({ onSuccess: () => { toast.success("Framework independently approved."); refresh(); }, onError: error => toast.error(error.message) }); const activate = trpc.governanceHub.activateRegime.useMutation({ onSuccess: () => { toast.success("Approved framework activated."); refresh(); }, onError: error => toast.error(error.message) }); return <article className="surface p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="eyebrow">{record.jurisdiction}{record.regulator ? ` · ${record.regulator}` : ""}</p><h3 className="mt-2 text-lg font-extrabold">{record.name}</h3><p className="mt-1 text-xs text-muted-foreground">Effective from {isoDate(record.effectiveFrom)}</p></div><StatusBadge status={record.status} /></div><div className="mt-4 flex flex-wrap items-center gap-2 text-sm"><a className="font-semibold text-primary underline-offset-4 hover:underline" href={record.sourceUrl} target="_blank" rel="noreferrer">Open source</a><span className="text-muted-foreground">Applies to {Array.isArray(record.applicability?.areas) ? record.applicability.areas.join(", ").replaceAll("_", " ") : "recorded scope"}</span></div><div className="mt-5 flex flex-wrap gap-2">{record.status === "draft" && <Button size="sm" variant="outline" onClick={() => submit.mutate({ entityId, regimeId: record.id })}>Send for review</Button>}{record.status === "in_review" && <Button size="sm" onClick={() => approve.mutate({ entityId, regimeId: record.id })}>Approve independently</Button>}{record.status === "approved" && <Button size="sm" onClick={() => activate.mutate({ entityId, regimeId: record.id })}>Activate independently</Button>}</div></article>; }
function RegimeDialog({ entityId }: { entityId: number }) { const [open, setOpen] = useState(false); const [name, setName] = useState(""); const [jurisdiction, setJurisdiction] = useState("England"); const [regulator, setRegulator] = useState(""); const [sourceUrl, setSourceUrl] = useState(""); const [effective, setEffective] = useState(isoDate(Date.now())); const [area, setArea] = useState("properties"); const utils = trpc.useUtils(); const mutation = trpc.governanceHub.createRegime.useMutation({ onSuccess: () => { setOpen(false); toast.success("Source-linked framework draft created."); utils.governanceHub.workspace.invalidate({ entityId }); }, onError: error => toast.error(error.message) }); return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button className="rounded-xl"><Plus className="mr-2 h-4 w-4" />New framework</Button></DialogTrigger><DialogContent className="max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>Create framework record</DialogTitle><DialogDescription>Record the authoritative source and relevant operational area. Review, approval and activation are independent transitions.</DialogDescription></DialogHeader><Field label="Framework name"><Input value={name} onChange={event => setName(event.target.value)} /></Field><Field label="Jurisdiction"><Input value={jurisdiction} onChange={event => setJurisdiction(event.target.value)} /></Field><Field label="Regulator (optional)"><Input value={regulator} onChange={event => setRegulator(event.target.value)} /></Field><Field label="Authoritative source URL"><Input type="url" value={sourceUrl} onChange={event => setSourceUrl(event.target.value)} /></Field><Field label="Effective from"><Input type="date" value={effective} onChange={event => setEffective(event.target.value)} /></Field><Choice label="Primary applicability" value={area} onChange={setArea} options={["properties", "workforce", "placements", "records", "finance", "governance"]} /><DialogFooter><Button onClick={() => mutation.mutate({ entityId, name, jurisdiction, regulator: regulator || undefined, sourceUrl, effectiveFrom: dateToMs(effective), applicability: [area as any] })} disabled={name.trim().length < 3 || jurisdiction.trim().length < 2 || !sourceUrl}>Create draft</Button></DialogFooter></DialogContent></Dialog>; }

function OutcomesPanel({ entityId, measures, observations, placements }: { entityId: number; measures: any[]; observations: any[]; placements: any[] }) { return <section className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="eyebrow">Defined measures</p><h2 className="text-xl font-extrabold">Outcome observations</h2></div><MeasureDialog entityId={entityId} /></div>{!measures.length ? <EmptyState icon={BarChart3} title="No outcome measures" description="Create a clearly defined draft measure. Another authorised user must activate it before observations can be recorded." /> : <div className="grid gap-4">{measures.map(record => <MeasureCard key={record.id} entityId={entityId} record={record} placements={placements} observations={observations.filter(item => item.measureId === record.id)} />)}</div>}</section>; }
function MeasureCard({ entityId, record, placements, observations }: { entityId: number; record: any; placements: any[]; observations: any[] }) { const utils = trpc.useUtils(); const refresh = () => utils.governanceHub.workspace.invalidate({ entityId }); const activate = trpc.governanceHub.activateMeasure.useMutation({ onSuccess: () => { toast.success("Measure independently activated."); refresh(); }, onError: error => toast.error(error.message) }); const pause = trpc.governanceHub.pauseMeasure.useMutation({ onSuccess: () => { toast.success("Measure paused."); refresh(); }, onError: error => toast.error(error.message) }); return <article className="surface p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="eyebrow">{record.domain.replaceAll("_", " ")} · {record.measureType}</p><h3 className="mt-2 text-lg font-extrabold">{record.name}</h3><p className="mt-1 text-xs text-muted-foreground">Key: {record.key}{record.unit ? ` · ${record.unit}` : ""} · {observations.length} recorded observations</p></div><StatusBadge status={record.status} /></div><div className="mt-5 flex flex-wrap gap-2">{["draft", "paused"].includes(record.status) && <Button size="sm" onClick={() => activate.mutate({ entityId, measureId: record.id })}>Activate independently</Button>}{record.status === "active" && <><ObservationDialog entityId={entityId} measureId={record.id} placements={placements} /><Button size="sm" variant="outline" onClick={() => pause.mutate({ entityId, measureId: record.id })}>Pause measure</Button></>}</div></article>; }
function MeasureDialog({ entityId }: { entityId: number }) { const [open, setOpen] = useState(false); const [key, setKey] = useState(""); const [name, setName] = useState(""); const [domain, setDomain] = useState("outcome"); const [type, setType] = useState("count"); const [unit, setUnit] = useState(""); const [direction, setDirection] = useState("neutral"); const utils = trpc.useUtils(); const mutation = trpc.governanceHub.createMeasure.useMutation({ onSuccess: () => { setOpen(false); toast.success("Outcome measure draft created."); utils.governanceHub.workspace.invalidate({ entityId }); }, onError: error => toast.error(error.message) }); return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button className="rounded-xl"><Plus className="mr-2 h-4 w-4" />New measure</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Create outcome measure</DialogTitle><DialogDescription>Define the measure before data is captured. An independent authorised user must activate it.</DialogDescription></DialogHeader><Field label="Measure key"><Input value={key} onChange={event => setKey(event.target.value.toLowerCase().replaceAll(" ", "_"))} placeholder="placement_stability" /></Field><Field label="Measure name"><Input value={name} onChange={event => setName(event.target.value)} /></Field><Choice label="Domain" value={domain} onChange={setDomain} options={["incident", "complaint", "missing", "restraint", "placement", "staffing", "compliance", "finance", "improvement", "outcome", "feedback"]} /><Choice label="Measure type" value={type} onChange={setType} options={["count", "percentage", "average", "duration", "currency", "score", "custom"]} /><Field label="Unit (optional)"><Input value={unit} onChange={event => setUnit(event.target.value)} /></Field><Choice label="Direction" value={direction} onChange={setDirection} options={["higher_is_better", "lower_is_better", "neutral"]} /><DialogFooter><Button onClick={() => mutation.mutate({ entityId, key, name, domain: domain as any, measureType: type as any, unit: unit || undefined, direction: direction as any })} disabled={key.length < 2 || name.trim().length < 3}>Create draft</Button></DialogFooter></DialogContent></Dialog>; }
function ObservationDialog({ entityId, measureId, placements }: { entityId: number; measureId: number; placements: any[] }) { const [open, setOpen] = useState(false); const [placementId, setPlacementId] = useState(placements[0] ? String(placements[0].id) : ""); const [start, setStart] = useState(isoDate(Date.now() - 7 * day)); const [end, setEnd] = useState(isoDate(Date.now())); const [value, setValue] = useState(""); const [score, setScore] = useState(""); const [feedback, setFeedback] = useState(""); const [source, setSource] = useState("key_worker"); const utils = trpc.useUtils(); const mutation = trpc.governanceHub.recordObservation.useMutation({ onSuccess: () => { setOpen(false); toast.success("Outcome observation recorded."); utils.governanceHub.workspace.invalidate({ entityId }); }, onError: error => toast.error(error.message) }); return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button size="sm" variant="outline" disabled={!placements.length}>Record observation</Button></DialogTrigger><DialogContent className="max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>Record outcome observation</DialogTitle><DialogDescription>Only active measures can receive observations. Feedback is encrypted; the server validates the period and placement scope again on submission.</DialogDescription></DialogHeader><Choice label="Placement" value={placementId} onChange={setPlacementId} options={placements.map(item => String(item.id))} /><p className="-mt-1 text-xs text-muted-foreground">Choose the authoritative placement ID assigned to your scope.</p><Field label="Period start"><Input type="date" value={start} onChange={event => setStart(event.target.value)} /></Field><Field label="Period end"><Input type="date" value={end} onChange={event => setEnd(event.target.value)} /></Field><Field label="Numeric value (optional)"><Input inputMode="decimal" value={value} onChange={event => setValue(event.target.value)} /></Field><Field label="Feedback score 0–10 (optional)"><Input inputMode="numeric" value={score} onChange={event => setScore(event.target.value)} /></Field><Field label="Feedback (optional)"><Textarea value={feedback} onChange={event => setFeedback(event.target.value)} /></Field><Choice label="Source" value={source} onChange={setSource} options={["young_person", "key_worker", "manager", "professional", "system_import"]} /><DialogFooter><Button onClick={() => mutation.mutate({ entityId, measureId, placementId: Number(placementId), periodStart: dateToMs(start), periodEnd: dateToMs(end), numericValue: value || undefined, feedbackScore: score ? Number(score) : undefined, feedback: feedback || undefined, source: source as any })} disabled={!placementId || (!value && !score && !feedback)}>Record observation</Button></DialogFooter></DialogContent></Dialog>; }
