import { CreateEntityDialog } from "@/components/app/CreateEntityDialog";
import { ActionCard, MetricCard, PageHeader } from "@/components/app/Primitives";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { useWorkspace } from "@/contexts/WorkspaceContext";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, ArrowRight, Building2, CalendarPlus, ClipboardPlus, DatabaseZap, House, ShieldCheck, UsersRound, WalletCards } from "lucide-react";
import { useLocation } from "wouter";

export default function Home() {
  const { entityId, entity, loading: workspaceLoading } = useWorkspace();
  const [, setLocation] = useLocation();
  const { data, isLoading } = trpc.dashboard.summary.useQuery({ entityId: entityId ?? undefined }, { enabled: Boolean(entityId) });
  const quality = trpc.workspace.dataQuality.useQuery({ entityId: entityId! }, { enabled: Boolean(entityId), retry: false });

  if (!workspaceLoading && !entityId) return <Onboarding />;
  return <div className="mx-auto max-w-[1480px] pb-20"><PageHeader eyebrow="Today" title={entity ? `${entity.name} overview` : "Operational overview"} description="The most important compliance, staffing, placement and finance work is brought forward automatically." action={<Button variant="outline" className="rounded-xl bg-card" onClick={() => setLocation("/search")}>Find a record <ArrowRight className="ml-2 h-4 w-4" /></Button>} />
    {isLoading ? <DashboardSkeleton /> : !data ? <DashboardUnavailable onRetry={() => window.location.reload()} /> : <>
      <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4" aria-label="Headline measures">
        <MetricCard label="Properties" value={data.counts.properties ?? 0} note="Across the current entity" icon={Building2} />
        <MetricCard label="Active staff" value={data.counts.activeStaff ?? 0} note={`${data.counts.openShifts ?? 0} open shifts`} icon={UsersRound} tone="blush" />
        <MetricCard label="Active placements" value={data.counts.activePlacements ?? 0} note="Restricted by assignment" icon={House} tone="green" />
        <MetricCard label="Needs attention" value={(data.rag?.red ?? 0) + (data.counts.openIncidents ?? 0)} note={`${data.rag?.amber ?? 0} due soon`} icon={AlertTriangle} tone="amber" />
      </section>
      <section className="mt-6 grid gap-6 xl:grid-cols-[1.35fr_0.65fr]">
        <div className="surface overflow-hidden"><div className="flex items-center justify-between border-b border-border/70 p-5 sm:p-6"><div><p className="eyebrow">Priority queue</p><h2 className="mt-1 text-xl font-extrabold tracking-[-0.035em]">What needs action</h2></div><Button variant="ghost" onClick={() => setLocation("/work-plans")}>View all <ArrowRight className="ml-2 h-4 w-4" /></Button></div>{data.priorities?.length ? <div className="divide-y divide-border/60">{data.priorities.map(item => <button key={`${item.kind}-${item.id}`} onClick={() => setLocation(item.kind === "compliance" ? "/compliance" : item.kind === "incident" ? "/key-worker" : "/work-plans")} className="flex w-full items-center gap-4 p-5 text-left hover:bg-muted/60"><span className={`h-2.5 w-2.5 shrink-0 rounded-full ${item.tone === "red" ? "bg-destructive" : item.tone === "amber" ? "bg-amber-500" : "bg-primary"}`} aria-hidden="true" /><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{item.title}</p><p className="mt-1 text-xs capitalize text-muted-foreground">{item.kind.replaceAll("_", " ")}{item.dueAt ? ` · ${new Date(item.dueAt).toLocaleDateString("en-GB")}` : ""}</p></div><ArrowRight className="h-4 w-4 text-muted-foreground" /></button>)}</div> : <div className="p-8 text-center"><ShieldCheck className="mx-auto h-7 w-7 text-emerald-600" /><p className="mt-3 font-bold">No urgent items</p><p className="thin-copy mt-1">New obligations and actions will appear here.</p></div>}</div>
        <aside className="surface p-5 sm:p-6"><p className="eyebrow">Compliance health</p><h2 className="mt-1 text-xl font-extrabold tracking-[-0.035em]">Current obligations</h2><div className="mt-7 grid grid-cols-2 gap-3">{([['Green', data.rag?.green ?? 0, 'bg-emerald-100 text-emerald-800'], ['Amber', data.rag?.amber ?? 0, 'bg-amber-100 text-amber-800'], ['Red', data.rag?.red ?? 0, 'bg-red-100 text-red-800'], ['Unrated', data.rag?.grey ?? 0, 'bg-slate-100 text-slate-700']] as const).map(([label, count, classes]) => <div key={label} className={`rounded-2xl p-4 ${classes}`}><p className="text-2xl font-extrabold">{count}</p><p className="mt-1 text-xs font-semibold">{label}</p></div>)}</div><Button className="mt-5 w-full rounded-xl" onClick={() => setLocation("/compliance")}>Open compliance calendar</Button></aside>
      </section>
      <section className="surface mt-6 overflow-hidden"><div className="flex flex-col gap-3 border-b border-border/70 p-5 sm:flex-row sm:items-center sm:justify-between sm:p-6"><div><p className="eyebrow">Record health</p><h2 className="mt-1 text-xl font-extrabold tracking-[-0.035em]">Corrective checks</h2><p className="thin-copy mt-1">Duplicates, stale facts, missing evidence and background rules are checked within your permissions.</p></div>{quality.data && <div className="flex gap-2"><span className="rounded-xl bg-red-50 px-3 py-2 text-xs font-bold text-red-800">{quality.data.counts.urgent} urgent</span><span className="rounded-xl bg-amber-50 px-3 py-2 text-xs font-bold text-amber-800">{quality.data.counts.warning} warnings</span></div>}</div>{quality.isLoading ? <div className="p-6"><Skeleton className="h-20 rounded-xl" /></div> : quality.error ? <div className="flex items-start gap-3 p-6 text-sm text-muted-foreground"><DatabaseZap className="mt-0.5 h-4 w-4 shrink-0" /><p>Record-health checks are unavailable for this role or connection. Operational modules remain available.</p></div> : quality.data?.issues.length ? <div className="divide-y divide-border/60">{quality.data.issues.slice(0, 8).map(issue => <button key={issue.key} onClick={() => setLocation(issue.path)} className="flex w-full items-start gap-4 p-5 text-left hover:bg-muted/60"><span className={`mt-1 h-2.5 w-2.5 shrink-0 rounded-full ${issue.severity === "urgent" ? "bg-destructive" : issue.severity === "warning" ? "bg-amber-500" : "bg-primary"}`} /><div className="min-w-0 flex-1"><p className="text-sm font-extrabold">{issue.title}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{issue.message}</p></div><ArrowRight className="mt-1 h-4 w-4 text-muted-foreground" /></button>)}</div> : <div className="flex items-start gap-3 p-6"><ShieldCheck className="mt-0.5 h-5 w-5 text-emerald-600" /><div><p className="text-sm font-extrabold">No detected record-health issues</p><p className="thin-copy mt-1">Last checked {quality.data ? new Date(quality.data.checkedAt).toLocaleString("en-GB") : "now"}. This check supports, but does not replace, management review.</p></div></div>}</section>
      <section className="mt-6"><div className="mb-4"><p className="eyebrow">Guided actions</p><h2 className="mt-1 text-xl font-extrabold tracking-[-0.035em]">Create without repeating details</h2></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><ActionCard title="Add property" description="Start onboarding with compliance actions created automatically." icon={Building2} onClick={() => setLocation("/properties")} /><ActionCard title="Record referral" description="Create a reference-led referral and placement context." icon={ClipboardPlus} tone="blush" onClick={() => setLocation("/placements")} /><ActionCard title="Plan a shift" description="Choose a property and see coverage clearly." icon={CalendarPlus} onClick={() => setLocation("/rota")} /><ActionCard title="Prepare invoice" description="Reuse authority, fee and placement details." icon={WalletCards} tone="blush" onClick={() => setLocation("/finance")} /></div></section>
    </>}
  </div>;
}

function Onboarding() {
  return <div className="relative mx-auto grid min-h-[75vh] max-w-6xl place-items-center overflow-hidden rounded-[2rem] bg-card p-6 sm:p-12"><div className="geometry-blue absolute -left-16 top-16 h-52 w-52 rotate-12 rounded-[3.5rem]" /><div className="geometry-blush absolute -right-16 bottom-8 h-60 w-60 rounded-full" /><div className="relative z-10 max-w-2xl text-center"><div className="mx-auto mb-6 grid h-14 w-14 place-items-center rounded-2xl bg-foreground text-background"><House className="h-6 w-6" /></div><p className="eyebrow">Start with one trusted source</p><h1 className="mt-3 text-4xl font-extrabold tracking-[-0.055em] sm:text-6xl">Set up the organisation once.</h1><p className="thin-copy mx-auto mt-5 max-w-xl">Entity information will pre-populate properties, provider packs and invoices. You can add more legal entities later and keep access separate.</p><div className="mt-8"><CreateEntityDialog first /></div><p className="mt-5 text-xs text-muted-foreground">Only owners can create legal entities. Every change is recorded.</p></div></div>;
}

function DashboardSkeleton() { return <section aria-live="polite"><div className="mb-5 flex items-center gap-3 rounded-xl border border-sky-100 bg-sky-50 p-4 text-sm text-sky-950"><span className="h-4 w-4 animate-spin rounded-full border-2 border-sky-300 border-t-sky-800" /><div><p className="font-extrabold">Loading your operational overview</p><p className="mt-0.5 text-xs">Retrieving only the records that your current company role is allowed to view.</p></div></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{Array.from({ length: 4 }).map((_, index) => <Skeleton key={index} className="h-44 rounded-2xl" />)}</div></section>; }
function DashboardUnavailable({ onRetry }: { onRetry: () => void }) { return <section className="surface mx-auto max-w-2xl p-8 text-center"><DatabaseZap className="mx-auto h-8 w-8 text-amber-700" /><h2 className="mt-4 text-2xl font-extrabold">Overview data is not available yet</h2><p className="mt-2 text-sm text-muted-foreground">Your role is signed in, but the overview could not be loaded. Check your company access or try again. Other permitted workspaces may still be available.</p><p className="mt-3 text-xs font-semibold text-muted-foreground">Support code: APP_OVERVIEW_UNAVAILABLE</p><Button className="mt-5 rounded-xl" onClick={onRetry}>Try again</Button></section>; }
