import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { Download, FileText, House, LockKeyhole, ShieldX } from "lucide-react";
import { useParams } from "wouter";

export default function InvoiceSharePage() {
  const { token } = useParams<{ token: string }>(); const query = trpc.finance.resolveSecureLink.useQuery({ token: token ?? "" }, { enabled: Boolean(token), retry: false, refetchOnWindowFocus: false });
  if (query.isLoading) return <main className="grid min-h-screen place-items-center bg-background p-5"><div className="surface w-full max-w-lg animate-pulse p-10"><div className="h-8 w-52 rounded bg-muted" /><div className="mt-5 h-24 rounded bg-muted" /></div></main>;
  if (query.error || !query.data) return <main className="grid min-h-screen place-items-center bg-background p-5"><section className="surface w-full max-w-lg p-8 text-center sm:p-12"><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-red-50 text-destructive"><ShieldX className="h-6 w-6" /></div><h1 className="mt-6 text-3xl font-extrabold tracking-[-0.05em]">Invoice unavailable</h1><p className="thin-copy mt-4">{query.error?.message ?? "This secure link cannot be used."} Ask the provider’s finance contact for a new link.</p></section></main>;
  const { invoice } = query.data;
  return <main className="relative min-h-screen overflow-hidden bg-background p-5 sm:p-10"><div className="geometry-blue absolute -left-28 top-16 h-64 w-64 rotate-12 rounded-[4rem]" /><div className="geometry-blush absolute -right-24 bottom-12 h-72 w-72 rounded-full" /><section className="surface relative z-10 mx-auto max-w-3xl p-6 sm:p-10"><div className="flex items-center gap-3 border-b border-border/70 pb-6"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-foreground text-background"><House className="h-5 w-5" /></div><div><p className="font-extrabold tracking-[-0.04em]">Supported Accommodation</p><p className="text-xs text-muted-foreground">Secure invoice delivery</p></div></div><div className="mt-8 flex flex-col gap-6 sm:flex-row sm:items-start sm:justify-between"><div><p className="eyebrow">Issued invoice</p><h1 className="mt-2 text-3xl font-extrabold tracking-[-0.05em]">{invoice.invoiceNumber}</h1><p className="thin-copy mt-3">{invoice.customerName} · placement reference {invoice.reference}</p></div><p className="text-3xl font-extrabold">£{invoice.total.toFixed(2)}</p></div><div className="mt-8 grid gap-3 rounded-2xl bg-muted p-5 sm:grid-cols-3"><Fact label="Invoice date" value={new Date(invoice.invoiceDate).toLocaleDateString("en-GB")} /><Fact label="Due date" value={invoice.dueAt ? new Date(invoice.dueAt).toLocaleDateString("en-GB") : "—"} /><Fact label="Fee period" value={`${new Date(invoice.periodStart).toLocaleDateString("en-GB")} – ${new Date(invoice.periodEnd).toLocaleDateString("en-GB")}`} /></div><Button size="lg" className="mt-8 h-12 w-full rounded-xl" asChild><a href={query.data.fileUrl} target="_blank" rel="noreferrer"><Download className="mr-2 h-4 w-4" />Open invoice PDF</a></Button><div className="mt-6 flex items-start gap-3 rounded-xl border border-border/70 p-4"><LockKeyhole className="mt-0.5 h-4 w-4 shrink-0 text-primary" /><p className="text-xs leading-5 text-muted-foreground">This link expires {new Date(query.data.expiresAt).toLocaleString("en-GB")}{query.data.remainingViews !== null ? ` and has ${query.data.remainingViews} view${query.data.remainingViews === 1 ? "" : "s"} remaining` : ""}. Each access is recorded.</p></div></section></main>;
}

function Fact({ label, value }: { label: string; value: string }) { return <div><p className="text-[0.65rem] font-semibold uppercase tracking-wider text-muted-foreground">{label}</p><p className="mt-1 text-sm font-bold">{value}</p></div>; }
