import { EmptyState, PageHeader, StatusBadge } from "@/components/app/Primitives";
import { VisitorLogDialog } from "@/components/VisitorLogDialog";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import { Skeleton } from "@/components/ui/skeleton";
import { DictationTextarea } from "@/components/DictationFields";
import { KeyworkerRotaSummary } from "@/components/RotaCoverageBoard";
import { useAuth } from "@/_core/hooks/useAuth";
import { useWorkspace } from "@/contexts/WorkspaceContext";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, ArrowRight, BellRing, CheckCheck, ClipboardPenLine, Clock3, FileText, LogIn, LogOut, MapPin, ShieldCheck, UserRoundCheck, UsersRound } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";
import { useLocation } from "wouter";

type PendingClock = { eventType: "clock_in" | "clock_out"; coordinates?: GeolocationCoordinates; message: string } | null;

export default function KeyWorkerApp() {
  const { entityId, entity } = useWorkspace();
  const { user } = useAuth();
  const [, setLocation] = useLocation();
  const context = trpc.keywork.context.useQuery({ entityId: entityId! }, { enabled: Boolean(entityId), retry: false });
  const shifts = trpc.operations.shifts.useQuery({ entityId: entityId! }, { enabled: Boolean(entityId), retry: false, refetchInterval: 30_000 });
  const notifications = trpc.workspace.notifications.useQuery(undefined, { refetchInterval: 30_000 });
  const [pendingClock, setPendingClock] = useState<PendingClock>(null);
  const [overrideReason, setOverrideReason] = useState("");
  const [briefOpen, setBriefOpen] = useState(false);
  const [visitorOpen, setVisitorOpen] = useState(false);
  const [briefTemplate, setBriefTemplate] = useState<"nursing_general" | "nursing_night" | "operational">("operational");
  const [briefFields, setBriefFields] = useState<Record<string, string>>({});
  const [briefSummary, setBriefSummary] = useState("");
  const [briefRisks, setBriefRisks] = useState("");
  const [briefActions, setBriefActions] = useState("");
  const [dictatedText, setDictatedText] = useState("");
  const clock = trpc.operations.clock.useMutation({ onSuccess: result => { toast.success("Attendance recorded", { description: result.locationState.replaceAll("_", " ") }); setPendingClock(null); setOverrideReason(""); }, onError: error => toast.error("Attendance could not be recorded", { description: error.message }) });
  const myShifts = useMemo(() => (shifts.data ?? []).filter(shift => shift.assignedUserId === user?.id && shift.status !== "cancelled").sort((a, b) => a.startsAt - b.startsAt), [shifts.data, user?.id]);
  const activeShift = useMemo(() => { const now = Date.now(); return myShifts.find(shift => shift.startsAt <= now && shift.endsAt >= now) ?? null; }, [myShifts]);
  const selectedShift = activeShift ?? myShifts.find(shift => shift.startsAt >= Date.now()) ?? null;
  const templates = trpc.operations.handoverTemplates.useQuery({ entityId: entityId! }, { enabled: Boolean(entityId), retry: false });
  const handovers = trpc.operations.handovers.useQuery({ entityId: entityId!, propertyId: selectedShift?.propertyId ?? -1, shiftId: selectedShift?.id }, { enabled: Boolean(entityId && selectedShift?.propertyId && selectedShift?.id), retry: false });
  const selectedTemplate = templates.data?.find(template => template.code === briefTemplate);
  const selectedProperty = context.data?.properties.find(property => property.id === selectedShift?.propertyId) ?? null;
  const previousHandovers = useMemo(() => (handovers.data ?? []).filter(handover => selectedShift && handover.createdBy !== user?.id && handover.shiftId !== selectedShift.id && new Date(handover.createdAt).getTime() <= selectedShift.startsAt).slice(-3).reverse(), [handovers.data, selectedShift, user?.id]);
  const acknowledge = trpc.operations.acknowledgeHandover.useMutation({ onSuccess: async result => { await handovers.refetch(); toast.success(result.alreadyAcknowledged ? "Handover already acknowledged" : "Handover acknowledged", { description: "Your incoming-shift acknowledgement is now recorded." }); }, onError: error => toast.error("Handover could not be acknowledged", { description: error.message }) });
  const createHandover = trpc.operations.createHandover.useMutation({ onSuccess: async () => { await handovers.refetch(); toast.success("Structured handover recorded", { description: dictatedText.trim() ? "Dictated text is awaiting manager review." : "The handover is ready for the next shift." }); setBriefOpen(false); setBriefFields({}); setBriefSummary(""); setBriefRisks(""); setBriefActions(""); setDictatedText(""); }, onError: error => toast.error("Handover could not be recorded", { description: error.message }) });
  const unread = notifications.data?.filter(item => !item.readAt).length ?? 0;
  const requestClock = async (eventType: "clock_in" | "clock_out") => {
    if (!activeShift || !entityId) return;
    const submit = async (coordinates?: GeolocationCoordinates, overrideReason?: string) => clock.mutateAsync({ entityId, propertyId: activeShift.propertyId, shiftId: activeShift.id, eventType, latitude: coordinates?.latitude, longitude: coordinates?.longitude, accuracyMetres: coordinates?.accuracy, overrideReason });
    try {
      if (!navigator.geolocation) throw new Error("Location is unavailable on this device");
      const coordinates = await new Promise<GeolocationCoordinates>((resolve, reject) => navigator.geolocation.getCurrentPosition(position => resolve(position.coords), reject, { enableHighAccuracy: true, timeout: 10_000 }));
      try { await submit(coordinates); } catch (error) { setPendingClock({ eventType, coordinates, message: error instanceof Error ? error.message : "Location could not be verified" }); }
    } catch (error) { setPendingClock({ eventType, message: error instanceof Error ? error.message : "Location could not be verified" }); }
  };
  const submitOverride = () => { if (!activeShift || !entityId || !pendingClock || overrideReason.trim().length < 5) return; clock.mutate({ entityId, propertyId: activeShift.propertyId, shiftId: activeShift.id, eventType: pendingClock.eventType, latitude: pendingClock.coordinates?.latitude, longitude: pendingClock.coordinates?.longitude, accuracyMetres: pendingClock.coordinates?.accuracy, overrideReason: overrideReason.trim() }); };
  const submitBrief = () => { if (!entityId || !selectedShift || briefSummary.trim().length < 10) return; createHandover.mutate({ entityId, propertyId: selectedShift.propertyId, shiftId: selectedShift.id, summary: briefSummary.trim(), risks: briefRisks.trim() || undefined, outstandingActions: briefActions.trim() || undefined, templateCode: briefTemplate, structuredBrief: Object.fromEntries(Object.entries(briefFields).filter(([, value]) => value.trim())), dictatedText: dictatedText.trim() || undefined }); };
  const reportPath = (placement: { id: number; propertyId: number | null }) => placement.propertyId ? `/key-worker?property=${placement.propertyId}&placement=${placement.id}` : "/key-worker";

  if (!entityId) return <EmptyState title="Choose an entity first" description="Key Worker records are always scoped to your authorised entity, property and placement assignments." icon={UserRoundCheck} />;
  if (context.error) return <EmptyState title="Key Worker app restricted" description="Your current role does not have access to a Key Worker workspace in this entity. No placement, shift or case detail is shown." icon={ShieldCheck} />;
  if (context.isLoading || shifts.isLoading) return <KeyWorkerSkeleton />;
  return <div className="mx-auto max-w-5xl space-y-4 pb-24"><PageHeader eyebrow="Mobile Keyworker App" title={entity ? `${entity.name} workday` : "Key Worker workday"} description="Clock in, read the previous shift handover, then complete the records for your assigned people." action={<Button variant="outline" size="sm" className="h-10 rounded-xl bg-card" onClick={() => setLocation("/search?tab=notifications")}><BellRing className="mr-2 h-4 w-4" />Alerts{unread ? ` (${unread})` : ""}</Button>} />
    <section className="surface overflow-hidden"><div className="border-b border-border/70 px-4 py-3 sm:px-5"><p className="eyebrow">1 · Attendance</p><h2 className="mt-1 text-lg font-extrabold">Clock in and out</h2>{selectedShift ? <p className="mt-1 text-xs leading-5 text-muted-foreground">{selectedShift.title} · {selectedProperty?.name ?? "Assigned property"} · {new Date(selectedShift.startsAt).toLocaleString("en-GB", { weekday: "short", day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit" })}</p> : <p className="mt-1 text-xs leading-5 text-muted-foreground">No current or upcoming assigned shift. Contact a manager if you expected one.</p>}</div>{selectedShift ? <div className="grid gap-2 p-3 sm:grid-cols-2 sm:p-4"><Button className="h-11 rounded-xl" onClick={() => requestClock("clock_in")} disabled={!activeShift || clock.isPending}><LogIn className="mr-2 h-4 w-4" />Clock in</Button><Button variant="outline" className="h-11 rounded-xl" onClick={() => requestClock("clock_out")} disabled={!activeShift || clock.isPending}><LogOut className="mr-2 h-4 w-4" />Clock out</Button>{!activeShift && <p className="sm:col-span-2 text-xs text-muted-foreground">Clocking becomes available 30 minutes before this assigned shift starts.</p>}<p className="sm:col-span-2 flex items-start gap-2 text-xs leading-5 text-muted-foreground"><MapPin className="mt-0.5 h-4 w-4 shrink-0" />Location is checked only for attendance. If it cannot be verified, record a reason for manager review instead of bypassing the check.</p></div> : <div className="p-3 text-sm text-muted-foreground">Your rota is managed by the registered manager. This frontline app will show your attendance actions when an assigned shift is due.</div>}</section>
    <KeyworkerRotaSummary shifts={myShifts} propertyNames={new Map(context.data?.properties.map(property => [property.id, property.name]) ?? [])} />
    <section className="surface overflow-hidden"><div className="border-b border-border/70 px-4 py-3 sm:px-5"><p className="eyebrow">2 · Incoming shift</p><h2 className="mt-1 text-lg font-extrabold">Previous shift handover notes</h2><p className="mt-1 text-xs leading-5 text-muted-foreground">Read and acknowledge each relevant note before starting your records. Each acknowledgement is individual to you and this shift.</p></div>{selectedShift ? previousHandovers.length ? <div className="divide-y divide-border/60">{previousHandovers.map(handover => <article key={handover.id} className="p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-extrabold">{handover.templateCode ? handover.templateCode.replaceAll("_", " ") : "Shift handover"}</p><p className="mt-1 text-xs text-muted-foreground">{handover.propertyName} · made by {handover.authorName} · {new Date(handover.createdAt).toLocaleString("en-GB", { dateStyle: "medium", timeStyle: "short" })}</p></div>{handover.acknowledgedForCurrentShiftAt ? <StatusBadge status="acknowledged" /> : <Button size="sm" className="h-9 rounded-lg" onClick={() => acknowledge.mutate({ entityId, handoverId: handover.id, shiftId: selectedShift.id })} disabled={acknowledge.isPending}><CheckCheck className="mr-1.5 h-3.5 w-3.5" />I have read this</Button>}</div><p className="mt-2 text-sm leading-6 text-muted-foreground">{handover.summary}</p>{handover.risks ? <p className="mt-2 rounded-lg bg-amber-50 px-3 py-2 text-xs text-amber-950"><span className="font-bold">Risks or escalation:</span> {handover.risks}</p> : null}{handover.outstandingActions ? <p className="mt-2 text-xs text-muted-foreground"><span className="font-bold text-foreground">Outstanding actions:</span> {handover.outstandingActions}</p> : null}</article>)}</div> : <div className="p-4"><p className="text-sm text-muted-foreground">No previous-shift handovers are waiting for this property and shift.</p></div> : <div className="p-4"><p className="text-sm text-muted-foreground">Your handovers become available once an assigned shift is due.</p></div>}</section>
    <section className="surface overflow-hidden"><div className="border-b border-border/70 px-4 py-3 sm:px-5"><p className="eyebrow">3 · Required records</p><h2 className="mt-1 text-lg font-extrabold">Reports to complete</h2><p className="mt-1 text-xs leading-5 text-muted-foreground">Choose an assigned person to open the guided report with factual prompts and optional on-device dictation.</p></div>{context.data?.placements.length ? <div className="divide-y divide-border/60">{context.data.placements.map(placement => <button key={placement.id} onClick={() => setLocation(reportPath(placement))} className="flex min-h-16 w-full items-center gap-3 px-4 py-3 text-left transition-colors hover:bg-muted/60"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-secondary text-secondary-foreground"><FileText className="h-4 w-4" /></div><div className="min-w-0 flex-1"><p className="font-extrabold">{placement.reference}</p><p className="truncate text-xs text-muted-foreground">{placement.preferredName || "Authorised placement"} · Property #{placement.propertyId}</p></div><ArrowRight className="h-4 w-4 text-muted-foreground" /></button>)}</div> : <div className="p-4"><p className="text-sm text-muted-foreground">No active placements are assigned to your account.</p></div>}</section>
    <section><div className="mb-2 flex items-end justify-between gap-3"><div><p className="eyebrow">My caseload</p><h2 className="mt-1 text-lg font-extrabold">Assigned people</h2></div><Button size="sm" variant="ghost" className="h-9 rounded-lg" onClick={() => setLocation("/key-worker")}>Open records <ArrowRight className="ml-1.5 h-3.5 w-3.5" /></Button></div>{context.data?.placements.length ? <div className="grid gap-2 sm:grid-cols-2">{context.data.placements.map(placement => <button key={placement.id} onClick={() => setLocation(reportPath(placement))} className="surface flex min-h-20 items-start gap-3 p-3 text-left hover:bg-muted/60"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-secondary text-secondary-foreground"><UserRoundCheck className="h-4 w-4" /></div><div className="min-w-0 flex-1"><p className="font-extrabold">{placement.reference}</p><p className="mt-0.5 truncate text-xs text-muted-foreground">{placement.preferredName || "Authorised placement"}</p></div><StatusBadge status={placement.status} /></button>)}</div> : <EmptyState title="No assigned placements" description="Only active placements explicitly assigned to your account appear here. A manager must create or amend the assignment." icon={UsersRound} />}</section>
    <section><p className="eyebrow">Other actions</p><h2 className="mt-1 text-lg font-extrabold">Record the next action</h2><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{[{ title: "Report incident", detail: "Record urgent operational facts", onClick: () => setLocation(context.data?.placements[0] ? `${reportPath(context.data.placements[0])}&tab=incident` : "/key-worker"), icon: AlertTriangle }, { title: "Handover for next shift", detail: "Record a structured shift brief", onClick: () => setBriefOpen(true), icon: ClipboardPenLine, disabled: !selectedShift }, { title: "Visitor log", detail: "Log arrivals and departures", onClick: () => setVisitorOpen(true), icon: UsersRound }, { title: "Curfew & welfare", detail: "Open authorised care actions", onClick: () => setLocation("/care"), icon: Clock3 }, { title: "Staff request", detail: "Leave, sickness or availability", onClick: () => setLocation("/staff"), icon: ClipboardPenLine }].map(action => <button key={action.title} onClick={action.onClick} disabled={action.disabled} className="surface flex min-h-20 items-start gap-3 p-3 text-left transition-colors hover:bg-muted/60 disabled:cursor-not-allowed disabled:opacity-60"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-secondary text-secondary-foreground"><action.icon className="h-4 w-4" /></div><div className="min-w-0 flex-1"><p className="font-extrabold">{action.title}</p><p className="mt-0.5 text-xs leading-5 text-muted-foreground">{action.detail}</p></div><ArrowRight className="mt-1 h-4 w-4 text-muted-foreground" /></button>)}</div></section>
    <VisitorLogDialog entityId={entityId} properties={context.data?.properties ?? []} open={visitorOpen} onOpenChange={setVisitorOpen} initialPropertyId={selectedShift?.propertyId} />
    <Dialog open={briefOpen} onOpenChange={open => { if (!open && !createHandover.isPending) setBriefOpen(false); }}><DialogContent className="max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>Handover for the next shift</DialogTitle><DialogDescription>Use the structured prompts for a clear incoming-shift record. Do not include unnecessary sensitive details.</DialogDescription></DialogHeader><div className="grid gap-3 py-1"><label className="grid gap-1.5 text-sm font-bold">Template<select value={briefTemplate} onChange={event => { setBriefTemplate(event.target.value as typeof briefTemplate); setBriefFields({}); }} className="h-10 rounded-xl border border-input bg-background px-3 text-sm">{templates.data?.map(template => <option key={template.code} value={template.code}>{template.label}</option>)}</select></label>{selectedTemplate?.fields.map(field => <label key={field} className="grid gap-1.5 text-sm font-bold">{field}<DictationTextarea value={briefFields[field] ?? ""} onChange={event => setBriefFields(currentFields => ({ ...currentFields, [field]: event.target.value }))} className="min-h-16 rounded-xl" placeholder={`Record ${field.toLowerCase()}.`} /></label>)}<label className="grid gap-1.5 text-sm font-bold">Handover summary<DictationTextarea value={briefSummary} onChange={event => setBriefSummary(event.target.value)} className="min-h-20 rounded-xl" placeholder="Clear summary for the incoming shift." aria-invalid={Boolean(briefSummary) && briefSummary.trim().length < 10} /></label><label className="grid gap-1.5 text-sm font-bold">Risks or escalation<DictationTextarea value={briefRisks} onChange={event => setBriefRisks(event.target.value)} className="min-h-16 rounded-xl" placeholder="Optional — necessary operational or safeguarding risks only." /></label><label className="grid gap-1.5 text-sm font-bold">Outstanding actions<DictationTextarea value={briefActions} onChange={event => setBriefActions(event.target.value)} className="min-h-16 rounded-xl" placeholder="Optional — what the incoming shift needs to do." /></label><label className="grid gap-1.5 text-sm font-bold">Dictated text for manager review<DictationTextarea value={dictatedText} onChange={event => setDictatedText(event.target.value)} className="min-h-20 rounded-xl" placeholder="Optional reviewed transcript. It will be marked pending independent manager review." /></label></div><DialogFooter><Button variant="outline" onClick={() => setBriefOpen(false)} disabled={createHandover.isPending}>Cancel</Button><Button onClick={submitBrief} disabled={createHandover.isPending || briefSummary.trim().length < 10}>Record handover</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={Boolean(pendingClock)} onOpenChange={open => { if (!open && !clock.isPending) { setPendingClock(null); setOverrideReason(""); } }}><DialogContent><DialogHeader><DialogTitle>Attendance exception</DialogTitle><DialogDescription>{pendingClock?.message ?? "Location could not be verified."} You may continue only by recording a clear reason for manager review.</DialogDescription></DialogHeader><div className="grid gap-2 py-3"><Label htmlFor="attendance-exception">Reason</Label><DictationTextarea id="attendance-exception" value={overrideReason} onChange={event => setOverrideReason(event.target.value)} placeholder="Explain why location could not be verified or why an off-site record is required." className="min-h-24 rounded-xl" aria-invalid={Boolean(overrideReason) && overrideReason.trim().length < 5} /><p className="text-xs text-muted-foreground">At least five characters are required. This exception is recorded with the attendance event.</p></div><DialogFooter><Button variant="outline" onClick={() => setPendingClock(null)} disabled={clock.isPending}>Cancel</Button><Button onClick={submitOverride} disabled={clock.isPending || overrideReason.trim().length < 5}>Record exception</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}

function KeyWorkerSkeleton() { return <div className="mx-auto max-w-5xl space-y-4 pb-24" aria-label="Loading Key Worker app"><Skeleton className="h-24 rounded-2xl" /><Skeleton className="h-44 rounded-2xl" /><div className="grid gap-2 sm:grid-cols-2">{Array.from({ length: 4 }).map((_, index) => <Skeleton key={index} className="h-20 rounded-2xl" />)}</div></div>; }
