import { EmptyState, PageHeader, StatusBadge } from "@/components/app/Primitives";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import { Skeleton } from "@/components/ui/skeleton";
import { Textarea } from "@/components/ui/textarea";
import { useAuth } from "@/_core/hooks/useAuth";
import { useWorkspace } from "@/contexts/WorkspaceContext";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, ArrowRight, BellRing, ClipboardPenLine, Clock3, FileText, LogIn, LogOut, MapPin, ShieldCheck, UsersRound, UserRoundCheck } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";
import { useLocation } from "wouter";

type PendingClock = { eventType: "clock_in" | "clock_out"; coordinates?: GeolocationCoordinates; message: string } | null;

export default function KeyWorkerApp() {
  const { entityId, entity } = useWorkspace(); const { user } = useAuth(); const [, setLocation] = useLocation();
  const context = trpc.keywork.context.useQuery({ entityId: entityId! }, { enabled: Boolean(entityId), retry: false });
  const shifts = trpc.operations.shifts.useQuery({ entityId: entityId! }, { enabled: Boolean(entityId), retry: false });
  const notifications = trpc.workspace.notifications.useQuery();
  const [pendingClock, setPendingClock] = useState<PendingClock>(null); const [overrideReason, setOverrideReason] = useState("");
  const clock = trpc.operations.clock.useMutation({ onSuccess: result => { toast.success("Attendance recorded", { description: result.locationState.replaceAll("_", " ") }); setPendingClock(null); setOverrideReason(""); }, onError: error => toast.error("Attendance could not be recorded", { description: error.message }) });
  const myShifts = useMemo(() => (shifts.data ?? []).filter(shift => shift.assignedUserId === user?.id && shift.status !== "cancelled").sort((a, b) => a.startsAt - b.startsAt), [shifts.data, user?.id]);
  const current = useMemo(() => { const now = Date.now(); return myShifts.find(shift => shift.startsAt <= now && shift.endsAt >= now) ?? myShifts.find(shift => shift.startsAt >= now) ?? null; }, [myShifts]);
  const unread = notifications.data?.filter(item => !item.readAt).length ?? 0;
  const requestClock = async (eventType: "clock_in" | "clock_out") => {
    if (!current || !entityId) return;
    const submit = async (coordinates?: GeolocationCoordinates, overrideReason?: string) => clock.mutateAsync({ entityId, propertyId: current.propertyId, shiftId: current.id, eventType, latitude: coordinates?.latitude, longitude: coordinates?.longitude, accuracyMetres: coordinates?.accuracy, overrideReason });
    try {
      if (!navigator.geolocation) throw new Error("Location is unavailable on this device");
      const coordinates = await new Promise<GeolocationCoordinates>((resolve, reject) => navigator.geolocation.getCurrentPosition(position => resolve(position.coords), reject, { enableHighAccuracy: true, timeout: 10_000 }));
      try { await submit(coordinates); } catch (error) { setPendingClock({ eventType, coordinates, message: error instanceof Error ? error.message : "Location could not be verified" }); }
    } catch (error) { setPendingClock({ eventType, message: error instanceof Error ? error.message : "Location could not be verified" }); }
  };
  const submitOverride = () => { if (!current || !entityId || !pendingClock) return; if (overrideReason.trim().length < 5) return; clock.mutate({ entityId, propertyId: current.propertyId, shiftId: current.id, eventType: pendingClock.eventType, latitude: pendingClock.coordinates?.latitude, longitude: pendingClock.coordinates?.longitude, accuracyMetres: pendingClock.coordinates?.accuracy, overrideReason: overrideReason.trim() }); };
  if (!entityId) return <EmptyState title="Choose an entity first" description="Key Worker records are always scoped to your authorised entity, property and placement assignments." icon={UserRoundCheck} />;
  if (context.error) return <EmptyState title="Key Worker app restricted" description="Your current role does not have access to a Key Worker workspace in this entity. No placement, shift or case detail is shown." icon={ShieldCheck} />;
  if (context.isLoading || shifts.isLoading) return <KeyWorkerSkeleton />;
  return <div className="mx-auto max-w-5xl pb-28"><PageHeader eyebrow="Mobile key worker app" title={entity ? `${entity.name} workday` : "Key Worker workday"} description="Your authorised shifts, people and record actions in one mobile-first workspace." action={<Button variant="outline" className="rounded-xl bg-card" onClick={() => setLocation("/search?tab=notifications")}><BellRing className="mr-2 h-4 w-4" />Alerts{unread ? ` (${unread})` : ""}</Button>} />
    <section className="surface overflow-hidden"><div className="border-b border-border/70 p-5 sm:p-6"><p className="eyebrow">My shift</p><h2 className="mt-1 text-xl font-extrabold">{current ? current.title : "No current or upcoming assigned shift"}</h2>{current ? <p className="mt-2 text-sm text-muted-foreground">Property #{current.propertyId} · {new Date(current.startsAt).toLocaleString("en-GB", { weekday: "short", day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit" })} – {new Date(current.endsAt).toLocaleTimeString("en-GB", { hour: "2-digit", minute: "2-digit" })}</p> : <p className="thin-copy mt-2">Your rota only shows work assigned to your account. Contact a manager about missing or incorrect shifts.</p>}</div>{current ? <div className="grid gap-3 p-4 sm:grid-cols-2 sm:p-5"><Button className="h-12 rounded-xl" onClick={() => requestClock("clock_in")} disabled={clock.isPending}><LogIn className="mr-2 h-4 w-4" />Clock in</Button><Button variant="outline" className="h-12 rounded-xl" onClick={() => requestClock("clock_out")} disabled={clock.isPending}><LogOut className="mr-2 h-4 w-4" />Clock out</Button><p className="sm:col-span-2 flex items-start gap-2 text-xs leading-5 text-muted-foreground"><MapPin className="mt-0.5 h-4 w-4 shrink-0" />Location is used only when recording attendance. If it cannot be verified, you can submit a reason for manager review instead of silently bypassing the check.</p></div> : <div className="p-5"><Button variant="outline" className="w-full rounded-xl" onClick={() => setLocation("/rota")}>Open my rota <ArrowRight className="ml-2 h-4 w-4" /></Button></div>}</section>
    <section className="mt-5"><div className="mb-3 flex items-end justify-between gap-4"><div><p className="eyebrow">My caseload</p><h2 className="mt-1 text-xl font-extrabold">Assigned people</h2></div><Button size="sm" variant="ghost" onClick={() => setLocation("/key-worker")}>Record view <ArrowRight className="ml-2 h-4 w-4" /></Button></div>{context.data?.placements.length ? <div className="grid gap-3 sm:grid-cols-2">{context.data.placements.map(placement => <button key={placement.id} onClick={() => setLocation("/key-worker")} className="surface flex min-h-28 items-start gap-4 p-5 text-left hover:bg-muted/60"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-2xl bg-secondary text-secondary-foreground"><UserRoundCheck className="h-5 w-5" /></div><div className="min-w-0 flex-1"><p className="font-extrabold">{placement.reference}</p><p className="mt-1 truncate text-sm text-muted-foreground">{placement.preferredName || "Authorised placement"}</p><p className="mt-2 text-xs text-muted-foreground">Property #{placement.propertyId}</p></div><StatusBadge status={placement.status} /></button>)}</div> : <EmptyState title="No assigned placements" description="Only active placements explicitly assigned to your account appear here. A manager must create or amend the assignment." icon={UsersRound} />}</section>
    <section className="mt-5"><p className="eyebrow">Quick actions</p><h2 className="mt-1 text-xl font-extrabold">Record the next action</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{[{ title: "Write report", detail: "Daily, weekly or monthly report", path: "/key-worker", icon: FileText }, { title: "Report incident", detail: "Record urgent operational facts", path: "/key-worker", icon: AlertTriangle }, { title: "Handover", detail: "Review or record a structured handover", path: "/rota", icon: ClipboardPenLine }, { title: "Visitor & property", detail: "Access the guarded property log", path: "/properties", icon: UsersRound }, { title: "Curfew & welfare", detail: "Open authorised care actions", path: "/care", icon: Clock3 }, { title: "Staff request", detail: "Leave, sickness, availability or details", path: "/staff", icon: ClipboardPenLine }].map(action => <button key={action.title} onClick={() => setLocation(action.path)} className="surface flex min-h-28 items-start gap-4 p-5 text-left transition-colors hover:bg-muted/60"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-2xl bg-secondary text-secondary-foreground"><action.icon className="h-5 w-5" /></div><div className="min-w-0 flex-1"><p className="font-extrabold">{action.title}</p><p className="mt-2 text-xs leading-5 text-muted-foreground">{action.detail}</p></div><ArrowRight className="mt-1 h-4 w-4 text-muted-foreground" /></button>)}</div></section>
    <Dialog open={Boolean(pendingClock)} onOpenChange={open => { if (!open && !clock.isPending) { setPendingClock(null); setOverrideReason(""); } }}><DialogContent><DialogHeader><DialogTitle>Attendance exception</DialogTitle><DialogDescription>{pendingClock?.message ?? "Location could not be verified."} You may continue only by recording a clear reason for manager review.</DialogDescription></DialogHeader><div className="grid gap-2 py-3"><Label htmlFor="attendance-exception">Reason</Label><Textarea id="attendance-exception" value={overrideReason} onChange={event => setOverrideReason(event.target.value)} placeholder="Explain why location could not be verified or why an off-site record is required." className="min-h-28 rounded-xl" aria-invalid={Boolean(overrideReason) && overrideReason.trim().length < 5} /><p className="text-xs text-muted-foreground">At least five characters are required. This exception is recorded with the attendance event.</p></div><DialogFooter><Button variant="outline" onClick={() => setPendingClock(null)} disabled={clock.isPending}>Cancel</Button><Button onClick={submitOverride} disabled={clock.isPending || overrideReason.trim().length < 5}>Record exception</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}
function KeyWorkerSkeleton() { return <div className="mx-auto max-w-5xl space-y-5 pb-28" aria-label="Loading Key Worker app"><Skeleton className="h-28 rounded-3xl" /><Skeleton className="h-52 rounded-3xl" /><div className="grid gap-3 sm:grid-cols-2">{Array.from({ length: 4 }).map((_, index) => <Skeleton key={index} className="h-28 rounded-2xl" />)}</div></div>; }
