import { EmptyState, PageHeader, StatusBadge } from "@/components/app/Primitives";
import { VisitorLogDialog } from "@/components/VisitorLogDialog";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Skeleton } from "@/components/ui/skeleton";
import { DictationTextarea } from "@/components/DictationFields";
import { useWorkspace } from "@/contexts/WorkspaceContext";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, ArrowRight, CalendarClock, ClipboardCheck, FileWarning, ShieldCheck, UsersRound, Wrench } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";
import { useLocation } from "wouter";

type Queue = { staffRequests: any[]; incidents: any[]; reports: any[]; propertyChecks: any[]; medicationDiscrepancies: any[]; financeDiscrepancies: any[]; safeguardingConcerns: any[]; investigations: any[] };

function count(queue: Partial<Queue> | undefined, key: keyof Queue) { return queue?.[key]?.length ?? 0; }

export default function ManagerApp() {
  const { entityId, entity } = useWorkspace();
  const [location, setLocation] = useLocation();
  const queue = trpc.staffWorkspace.managerQueue.useQuery({ entityId: entityId! }, { enabled: Boolean(entityId), retry: false });
  const context = trpc.staffWorkspace.context.useQuery({ entityId: entityId! }, { enabled: Boolean(entityId), retry: false });
  const shifts = trpc.operations.shifts.useQuery({ entityId: entityId! }, { enabled: Boolean(entityId), retry: false });
  const notifications = trpc.workspace.notifications.useQuery();
  const [reportPeriod] = useState(() => ({ from: Date.now() - 7 * 86_400_000, to: Date.now() }));
  const reportCompletion = trpc.keywork.reportCompletion.useQuery({ entityId: entityId!, ...reportPeriod }, { enabled: Boolean(entityId), retry: false });
  const utils = trpc.useUtils();
  const [returningReport, setReturningReport] = useState<any | null>(null);
  const [returnReason, setReturnReason] = useState("");
  const [visitorOpen, setVisitorOpen] = useState(false);
  const reviewReport = trpc.staffWorkspace.reviewReport.useMutation({
    onSuccess: async () => { await utils.staffWorkspace.managerQueue.invalidate(); toast.success("Report decision recorded"); setReturningReport(null); setReturnReason(""); },
    onError: error => toast.error("Report decision could not be recorded", { description: error.message }),
  });
  const approveReport = (report: any) => { if (!entityId) return; reviewReport.mutate({ entityId, reportId: report.id, decision: "approved", expectedVersion: report.version }); };
  const returnReport = () => { if (!entityId || !returningReport || returnReason.trim().length < 10) return; reviewReport.mutate({ entityId, reportId: returningReport.id, decision: "returned", notes: returnReason.trim(), expectedVersion: returningReport.version }); };
  const live = useMemo(() => {
    const now = Date.now(); const items = shifts.data ?? [];
    return {
      active: items.filter(item => item.status !== "cancelled" && item.startsAt <= now && item.endsAt >= now),
      uncovered: items.filter(item => item.status !== "cancelled" && (item.coverageState === "uncovered" || !item.assignedUserId)),
      atRisk: items.filter(item => item.status !== "cancelled" && item.coverageState === "at_risk"),
    };
  }, [shifts.data]);
  useEffect(() => {
    if (new URLSearchParams(window.location.search).get("section") !== "reports" || queue.isLoading || shifts.isLoading) return;
    const target = document.getElementById("submitted-reports");
    target?.scrollIntoView({ behavior: "smooth", block: "start" });
    target?.focus({ preventScroll: true });
  }, [location, queue.isLoading, shifts.isLoading]);

  if (!entityId) return <EmptyState title="Create an entity first" description="Manager oversight is scoped to an authorised legal entity, property and operational role." icon={UsersRound} />;
  if (queue.error) return <EmptyState title="Manager app restricted" description="This operational inbox is available only to authorised owners and registered managers. No team or resident details are shown without that access." icon={ShieldCheck} />;
  if (queue.isLoading || shifts.isLoading) return <ManagerSkeleton />;
  const urgent = count(queue.data, "incidents") + count(queue.data, "safeguardingConcerns") + count(queue.data, "medicationDiscrepancies") + count(queue.data, "financeDiscrepancies");
  const tasks = [
    { title: "Staff requests", count: count(queue.data, "staffRequests"), detail: "Leave, sickness, availability and profile changes awaiting a decision.", path: "/workforce", icon: UsersRound, tone: "blue" },
    { title: "Reports to review", count: count(queue.data, "reports"), detail: "Submitted key-worker reports awaiting manager review.", path: "/manager-app?section=reports", icon: ClipboardCheck, tone: "green" },
    { title: "Incidents & concerns", count: urgent, detail: "Open incidents, safeguarding concerns and discrepancies requiring attention.", path: "/safeguarding", icon: AlertTriangle, tone: "red" },
    { title: "Property actions", count: count(queue.data, "propertyChecks"), detail: "Submitted checks and operational issues that need a response.", path: "/properties", icon: Wrench, tone: "amber" },
  ];
  return <div className="mx-auto max-w-6xl pb-28"><PageHeader eyebrow="Mobile manager app" title={entity ? `${entity.name} command view` : "Manager command view"} description="Act on current staffing, requests, reports and operational exceptions without creating a second source of truth." action={<Button className="rounded-xl" onClick={() => setLocation("/search?tab=notifications")}>Notifications {notifications.data?.filter(item => !item.readAt).length ? `(${notifications.data.filter(item => !item.readAt).length})` : ""}</Button>} />
    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4" aria-label="Manager operational summary">
      <SummaryCard label="On duty now" value={live.active.length} note="Scheduled active shifts" icon={UsersRound} onClick={() => setLocation("/rota")} />
      <SummaryCard label="Coverage gaps" value={live.uncovered.length} note="Open or uncovered shifts" icon={CalendarClock} tone="amber" onClick={() => setLocation("/rota")} />
      <SummaryCard label="At-risk shifts" value={live.atRisk.length} note="Rest, role or coverage warning" icon={FileWarning} tone="amber" onClick={() => setLocation("/rota")} />
      <SummaryCard label="Urgent review" value={urgent} note="Incidents and restricted concerns" icon={AlertTriangle} tone="red" onClick={() => setLocation("/search?tab=notifications")} />
    </section>
    <section className="mt-5 surface overflow-hidden"><div className="flex items-center justify-between gap-4 border-b border-border/70 p-5"><div><p className="eyebrow">Manager inbox</p><h2 className="mt-1 text-xl font-extrabold">Review and exception queue</h2></div><Button variant="outline" size="sm" onClick={() => setLocation("/rota")}>Open rota <ArrowRight className="ml-2 h-4 w-4" /></Button></div><div className="grid divide-y divide-border/60 sm:grid-cols-2 sm:divide-x sm:divide-y-0">{tasks.map(item => <button key={item.title} onClick={() => setLocation(item.path)} className="flex min-h-32 items-start gap-4 p-5 text-left transition-colors hover:bg-muted/60"><div className={`grid h-11 w-11 shrink-0 place-items-center rounded-2xl ${item.tone === "red" ? "bg-red-100 text-red-800" : item.tone === "amber" ? "bg-amber-100 text-amber-900" : item.tone === "green" ? "bg-emerald-100 text-emerald-800" : "bg-secondary text-secondary-foreground"}`}><item.icon className="h-5 w-5" /></div><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-3"><p className="font-extrabold">{item.title}</p><span className="rounded-full bg-muted px-2.5 py-1 text-sm font-extrabold">{item.count}</span></div><p className="mt-2 text-xs leading-5 text-muted-foreground">{item.detail}</p></div><ArrowRight className="mt-1 h-4 w-4 text-muted-foreground" /></button>)}</div></section>
    <section className="mt-5 grid gap-5 lg:grid-cols-[1.2fr_0.8fr]"><div className="surface p-5 sm:p-6"><p className="eyebrow">Live staffing</p><h2 className="mt-1 text-xl font-extrabold">Current shift coverage</h2>{live.active.length ? <div className="mt-4 space-y-2">{live.active.slice(0, 6).map(shift => <article key={shift.id} className="operational-row rounded-xl bg-muted"><div className="min-w-0 flex-1"><p className="truncate text-sm font-extrabold">{shift.title}</p><p className="mt-0.5 text-xs text-muted-foreground">Property #{shift.propertyId} · ends {new Date(shift.endsAt).toLocaleTimeString("en-GB", { hour: "2-digit", minute: "2-digit" })}</p></div><StatusBadge status={shift.coverageState} /></article>)}</div> : <p className="thin-copy mt-5">No scheduled shifts are currently active. Open the rota to check upcoming coverage and acknowledgements.</p>}<Button variant="outline" className="mt-5 w-full rounded-xl" onClick={() => setLocation("/rota")}>View rota and time exceptions</Button></div><aside className="surface p-5 sm:p-6"><p className="eyebrow">Manager actions</p><h2 className="mt-1 text-xl font-extrabold">Open the right record</h2><div className="mt-5 grid gap-2">{[{ label: "Compliance dashboard", onClick: () => setLocation("/compliance-dashboard") }, { label: "Work plans", onClick: () => setLocation("/work-plans") }, { label: "Visitor log", onClick: () => setVisitorOpen(true) }, { label: "Quality reviews", onClick: () => setLocation("/quality-reviews") }].map(action => <Button key={action.label} variant="outline" className="h-11 justify-between rounded-xl" onClick={action.onClick}>{action.label}<ArrowRight className="h-4 w-4" /></Button>)}</div><p className="mt-5 text-xs leading-5 text-muted-foreground">Manager review and restricted-data decisions remain server-authorised.</p></aside></section>
    <section className="surface mt-5 overflow-hidden"><div className="flex items-center justify-between gap-3 border-b border-border/70 px-4 py-3 sm:px-5"><div><p className="eyebrow">Report completion</p><h2 className="mt-1 text-xl font-extrabold">By Key Worker and property</h2><p className="mt-1 text-xs text-muted-foreground">Last seven days · status is based on records actually submitted or saved.</p></div><Button variant="outline" size="sm" className="h-9 rounded-lg" onClick={() => setLocation("/key-worker")}>Open reports <ArrowRight className="ml-1.5 h-3.5 w-3.5" /></Button></div>{reportCompletion.data?.properties.length ? <div className="divide-y divide-border/60">{reportCompletion.data.properties.map(property => <button key={property.propertyId} onClick={() => setLocation("/key-worker")} className="operational-row operational-row-action"><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-3"><p className="truncate text-sm font-extrabold">{property.propertyName}</p><span className="shrink-0 rounded-full bg-muted px-2 py-1 text-xs font-extrabold">{property.counts.logged} logged</span></div><p className="mt-0.5 truncate text-xs text-muted-foreground">{property.keyWorkers.map(worker => `${worker.name}: ${worker.counts.logged} logged${worker.counts.needsCompletion ? `, ${worker.counts.needsCompletion} to amend` : ""}`).join(" · ")}</p></div><ArrowRight className="h-4 w-4 shrink-0 text-muted-foreground" /></button>)}</div> : <div className="p-4"><p className="text-sm text-muted-foreground">No report records were created in the last seven days for the selected entity.</p></div>}</section>
    <section id="submitted-reports" className="surface mt-5 scroll-mt-20 overflow-hidden" tabIndex={-1}><div className="border-b border-border/70 p-5"><p className="eyebrow">Submitted reports</p><h2 className="mt-1 text-xl font-extrabold">Approve or return</h2><p className="mt-2 text-sm text-muted-foreground">Each decision is recorded with the manager, timestamp and any return reason. You cannot review your own report.</p></div>{queue.data?.reports.length ? <div className="divide-y divide-border/60">{queue.data.reports.map(report => <article key={report.id} className="p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2"><p className="font-extrabold">{report.reportType.replaceAll("_", " ")} report #{report.id}</p><StatusBadge status={report.status} /></div><p className="mt-1 text-xs text-muted-foreground">Report date {new Date(report.reportDate).toLocaleDateString("en-GB")} · property #{report.propertyId}</p><p className="mt-2 text-xs text-muted-foreground">Review audit: {report.reviewedAt ? `reviewed ${new Date(report.reviewedAt).toLocaleString("en-GB")}` : "awaiting a manager decision"}{report.approvedAt ? ` · approved ${new Date(report.approvedAt).toLocaleString("en-GB")}` : ""}</p></div><div className="flex gap-2"><Button size="sm" className="rounded-xl" disabled={reviewReport.isPending} onClick={() => approveReport(report)}>Approve</Button><Button size="sm" variant="outline" className="rounded-xl" disabled={reviewReport.isPending} onClick={() => { setReturningReport(report); setReturnReason(""); }}>Return</Button></div></div></article>)}</div> : <div className="p-5"><p className="thin-copy">No submitted key-worker reports are awaiting manager action.</p></div>}</section>
    <VisitorLogDialog entityId={entityId} properties={context.data?.properties ?? []} open={visitorOpen} onOpenChange={setVisitorOpen} />
    <Dialog open={Boolean(returningReport)} onOpenChange={open => { if (!open && !reviewReport.isPending) { setReturningReport(null); setReturnReason(""); } }}><DialogContent><DialogHeader><DialogTitle>Return report for amendment</DialogTitle><DialogDescription>Add a clear, constructive reason. The author will see this in the protected report review record.</DialogDescription></DialogHeader><DictationTextarea value={returnReason} onChange={event => setReturnReason(event.target.value)} className="min-h-32 rounded-xl" placeholder="Explain what needs to be corrected or completed." aria-invalid={Boolean(returnReason) && returnReason.trim().length < 10} /><p className="text-xs text-muted-foreground">At least 10 characters are required. This reason is encrypted and audit recorded.</p><DialogFooter><Button variant="outline" onClick={() => setReturningReport(null)} disabled={reviewReport.isPending}>Cancel</Button><Button onClick={returnReport} disabled={reviewReport.isPending || returnReason.trim().length < 10}>Return report</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}

function SummaryCard({ label, value, note, icon: Icon, tone = "blue", onClick }: { label: string; value: number; note: string; icon: typeof UsersRound; tone?: "blue" | "amber" | "red"; onClick: () => void }) { return <button type="button" onClick={onClick} className={`surface group flex min-h-[5.5rem] w-full items-center gap-3 p-3.5 text-left hover:bg-muted/60 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring sm:min-h-24 sm:p-4 ${tone === "red" ? "border border-red-200" : tone === "amber" ? "border border-amber-200" : ""}`} aria-label={`Open ${label}`}><div className={`grid h-10 w-10 shrink-0 place-items-center rounded-xl ${tone === "red" ? "bg-red-100 text-red-700" : tone === "amber" ? "bg-amber-100 text-amber-800" : "bg-secondary text-primary"}`}><Icon className="h-4 w-4" /></div><div className="min-w-0 flex-1"><div className="flex items-baseline justify-between gap-3"><p className="truncate text-sm font-extrabold">{label}</p><p className="shrink-0 text-2xl font-extrabold tracking-[-0.05em]">{value}</p></div><p className="mt-0.5 truncate text-xs leading-5 text-muted-foreground">{note}</p></div><ArrowRight className="h-4 w-4 shrink-0 text-muted-foreground transition-transform group-hover:translate-x-1" aria-hidden="true" /></button>; }
function ManagerSkeleton() { return <div className="mx-auto max-w-6xl space-y-5 pb-28" aria-label="Loading manager app"><Skeleton className="h-28 rounded-3xl" /><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{Array.from({ length: 4 }).map((_, index) => <Skeleton key={index} className="h-36 rounded-2xl" />)}</div><Skeleton className="h-72 rounded-3xl" /></div>; }
