import {EmptyState,PageHeader,StatusBadge} from "@/components/app/Primitives";
import {Button} from "@/components/ui/button";
import {Dialog,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle,DialogTrigger} from "@/components/ui/dialog";
import {Input} from "@/components/ui/input";
import {Label} from "@/components/ui/label";
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from "@/components/ui/select";
import {Textarea} from "@/components/ui/textarea";
import {useWorkspace} from "@/contexts/WorkspaceContext";
import {trpc} from "@/lib/trpc";
import {BellRing,Plus,ShieldCheck} from "lucide-react";
import {useState} from "react";
import {toast} from "sonner";
export default function Regulation28(){const{entityId}=useWorkspace();const query=trpc.regulation28.workspace.useQuery({entityId:entityId!},{enabled:Boolean(entityId)});if(!entityId)return <EmptyState icon={BellRing} title="Create an entity first" description="Admission and discharge notification decisions require an accountable entity."/>;return <div className="space-y-6"><PageHeader eyebrow="Regulation 28" title="Admission and discharge notifications" description="Record recipient logic, exemption reasons, encrypted facts, deadlines and submission evidence without sending anything automatically." action={<CreateDialog entityId={entityId} placements={query.data?.placements??[]}/>}/>{query.isLoading?<div className="surface h-64 animate-pulse"/>:query.error?<EmptyState icon={ShieldCheck} title="Notification access restricted" description={query.error.message}/>:!query.data?.notifications.length?<EmptyState icon={BellRing} title="No notification decisions" description="Create an admission or discharge record from an assigned placement."/>:<div className="grid gap-4">{query.data.notifications.map(item=><NotificationRow key={item.id} entityId={entityId} item={item} authorities={query.data!.authorities}/>)}</div>}</div>;}
function NotificationRow({entityId,item,authorities}:{entityId:number;item:any;authorities:any[]}){const utils=trpc.useUtils();const[open,setOpen]=useState(false);const[decision,setDecision]=useState("notify_host_authority");const[authority,setAuthority]=useState("none");const[reason,setReason]=useState("");const[facts,setFacts]=useState("");const decide=trpc.regulation28.recordDecision.useMutation({onSuccess:()=>{setOpen(false);toast.success("Regulation 28 decision recorded.");utils.regulation28.workspace.invalidate();},onError:error=>toast.error(error.message)});const submit=trpc.regulation28.submit.useMutation({onSuccess:()=>{toast.success("Submission evidence recorded.");utils.regulation28.workspace.invalidate();},onError:error=>toast.error(error.message)});return <section className="surface p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="eyebrow">{item.notificationType} · placement {item.placementId}</p><h2 className="mt-2 text-xl font-extrabold">Decision due {new Date(item.dueAt).toLocaleString("en-GB")}</h2><p className="mt-1 text-xs text-muted-foreground">{item.decision.replaceAll("_"," ")}{item.recipientEmail?` · ${item.recipientEmail}`:""}</p></div><StatusBadge status={item.status}/></div><div className="mt-4 flex flex-wrap gap-2">{item.status==="draft"&&<Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button size="sm">Record decision</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Notification routing decision</DialogTitle><DialogDescription>Record the statutory recipient logic and encrypted minimum facts. No external message is sent.</DialogDescription></DialogHeader><Choice label="Decision" value={decision} onChange={setDecision} options={["notify_host_authority","same_authority_exempt","not_required"]}/><Choice label="Host authority" value={authority} onChange={setAuthority} options={["none",...authorities.map(value=>String(value.id))]} labels={Object.fromEntries(authorities.map(value=>[String(value.id),value.name]))}/><Field label="Decision reason"><Textarea value={reason} onChange={event=>setReason(event.target.value)}/></Field><Field label="Minimum facts snapshot"><Textarea value={facts} onChange={event=>setFacts(event.target.value)}/></Field><DialogFooter><Button onClick={()=>decide.mutate({entityId,notificationId:item.id,decision:decision as any,decisionReason:reason,hostAuthorityId:authority==="none"?undefined:Number(authority),factsSnapshot:facts})} disabled={reason.length<10||facts.length<20}>Record decision</Button></DialogFooter></DialogContent></Dialog>}{["decision_recorded","pack_ready"].includes(item.status)&&<Button size="sm" variant="outline" onClick={()=>submit.mutate({entityId,notificationId:item.id,submissionMethod:"portal",submissionReference:`Recorded ${new Date().toISOString()}`})}>Record submission</Button>}</div></section>;}
function CreateDialog({entityId,placements}:{entityId:number;placements:any[]}){const[open,setOpen]=useState(false);const[placementId,setPlacementId]=useState("");const[type,setType]=useState("admission");const[destination,setDestination]=useState("supported_accommodation");const[reason,setReason]=useState("planned_transition");const utils=trpc.useUtils();const mutation=trpc.regulation28.create.useMutation({onSuccess:()=>{setOpen(false);toast.success("Notification decision record created with a 24-hour target.");utils.regulation28.workspace.invalidate();},onError:error=>toast.error(error.message)});return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button className="rounded-xl"><Plus className="mr-2 h-4 w-4"/>New decision</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>New admission or discharge decision</DialogTitle><DialogDescription>Placement, property and placing-authority facts are reused from the current record.</DialogDescription></DialogHeader><Field label="Assigned placement"><Select value={placementId} onValueChange={setPlacementId}><SelectTrigger><SelectValue placeholder="Choose placement"/></SelectTrigger><SelectContent>{placements.map(item=><SelectItem key={item.id} value={String(item.id)}>{item.reference} · {item.propertyName??"No property"}</SelectItem>)}</SelectContent></Select></Field><Choice label="Notification type" value={type} onChange={setType} options={["admission","discharge"]}/>{type==="discharge"&&<><Choice label="Destination" value={destination} onChange={setDestination} options={["family","independent_living","supported_accommodation","semi_independent","custody","hospital","homeless","unknown","other"]}/><Choice label="Discharge reason" value={reason} onChange={setReason} options={["planned_transition","placement_end","safeguarding","placement_breakdown","custody","hospital","young_person_choice","other"]}/></>}<DialogFooter><Button onClick={()=>mutation.mutate({entityId,placementId:Number(placementId),notificationType:type as any,eventAt:Date.now(),dischargeDestinationType:type==="discharge"?destination as any:undefined,dischargeReason:type==="discharge"?reason as any:undefined})} disabled={!placementId}>Create record</Button></DialogFooter></DialogContent></Dialog>;}
function Choice({label,value,onChange,options,labels={}}:{label:string;value:string;onChange:(value:string)=>void;options:string[];labels?:Record<string,string>}){return <Field label={label}><Select value={value} onValueChange={onChange}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{options.map(option=><SelectItem key={option} value={option}>{labels[option]??option.replaceAll("_"," ")}</SelectItem>)}</SelectContent></Select></Field>;}
function Field({label,children}:{label:string;children:any}){return <div className="grid gap-2"><Label>{label}</Label>{children}</div>;}
