import { EmptyState, PageHeader, StatusBadge } from "@/components/app/Primitives";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Progress } from "@/components/ui/progress";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { useWorkspace } from "@/contexts/WorkspaceContext";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, CheckCheck, FileCheck2, History, Link2, ListTodo, Loader2, Plus, ShieldCheck, UserRound } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

type Action = {
  id: number; title: string; description: string | null; sourceType: string | null; sourceId: number | null;
  dueAt: number; ownerUserId: number | null; status: string; progressPercent: number; completionNotes: string | null; evidenceDocumentId: number | null;
  reviewOutcome: string | null; reviewNotes: string | null; dependencies: number[];
};

export default function WorkPlansPage() {
  const { entityId } = useWorkspace();
  const query = trpc.compliance.workPlans.useQuery({ entityId: entityId! }, { enabled: Boolean(entityId), retry: false });
  const members = trpc.entities.members.useQuery({ entityId: entityId! }, { enabled: Boolean(entityId), retry: false });
  return <div className="mx-auto max-w-[1480px] pb-20"><PageHeader eyebrow="Improvement" title="Operational work plans" description="Every action retains its source, dependencies, accountable owner, target date, evidence and independent review history." action={entityId ? <CreateActionDialog entityId={entityId} members={members.data ?? []} /> : null} />
    {!entityId ? <EmptyState title="Create an entity first" description="Work plans need an accountable organisation and owner." icon={ListTodo} /> : query.error ? <EmptyState title="Work-plan access is restricted" description={query.error.message} icon={ShieldCheck} /> : query.isLoading ? <div className="thin-copy">Loading work plans…</div> : !query.data?.length ? <EmptyState title="No work-plan actions" description="Create an action directly or let property, compliance and incident workflows generate one with a source link." actionLabel="Create action" onAction={() => document.getElementById("create-action-trigger")?.click()} icon={ListTodo} /> : <div className="grid gap-4 lg:grid-cols-2">{query.data.map(item => <ActionCard key={item.id} entityId={entityId} item={item as Action} actions={query.data as Action[]} members={members.data ?? []} />)}</div>}
  </div>;
}

function ActionCard({ entityId, item, actions, members }: { entityId: number; item: Action; actions: Action[]; members: any[] }) {
  const utils = trpc.useUtils();
  const update = trpc.compliance.updateWorkPlan.useMutation({ onSuccess: async () => { await utils.compliance.workPlans.invalidate(); toast.success("Action updated"); }, onError: error => toast.error(error.message) });
  const prerequisites = item.dependencies.map(id => actions.find(action => action.id === id)).filter(Boolean) as Action[];
  return <article className="surface p-5"><div className="flex items-start justify-between gap-4"><div><p className="eyebrow capitalize">{item.sourceType?.replaceAll("_", " ") || "Manual action"}{item.sourceId ? ` #${item.sourceId}` : ""}</p><h2 className="mt-2 text-lg font-extrabold tracking-[-0.035em]">{item.title}</h2></div><StatusBadge status={item.status} /></div>
    {item.description && <p className="thin-copy mt-3">{item.description}</p>}
    {item.dueAt < Date.now() && item.status !== "complete" && <div className="mt-4 flex gap-2 rounded-xl bg-red-50 p-3 text-xs leading-5 text-red-950"><AlertTriangle className="mt-0.5 h-4 w-4 shrink-0" />Overdue actions are escalated through the configured work-plan route until acknowledged or completed.</div>}
    {prerequisites.length > 0 && <div className="mt-4 rounded-xl bg-muted p-3"><p className="text-[0.65rem] font-bold uppercase tracking-wider text-muted-foreground">Prerequisites</p><div className="mt-2 flex flex-wrap gap-2">{prerequisites.map(action => <span key={action.id} className="rounded-lg bg-card px-2.5 py-1 text-xs font-semibold">{action.title} · {action.status.replaceAll("_", " ")}</span>)}</div></div>}
    <div className="mt-5 grid grid-cols-2 gap-3 rounded-xl bg-muted p-3 text-xs"><div><p className="text-muted-foreground">Owner</p><p className="mt-1 font-bold">{members.find(member => member.userId === item.ownerUserId)?.name || (item.ownerUserId ? `User #${item.ownerUserId}` : "Unassigned")}</p></div><div><p className="text-muted-foreground">Target</p><p className="mt-1 font-bold">{new Date(item.dueAt).toLocaleDateString("en-GB")}</p></div></div><div className="mt-6"><div className="mb-2 flex justify-between text-xs font-semibold"><span>{item.progressPercent}% complete</span><span className={item.dueAt < Date.now() && item.status !== "complete" ? "text-destructive" : "text-muted-foreground"}>Due {new Date(item.dueAt).toLocaleDateString("en-GB")}</span></div><Progress value={item.progressPercent} /></div>
    {item.completionNotes && <p className="mt-4 rounded-xl border border-border/70 p-3 text-xs leading-5"><strong>Completion evidence:</strong> {item.completionNotes}</p>}
    {item.reviewNotes && <p className="mt-2 text-xs leading-5 text-muted-foreground"><strong>Review:</strong> {item.reviewNotes}</p>}
    <div className="mt-5 flex flex-wrap gap-2"><AssignDialog entityId={entityId} item={item} members={members} />{!["complete", "ready_for_review"].includes(item.status) && <Button size="sm" variant="outline" onClick={() => update.mutate({ entityId, id: item.id, status: "in_progress", progressPercent: Math.max(25, item.progressPercent) })}>Start / update</Button>}{!["complete", "ready_for_review"].includes(item.status) && <SubmitReviewDialog entityId={entityId} item={item} />}{item.status === "ready_for_review" && <ReviewDialog entityId={entityId} item={item} />}<DependencyDialog entityId={entityId} item={item} actions={actions} /><HistoryDialog entityId={entityId} item={item} /></div>
  </article>;
}

function SubmitReviewDialog({ entityId, item }: { entityId: number; item: Action }) { const [open, setOpen] = useState(false); const [notes, setNotes] = useState(item.completionNotes ?? ""); const [evidence, setEvidence] = useState(item.evidenceDocumentId ? String(item.evidenceDocumentId) : "none"); const documents = trpc.documents.list.useQuery({ entityId }, { enabled: open }); const utils = trpc.useUtils(); const submit = trpc.compliance.submitWorkPlanReview.useMutation({ onSuccess: async () => { await utils.compliance.workPlans.invalidate(); setOpen(false); toast.success("Action sent for independent review"); }, onError: error => toast.error(error.message) }); return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button size="sm"><FileCheck2 className="mr-2 h-4 w-4" />Submit evidence</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Submit action for review</DialogTitle><DialogDescription>All prerequisites must be complete. Add concise completion evidence and link a controlled document where appropriate.</DialogDescription></DialogHeader><div className="grid gap-4 py-3"><div className="grid gap-2"><Label>Completion evidence</Label><Textarea value={notes} onChange={event => setNotes(event.target.value)} rows={6} /></div><div className="grid gap-2"><Label>Evidence document</Label><Select value={evidence} onValueChange={setEvidence}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="none">No linked document</SelectItem>{(documents.data ?? []).map(document => <SelectItem key={document.id} value={String(document.id)}>{document.title}</SelectItem>)}</SelectContent></Select></div></div><DialogFooter><Button variant="outline" onClick={() => setOpen(false)}>Cancel</Button><Button onClick={() => submit.mutate({ entityId, id: item.id, progressPercent: Math.max(item.progressPercent, 90), completionNotes: notes, evidenceDocumentId: evidence === "none" ? undefined : Number(evidence) })} disabled={notes.length < 5 || submit.isPending}>Submit for review</Button></DialogFooter></DialogContent></Dialog>; }

function ReviewDialog({ entityId, item }: { entityId: number; item: Action }) { const [open, setOpen] = useState(false); const [notes, setNotes] = useState(""); const [decision, setDecision] = useState("approved"); const utils = trpc.useUtils(); const review = trpc.compliance.reviewWorkPlan.useMutation({ onSuccess: async () => { await utils.compliance.workPlans.invalidate(); setOpen(false); toast.success(decision === "approved" ? "Action approved and completed" : "Action returned for further work"); }, onError: error => toast.error(error.message) }); return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button size="sm"><CheckCheck className="mr-2 h-4 w-4" />Review</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Review completion evidence</DialogTitle><DialogDescription>The creator cannot approve their own action. A return reopens the action without deleting the submitted evidence.</DialogDescription></DialogHeader><div className="grid gap-4 py-3"><Select value={decision} onValueChange={setDecision}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="approved">Approve and complete</SelectItem><SelectItem value="returned">Return for more work</SelectItem></SelectContent></Select><div className="grid gap-2"><Label>Review notes</Label><Textarea value={notes} onChange={event => setNotes(event.target.value)} rows={5} /></div></div><DialogFooter><Button variant="outline" onClick={() => setOpen(false)}>Cancel</Button><Button onClick={() => review.mutate({ entityId, id: item.id, decision: decision as "approved" | "returned", notes })} disabled={notes.length < 3 || review.isPending}>Record decision</Button></DialogFooter></DialogContent></Dialog>; }

function DependencyDialog({ entityId, item, actions }: { entityId: number; item: Action; actions: Action[] }) { const [open, setOpen] = useState(false); const [dependsOn, setDependsOn] = useState("none"); const utils = trpc.useUtils(); const add = trpc.compliance.addWorkPlanDependency.useMutation({ onSuccess: async () => { await utils.compliance.workPlans.invalidate(); setOpen(false); toast.success("Dependency linked"); }, onError: error => toast.error(error.message) }); const candidates = actions.filter(action => action.id !== item.id && !item.dependencies.includes(action.id)); return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button size="sm" variant="outline"><Link2 className="mr-2 h-4 w-4" />Dependency</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Link prerequisite action</DialogTitle><DialogDescription>The system rejects circular dependencies and prevents review until prerequisites are complete.</DialogDescription></DialogHeader><div className="py-3"><Select value={dependsOn} onValueChange={setDependsOn}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="none">Choose action</SelectItem>{candidates.map(action => <SelectItem key={action.id} value={String(action.id)}>{action.title}</SelectItem>)}</SelectContent></Select></div><DialogFooter><Button variant="outline" onClick={() => setOpen(false)}>Cancel</Button><Button onClick={() => add.mutate({ entityId, actionId: item.id, dependsOnActionId: Number(dependsOn) })} disabled={dependsOn === "none" || add.isPending}>Link dependency</Button></DialogFooter></DialogContent></Dialog>; }

function HistoryDialog({ entityId, item }: { entityId: number; item: Action }) { const [open, setOpen] = useState(false); const history = trpc.compliance.workPlanHistory.useQuery({ entityId, id: item.id }, { enabled: open }); return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button size="sm" variant="ghost"><History className="h-4 w-4" /><span className="sr-only">View history</span></Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Action history</DialogTitle><DialogDescription>Append-only creation, dependency, progress, submission and review events.</DialogDescription></DialogHeader><div className="max-h-80 space-y-2 overflow-y-auto py-3">{history.data?.map(event => <div key={event.id} className="rounded-xl border border-border/70 p-3"><p className="text-sm font-bold">{event.action.replaceAll("_", " ").replaceAll(".", " · ")}</p><p className="mt-1 text-xs text-muted-foreground">{new Date(event.occurredAt).toLocaleString("en-GB")} · {event.result}</p></div>)}{!history.isLoading && !history.data?.length && <p className="thin-copy">No history events available.</p>}</div></DialogContent></Dialog>; }

function AssignDialog({ entityId, item, members }: { entityId: number; item: Action; members: any[] }) { const [open, setOpen] = useState(false); const [owner, setOwner] = useState(item.ownerUserId ? String(item.ownerUserId) : ""); const [due, setDue] = useState(new Date(item.dueAt).toISOString().slice(0, 10)); const utils = trpc.useUtils(); const assign = trpc.compliance.assignWorkPlan.useMutation({ onSuccess: async () => { await utils.compliance.workPlans.invalidate(); setOpen(false); toast.success("Owner and target updated"); }, onError: error => toast.error(error.message) }); return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button size="sm" variant="outline"><UserRound className="mr-2 h-4 w-4" />Assign</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Assign action</DialogTitle><DialogDescription>The owner must be an active member of this entity. Changes enter the action audit history and drive reminder routing.</DialogDescription></DialogHeader><div className="grid gap-4 py-3"><Select value={owner} onValueChange={setOwner}><SelectTrigger><SelectValue placeholder="Choose owner" /></SelectTrigger><SelectContent>{members.map(member => <SelectItem key={member.userId} value={String(member.userId)}>{member.name || member.email || `User #${member.userId}`} · {member.role.replaceAll("_", " ")}</SelectItem>)}</SelectContent></Select><div className="grid gap-2"><Label>Target date</Label><Input type="date" value={due} onChange={event => setDue(event.target.value)} /></div></div><DialogFooter><Button variant="outline" onClick={() => setOpen(false)}>Cancel</Button><Button onClick={() => assign.mutate({ entityId, id: item.id, ownerUserId: Number(owner), dueAt: new Date(`${due}T12:00:00`).getTime() })} disabled={!owner || !due || assign.isPending}>Save assignment</Button></DialogFooter></DialogContent></Dialog>; }

function CreateActionDialog({ entityId, members }: { entityId: number; members: any[] }) { const [open, setOpen] = useState(false); const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [priority, setPriority] = useState("normal"); const [due, setDue] = useState(""); const [owner, setOwner] = useState(""); const utils = trpc.useUtils(); const create = trpc.compliance.createWorkPlan.useMutation({ onSuccess: async () => { await utils.compliance.workPlans.invalidate(); setOpen(false); toast.success("Action created"); }, onError: error => toast.error(error.message) }); return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button id="create-action-trigger" className="rounded-xl"><Plus className="mr-2 h-4 w-4" />Create action</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Create work-plan action</DialogTitle><DialogDescription>Set the accountable owner now so due and overdue reminders route to the correct person.</DialogDescription></DialogHeader><div className="grid gap-5 py-3"><div className="grid gap-2"><Label>Action title</Label><Input value={title} onChange={event => setTitle(event.target.value)} /></div><div className="grid gap-2"><Label>Description</Label><Textarea value={description} onChange={event => setDescription(event.target.value)} rows={4} /></div><div className="grid gap-2"><Label>Owner</Label><Select value={owner} onValueChange={setOwner}><SelectTrigger><SelectValue placeholder="Choose owner" /></SelectTrigger><SelectContent>{members.map(member => <SelectItem key={member.userId} value={String(member.userId)}>{member.name || member.email || `User #${member.userId}`}</SelectItem>)}</SelectContent></Select></div><div className="grid grid-cols-2 gap-4"><div className="grid gap-2"><Label>Priority</Label><Select value={priority} onValueChange={setPriority}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{["low", "normal", "high", "critical"].map(value => <SelectItem value={value} key={value}>{value}</SelectItem>)}</SelectContent></Select></div><div className="grid gap-2"><Label>Target date</Label><Input type="date" value={due} onChange={event => setDue(event.target.value)} /></div></div></div><DialogFooter><Button variant="outline" onClick={() => setOpen(false)}>Cancel</Button><Button onClick={() => create.mutate({ entityId, title, description: description || undefined, ownerUserId: owner ? Number(owner) : undefined, priority: priority as any, dueAt: new Date(`${due}T12:00:00`).getTime() })} disabled={!title || !owner || !due || create.isPending}>{create.isPending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}Create action</Button></DialogFooter></DialogContent></Dialog>; }
