import { and, eq } from "drizzle-orm";
import {
  automationRules, carePlans, complianceObligations, entityMemberships, invoiceEvents, invoices, notifications,
  placements, policyAcknowledgements, workPlanActions, curfewChecks, loneWorkerSessions, propertyVisitors, documents, retentionReviews,
  medicationDiscrepancies, residentFinanceDiscrepancies, staffRequests, keyWorkerReports, incidents,
  propertyChecks, supervisionSessions, maintenanceJobs, safeguardingConcerns,
} from "../../drizzle/schema";
import { getDb } from "../db";
import { writeAuditEvent } from "./audit";
import { calculateRagStatus, classifyDeadline } from "./rules";
import { runComplianceRenewalEvaluation } from "./complianceRenewals";
import { operationalDayStartUtc, runRotaCoverageEvaluation } from "./rotaCoverageMonitoring";

type RuleType = "compliance" | "review" | "work_plan" | "policy" | "placement" | "invoice" | "evidence";
type RuleConfig = { leadDays: number; escalationDays: number; ownerRole: string; escalationRoute: string[]; requireAcknowledgement: boolean; snoozeDays: number };
type Candidate = {
  entityId: number; userId?: number | null; ownerRole?: string; type: string; title: string; message: string;
  severity: "info" | "warning" | "urgent"; resourceType: string; resourceId: number; deepLink: string;
  dueAt: number; acknowledgementRequired: number; escalationDueAt: number; escalationState: "none" | "escalated";
  escalationCount: number; dedupeKey: string;
};

const DAY = 86_400_000;
const defaults: Record<RuleType, RuleConfig> = {
  compliance: { leadDays: 30, escalationDays: 1, ownerRole: "registered_manager", escalationRoute: ["registered_manager", "owner"], requireAcknowledgement: true, snoozeDays: 3 },
  review: { leadDays: 14, escalationDays: 1, ownerRole: "registered_manager", escalationRoute: ["registered_manager", "owner"], requireAcknowledgement: true, snoozeDays: 3 },
  work_plan: { leadDays: 7, escalationDays: 1, ownerRole: "registered_manager", escalationRoute: ["registered_manager", "owner"], requireAcknowledgement: true, snoozeDays: 2 },
  policy: { leadDays: 7, escalationDays: 2, ownerRole: "registered_manager", escalationRoute: ["registered_manager", "owner"], requireAcknowledgement: true, snoozeDays: 2 },
  placement: { leadDays: 14, escalationDays: 1, ownerRole: "registered_manager", escalationRoute: ["registered_manager", "owner"], requireAcknowledgement: true, snoozeDays: 3 },
  invoice: { leadDays: 7, escalationDays: 3, ownerRole: "finance", escalationRoute: ["finance", "owner"], requireAcknowledgement: true, snoozeDays: 3 },
  evidence: { leadDays: 30, escalationDays: 1, ownerRole: "registered_manager", escalationRoute: ["registered_manager", "owner"], requireAcknowledgement: true, snoozeDays: 3 },
};

async function fallbackOwner(entityId: number, preferredRole?: string) {
  const db = await getDb(); if (!db) return null;
  const memberships = await db.select().from(entityMemberships).where(and(eq(entityMemberships.entityId, entityId), eq(entityMemberships.status, "active")));
  return memberships.find(item => preferredRole && item.operationalRole === preferredRole)?.userId
    ?? memberships.find(item => item.operationalRole === "registered_manager")?.userId
    ?? memberships.find(item => item.operationalRole === "owner")?.userId ?? null;
}

function policy(rules: Array<typeof automationRules.$inferSelect>, entityId: number, type: RuleType): RuleConfig {
  const row = rules.find(item => item.entityId === entityId && item.ruleType === type && item.enabled);
  return { ...defaults[type], ...((row?.configuration as Partial<RuleConfig> | null) ?? {}) };
}

function candidate(input: Omit<Candidate, "acknowledgementRequired" | "escalationDueAt" | "escalationState" | "escalationCount" | "ownerRole">, config: RuleConfig, now: number): Candidate {
  const escalationDueAt = input.dueAt + config.escalationDays * DAY;
  const escalated = now >= escalationDueAt;
  const escalationCount = escalated ? Math.max(1, Math.floor((now - input.dueAt) / (Math.max(1, config.escalationDays) * DAY))) : 0;
  const ownerRole = escalated ? config.escalationRoute[Math.min(escalationCount - 1, config.escalationRoute.length - 1)] ?? config.ownerRole : config.ownerRole;
  return { ...input, ownerRole, acknowledgementRequired: config.requireAcknowledgement ? 1 : 0, escalationDueAt, escalationState: escalated ? "escalated" : "none", escalationCount };
}

export async function runAutomationEvaluation(entityId?: number | null) {
  const db = await getDb(); if (!db) throw new Error("Database unavailable"); const now = Date.now();
  const scoped = <T extends { entityId: number }>(rows: T[]) => entityId ? rows.filter(row => row.entityId === entityId) : rows;
  const [allObligations, allActions, allPlans, allPlacements, allAcknowledgements, allInvoices, allRules, allCurfews, allLoneWorkers, allVisitors, allMedicationDiscrepancies, allFinanceDiscrepancies, allStaffRequests, allReports, allIncidents, allPropertyChecks, allSupervisions, allMaintenance, allSafeguarding, allDocuments, allRetentionReviews] = await Promise.all([
    db.select().from(complianceObligations), db.select().from(workPlanActions), db.select().from(carePlans),
    db.select().from(placements), db.select().from(policyAcknowledgements), db.select().from(invoices), db.select().from(automationRules),
    db.select().from(curfewChecks), db.select().from(loneWorkerSessions), db.select().from(propertyVisitors),
    db.select().from(medicationDiscrepancies), db.select().from(residentFinanceDiscrepancies), db.select().from(staffRequests),
    db.select().from(keyWorkerReports), db.select().from(incidents), db.select().from(propertyChecks),
    db.select().from(supervisionSessions), db.select().from(maintenanceJobs), db.select().from(safeguardingConcerns), db.select().from(documents), db.select().from(retentionReviews),
  ]);
  const obligations = scoped(allObligations); const actions = scoped(allActions); const plans = scoped(allPlans); const placementRows = scoped(allPlacements); const acknowledgements = scoped(allAcknowledgements); const invoiceRows = scoped(allInvoices);
  const rules = allRules.filter(item => item.entityId !== null && (!entityId || item.entityId === entityId) && item.enabled);
  const candidates: Candidate[] = [];
  const frontlineConfig = (rowEntityId: number) => policy(rules, rowEntityId, "work_plan");
  const evidenceConfig = (rowEntityId: number) => {
    const rule = rules.find(item => item.entityId === rowEntityId && item.ruleType === "evidence");
    return rule ? (rule.configuration as { staffEvidenceReviewHours?: number; documentReviewLeadDays?: number; retentionReviewLeadDays?: number }) : null;
  };

  for (const item of obligations.filter(item => !["complete", "not_applicable"].includes(item.status))) {
    const config = policy(rules, item.entityId, "compliance"); const leadDays = item.leadDays || config.leadDays;
    const rag = calculateRagStatus(item.dueAt, item.completedAt, leadDays, now); const status = rag === "red" ? "overdue" : rag === "amber" ? "due_soon" : "not_due";
    await db.update(complianceObligations).set({ status, ragStatus: rag }).where(eq(complianceObligations.id, item.id)); if (status === "not_due") continue;
    candidates.push(candidate({ entityId: item.entityId, userId: item.ownerUserId, type: "compliance", title: item.title, message: status === "overdue" ? "Compliance evidence is overdue and requires action." : `Compliance evidence is due within ${leadDays} days.`, severity: status === "overdue" ? "urgent" : "warning", resourceType: "compliance_obligation", resourceId: item.id, deepLink: `/compliance?record=${item.id}`, dueAt: item.dueAt, dedupeKey: `compliance:${item.id}` }, config, now));
  }

  for (const item of actions.filter(item => !["complete", "cancelled"].includes(item.status))) { const config = policy(rules, item.entityId, "work_plan"); if (item.dueAt > now + config.leadDays * DAY) continue; const band = classifyDeadline(item.dueAt, config.leadDays, now); candidates.push(candidate({ entityId: item.entityId, userId: item.ownerUserId, type: "work_plan", title: item.title, message: band === "overdue" ? "Work-plan action is overdue." : `Work-plan action is due within ${config.leadDays} days.`, severity: band === "overdue" ? "urgent" : "warning", resourceType: "work_plan_action", resourceId: item.id, deepLink: `/work-plans?record=${item.id}`, dueAt: item.dueAt, dedupeKey: `work-plan:${item.id}` }, config, now)); }
  for (const item of plans) { const dueAt = item.reviewDueAt; const config = policy(rules, item.entityId, "review"); if (item.status !== "approved" || !dueAt || dueAt > now + config.leadDays * DAY) continue; candidates.push(candidate({ entityId: item.entityId, type: "plan_review", title: `${item.planType.replaceAll("_", " ")} plan review`, message: dueAt < now ? "Approved plan review is overdue." : `Approved plan review is due within ${config.leadDays} days.`, severity: dueAt < now ? "urgent" : "warning", resourceType: "care_plan", resourceId: item.id, deepLink: `/placements?plan=${item.id}`, dueAt, dedupeKey: `plan:${item.id}` }, config, now)); }
  for (const item of placementRows.filter(item => item.reviewDueAt && !["ended", "declined"].includes(item.status))) { const config = policy(rules, item.entityId, "placement"); if (item.reviewDueAt! > now + config.leadDays * DAY) continue; const overdue = item.reviewDueAt! < now; candidates.push(candidate({ entityId: item.entityId, type: "placement_review", title: "Placement review", message: overdue ? "Placement review is overdue." : `Placement review is due within ${config.leadDays} days.`, severity: overdue ? "urgent" : "warning", resourceType: "placement", resourceId: item.id, deepLink: `/placements?record=${item.id}`, dueAt: item.reviewDueAt!, dedupeKey: `placement:${item.id}` }, config, now)); }
  for (const item of acknowledgements.filter(item => item.status !== "acknowledged" && item.dueAt)) { const config = policy(rules, item.entityId, "policy"); if (item.dueAt! > now + config.leadDays * DAY) continue; const overdue = item.dueAt! < now; candidates.push(candidate({ entityId: item.entityId, userId: item.userId, type: "policy", title: "Policy acknowledgement", message: overdue ? "Policy acknowledgement is overdue." : `Policy acknowledgement is due within ${config.leadDays} days.`, severity: overdue ? "urgent" : "warning", resourceType: "policy_acknowledgement", resourceId: item.id, deepLink: `/documents?ack=${item.id}`, dueAt: item.dueAt!, dedupeKey: `policy:${item.id}` }, config, now)); }
  for (const item of invoiceRows.filter(item => item.dueAt && !["paid", "void", "credited", "draft", "pending_approval"].includes(item.status))) { const config = policy(rules, item.entityId, "invoice"); if (item.dueAt! > now + config.leadDays * DAY) continue; const overdue = item.dueAt! < now; if (overdue && ["issued", "sent", "part_paid"].includes(item.status)) await db.update(invoices).set({ status: "overdue" }).where(eq(invoices.id, item.id)); candidates.push(candidate({ entityId: item.entityId, type: "invoice", title: item.invoiceNumber ? `Invoice ${item.invoiceNumber}` : "Invoice payment", message: overdue ? "Invoice payment is overdue." : `Invoice payment is due within ${config.leadDays} days.`, severity: overdue ? "urgent" : "warning", resourceType: "invoice", resourceId: item.id, deepLink: `/finance/invoice/${item.id}`, dueAt: item.dueAt!, dedupeKey: `invoice:${item.id}` }, config, now)); }

  for (const item of scoped(allCurfews).filter(item => item.status === "pending" && item.expectedAt <= now)) { const config = frontlineConfig(item.entityId); candidates.push(candidate({ entityId: item.entityId, type: "curfew", title: "Curfew check overdue", message: "A scheduled curfew check requires action in the Hub.", severity: item.escalationRequired ? "urgent" : "warning", resourceType: "curfew_check", resourceId: item.id, deepLink: "/app/people", dueAt: item.expectedAt, dedupeKey: `curfew:${item.id}` }, config, now)); }
  for (const item of scoped(allLoneWorkers).filter(item => ["active", "overdue"].includes(item.status) && item.nextCheckInDueAt <= now)) { const config = frontlineConfig(item.entityId); if (item.status === "active") await db.update(loneWorkerSessions).set({ status: "overdue", version: item.version + 1 }).where(eq(loneWorkerSessions.id, item.id)); candidates.push(candidate({ entityId: item.entityId, type: "lone_worker", title: "Lone-worker check-in overdue", message: "A lone-worker safety check-in is overdue. Open the Hub to respond.", severity: "urgent", resourceType: "lone_worker_session", resourceId: item.id, deepLink: "/app/property", dueAt: item.nextCheckInDueAt, dedupeKey: `lone-worker:${item.id}` }, config, now)); }
  for (const item of scoped(allVisitors).filter(item => item.status === "on_site" && item.expectedDepartureAt && item.expectedDepartureAt <= now)) { const config = frontlineConfig(item.entityId); candidates.push(candidate({ entityId: item.entityId, type: "visitor", title: "Visitor departure overdue", message: "A visitor remains recorded on site after the expected departure time.", severity: "warning", resourceType: "property_visitor", resourceId: item.id, deepLink: "/app/property", dueAt: item.expectedDepartureAt!, dedupeKey: `visitor:${item.id}` }, config, now)); }
  for (const item of scoped(allMedicationDiscrepancies).filter(item => item.status !== "closed")) { const config = frontlineConfig(item.entityId); const dueAt = item.createdAt.getTime() + DAY; candidates.push(candidate({ entityId: item.entityId, type: "medication", title: "Medication review required", message: "A medication discrepancy requires Manager review.", severity: dueAt <= now ? "urgent" : "warning", resourceType: "medication_discrepancy", resourceId: item.id, deepLink: "/app/manager/inbox", dueAt, dedupeKey: `medication-discrepancy:${item.id}` }, config, now)); }
  for (const item of scoped(allFinanceDiscrepancies).filter(item => item.status !== "closed")) { const config = frontlineConfig(item.entityId); const dueAt = item.createdAt.getTime() + DAY; candidates.push(candidate({ entityId: item.entityId, type: "resident_finance", title: "Resident-finance review required", message: "A resident-finance discrepancy requires Manager review.", severity: item.discrepancyType === "unauthorised" ? "urgent" : "warning", resourceType: "resident_finance_discrepancy", resourceId: item.id, deepLink: "/app/manager/inbox", dueAt, dedupeKey: `resident-finance-discrepancy:${item.id}` }, config, now)); }
  for (const item of scoped(allStaffRequests).filter(item => item.status === "submitted")) { const configuredEvidence = evidenceConfig(item.entityId); const isEvidence = ["certificate_submission", "sickness"].includes(item.requestType); const config = isEvidence && configuredEvidence ? policy(rules, item.entityId, "evidence") : frontlineConfig(item.entityId); const reviewHours = isEvidence && configuredEvidence ? Math.max(1, Math.min(720, Number(configuredEvidence.staffEvidenceReviewHours ?? 48))) : 48; const dueAt = item.createdAt.getTime() + reviewHours * 3_600_000; candidates.push(candidate({ entityId: item.entityId, type: isEvidence && configuredEvidence ? "evidence_review" : "staff_request", title: isEvidence ? "Workforce evidence awaiting review" : "Staff request awaiting review", message: isEvidence ? "Certificate or sickness evidence is awaiting independent Manager review." : "A staff self-service request is awaiting Manager review.", severity: dueAt <= now ? "urgent" : "warning", resourceType: "staff_request", resourceId: item.id, deepLink: "/manager-app", dueAt, dedupeKey: `${isEvidence && configuredEvidence ? "evidence-review" : "staff-request"}:${item.id}` }, config, now)); }
  for (const item of scoped(allDocuments).filter(item => item.status !== "archived" && item.reviewDueAt)) { const configuredEvidence = evidenceConfig(item.entityId); if (!configuredEvidence) continue; const config = policy(rules, item.entityId, "evidence"); const leadDays = Math.max(1, Math.min(365, Number(configuredEvidence.documentReviewLeadDays ?? 30))); if (item.reviewDueAt! > now + leadDays * DAY) continue; candidates.push(candidate({ entityId: item.entityId, type: "document_review", title: "Document review due", message: item.reviewDueAt! <= now ? "A controlled document review is overdue." : `A controlled document review is due within ${leadDays} days.`, severity: item.reviewDueAt! <= now ? "urgent" : "warning", resourceType: "document", resourceId: item.id, deepLink: "/documents", dueAt: item.reviewDueAt!, dedupeKey: `document-review:${item.id}` }, config, now)); }
  for (const item of scoped(allRetentionReviews).filter(item => item.status === "pending" && !item.legalHold)) { const configuredEvidence = evidenceConfig(item.entityId); if (!configuredEvidence) continue; const config = policy(rules, item.entityId, "evidence"); const leadDays = Math.max(1, Math.min(365, Number(configuredEvidence.retentionReviewLeadDays ?? 30))); if (item.reviewDueAt > now + leadDays * DAY) continue; candidates.push(candidate({ entityId: item.entityId, type: "retention_review", title: "Retention review due", message: item.reviewDueAt <= now ? "A retention review is overdue." : `A retention review is due within ${leadDays} days.`, severity: item.reviewDueAt <= now ? "urgent" : "warning", resourceType: "retention_review", resourceId: item.id, deepLink: "/documents", dueAt: item.reviewDueAt, dedupeKey: `retention-review:${item.id}` }, config, now)); }
  for (const item of scoped(allReports).filter(item => ["submitted", "reviewed"].includes(item.status))) { const config = frontlineConfig(item.entityId); const dueAt = item.createdAt.getTime() + DAY; candidates.push(candidate({ entityId: item.entityId, type: "keywork_report", title: "Keyworker report awaiting review", message: "A submitted report requires Manager review.", severity: dueAt <= now ? "urgent" : "warning", resourceType: "key_worker_report", resourceId: item.id, deepLink: "/app/manager/inbox", dueAt, dedupeKey: `keywork-report:${item.id}` }, config, now)); }
  for (const item of scoped(allIncidents).filter(item => ["pending", "in_review"].includes(item.managerReviewState))) { const config = frontlineConfig(item.entityId); const dueAt = item.notificationDueAt ?? item.createdAt.getTime() + DAY; candidates.push(candidate({ entityId: item.entityId, type: "incident_review", title: "Incident review required", message: "An incident requires Manager assessment in the Hub.", severity: item.severity === "critical" || dueAt <= now ? "urgent" : "warning", resourceType: "incident", resourceId: item.id, deepLink: "/app/manager/inbox", dueAt, dedupeKey: `incident-review:${item.id}` }, config, now)); }
  for (const item of scoped(allPropertyChecks).filter(item => item.status === "submitted")) { const config = frontlineConfig(item.entityId); const dueAt = item.completedAt ?? item.createdAt.getTime() + DAY; candidates.push(candidate({ entityId: item.entityId, type: "property_check", title: "Property check awaiting review", message: "A submitted property or room check requires Manager review.", severity: item.result === "urgent_action" ? "urgent" : "warning", resourceType: "property_check", resourceId: item.id, deepLink: "/app/manager/inbox", dueAt, dedupeKey: `property-check:${item.id}` }, config, now)); }
  for (const item of scoped(allSupervisions).filter(item => ["scheduled", "submitted"].includes(item.status) && item.scheduledAt <= now)) { const config = frontlineConfig(item.entityId); candidates.push(candidate({ entityId: item.entityId, userId: item.managerUserId, type: "supervision", title: "Supervision action required", message: "A supervision session requires action in the Hub.", severity: item.scheduledAt + 7 * DAY <= now ? "urgent" : "warning", resourceType: "supervision_session", resourceId: item.id, deepLink: "/app/more", dueAt: item.scheduledAt, dedupeKey: `supervision:${item.id}` }, config, now)); }
  for (const item of scoped(allMaintenance).filter(item => ["urgent", "emergency"].includes(item.priority) && !["verified", "cancelled"].includes(item.status))) { const config = frontlineConfig(item.entityId); const dueAt = item.targetAt ?? item.createdAt.getTime() + (item.priority === "emergency" ? 60 * 60_000 : DAY); candidates.push(candidate({ entityId: item.entityId, type: "maintenance", title: "Urgent maintenance action", message: "An urgent maintenance record requires action in the Hub.", severity: item.priority === "emergency" || dueAt <= now ? "urgent" : "warning", resourceType: "maintenance_job", resourceId: item.id, deepLink: "/app/property", dueAt, dedupeKey: `maintenance:${item.id}` }, config, now)); }
  for (const item of scoped(allSafeguarding).filter(item => item.status !== "closed")) { const config = frontlineConfig(item.entityId); const dueAt = item.reviewDueAt ?? item.createdAt.getTime() + DAY; candidates.push(candidate({ entityId: item.entityId, type: "safeguarding", title: "Safeguarding review required", message: "A safeguarding concern requires restricted Manager action in the Hub.", severity: ["high", "critical"].includes(item.riskLevel) || dueAt <= now ? "urgent" : "warning", resourceType: "safeguarding_concern", resourceId: item.id, deepLink: "/app/manager/inbox", dueAt, dedupeKey: `safeguarding:${item.id}` }, config, now)); }

  let created = 0;
  for (const item of candidates) {
    const owner = item.userId ?? await fallbackOwner(item.entityId, item.ownerRole); if (!owner) continue;
    const { ownerRole: _ownerRole, ...values } = item;
    const [previous] = await db.select({ id: notifications.id, escalationCount: notifications.escalationCount }).from(notifications).where(and(eq(notifications.userId, owner), eq(notifications.dedupeKey, item.dedupeKey))).limit(1);
    await db.insert(notifications).values({ ...values, userId: owner }).onDuplicateKeyUpdate({ set: { title: item.title, message: item.message, severity: item.severity, deepLink: item.deepLink, dueAt: item.dueAt, acknowledgementRequired: item.acknowledgementRequired, escalationDueAt: item.escalationDueAt, escalationState: item.escalationState, escalationCount: item.escalationCount, resolvedAt: null } });
    if (item.resourceType === "invoice" && (!previous || item.escalationCount > previous.escalationCount)) await db.insert(invoiceEvents).values({ entityId: item.entityId, invoiceId: item.resourceId, eventType: "reminded", occurredAt: now, metadata: { ownerUserId: owner, stage: item.escalationCount, severity: item.severity, dueAt: item.dueAt } });
    if (item.escalationCount > (previous?.escalationCount ?? 0)) await writeAuditEvent({ actorType: "scheduled_job", entityId: item.entityId, action: "notification.escalate", resourceType: item.resourceType, resourceId: item.resourceId, result: "success", reasonCode: `stage:${item.escalationCount}`, metadata: { notificationId: previous?.id ?? null, ownerUserId: owner, ownerRole: item.ownerRole, escalationDueAt: item.escalationDueAt } });
    created += 1;
  }
  const rotaCoverage = entityId ? await runRotaCoverageEvaluation(db, { entityId, from: operationalDayStartUtc(now), to: operationalDayStartUtc(now) + 31 * DAY, actorType: "scheduled_job" }) : { evaluatedDays: 0, gapCount: 0, notificationsUpserted: 0, notificationsResolved: 0 };
  const renewals=entityId?await runComplianceRenewalEvaluation(entityId):{evaluated:0,candidates:0,notificationsUpserted:0,outboxUpserted:0,emailProviderActive:false as const};
  return { evaluated: obligations.length + actions.length + plans.length + placementRows.length + acknowledgements.length + invoiceRows.length + allCurfews.length + allLoneWorkers.length + allVisitors.length + allMedicationDiscrepancies.length + allFinanceDiscrepancies.length + allStaffRequests.length + allReports.length + allIncidents.length + allPropertyChecks.length + allSupervisions.length + allMaintenance.length + allSafeguarding.length + allDocuments.length + allRetentionReviews.length + rotaCoverage.evaluatedDays + renewals.evaluated, notificationsUpserted: created + rotaCoverage.notificationsUpserted + renewals.notificationsUpserted, rotaCoverage, renewalCandidates: renewals.candidates, emailOutboxUpserted: renewals.outboxUpserted, emailProviderActive: renewals.emailProviderActive };
}

export async function markAutomationRun(taskUid: string) { const db = await getDb(); if (db) await db.update(automationRules).set({ lastRunAt: Date.now() }).where(eq(automationRules.scheduleCronTaskUid, taskUid)); }
