import{PROPERTY_COMPLIANCE_KINDS,type PropertyComplianceKind}from"./propertyComplianceRules";
const DAY=86_400_000;
export const STAFF_COMPLIANCE_CATEGORIES=["dbs","right_to_work","safeguarding","first_aid","medication","fire_safety","food_hygiene","manual_handling","other_training"]as const;export type StaffComplianceCategory=typeof STAFF_COMPLIANCE_CATEGORIES[number];
export const STAFF_COMPLIANCE_LABELS:Record<StaffComplianceCategory,string>={dbs:"DBS certificate",right_to_work:"Right to Work",safeguarding:"Safeguarding training",first_aid:"First aid training",medication:"Medication training",fire_safety:"Fire safety training",food_hygiene:"Food hygiene training",manual_handling:"Manual handling training",other_training:"Other certificate / training"};
export const CERTIFICATE_LIBRARY_FOLDERS=["Property — HMO licences","Property — Gas safety","Property — Electrical safety","Property — Fire safety","Property — Insurance","Property — Ofsted","Property — Other legal certificates","Staff — DBS and Right to Work","Staff — Safeguarding","Staff — First aid","Staff — Medication","Staff — Fire safety","Staff — Food hygiene","Staff — Manual handling","Staff — Other training"]as const;
export type RenewalBand="overdue"|"one_month"|"two_months"|"three_months"|"current"|"missing_date";
export function renewalBand(dueAt:number|null|undefined,now=Date.now()):{band:RenewalBand;daysRemaining:number|null;ragStatus:"red"|"amber"|"green"|"grey";label:string;severity:"urgent"|"warning"|"info"}{if(!dueAt||!Number.isFinite(dueAt))return{band:"missing_date",daysRemaining:null,ragStatus:"grey",label:"Renewal date missing",severity:"warning"};const days=Math.ceil((dueAt-now)/DAY);if(dueAt<now)return{band:"overdue",daysRemaining:days,ragStatus:"red",label:`Overdue by ${Math.max(1,Math.abs(days))} day${Math.abs(days)===1?"":"s"}`,severity:"urgent"};if(days<=30)return{band:"one_month",daysRemaining:days,ragStatus:"red",label:`Due in ${days} day${days===1?"":"s"}`,severity:"urgent"};if(days<=60)return{band:"two_months",daysRemaining:days,ragStatus:"amber",label:`Due within 2 months`,severity:"warning"};if(days<=90)return{band:"three_months",daysRemaining:days,ragStatus:"amber",label:`Due within 3 months`,severity:"warning"};return{band:"current",daysRemaining:days,ragStatus:"green",label:"Current",severity:"info"};}
export function propertyCategory(record:{recordType:string;title:string;details:unknown}):PropertyComplianceKind|null{const detail=record.details&&typeof record.details==="object"?(record.details as any).propertyComplianceKind:null;if(PROPERTY_COMPLIANCE_KINDS.includes(detail))return detail;if(record.recordType==="gas_safety")return"gas_safety";if(record.recordType==="electrical_safety")return"electrical_safety";if(record.recordType==="fire_risk")return"fire_safety";if(record.recordType==="insurance")return"insurance";if(record.recordType==="licence")return record.title.toLowerCase().includes("hmo")?"hmo_licence":"ofsted_registration";if(record.recordType==="certificate")return"other_certificate";return null;}
export function staffCategory(record:{checkType:string;title:string;level:string|null}):StaffComplianceCategory|null{if(record.level&&STAFF_COMPLIANCE_CATEGORIES.includes(record.level as StaffComplianceCategory))return record.level as StaffComplianceCategory;if(record.checkType==="dbs")return"dbs";if(record.checkType==="right_to_work")return"right_to_work";if(["training","qualification"].includes(record.checkType))return"other_training";return null;}
export function renewalDedupeKey(resourceType:"property_evidence"|"workforce_check",resourceId:number,band:RenewalBand,userId:number){return`renewal:${resourceType}:${resourceId}:${band}:user:${userId}`;}
export function outboxDedupeKey(resourceType:"property_evidence"|"workforce_check",resourceId:number,band:RenewalBand,userId:number){return`renewal-email:${resourceType}:${resourceId}:${band}:user:${userId}`;}
