export type PolicyInput={minimumRestHours:number;maximumShiftHours:number;maximumWeeklyHours:number;maximumNightHours:number;breakAfterHours:number};
export type ShiftInput={id:number;userId:number;startsAt:number;endsAt:number};
export type AvailabilityInput={userId:number;startsAt:number;endsAt:number;availabilityType:string;status:string};
export type WorkingException={exceptionType:"availability"|"minimum_rest"|"maximum_shift"|"maximum_weekly"|"night_work"|"break"|"overlap";severity:"warning"|"block";detail:string};
const hours=(start:number,end:number)=>(end-start)/3_600_000;
const overlaps=(a:{startsAt:number;endsAt:number},b:{startsAt:number;endsAt:number})=>a.startsAt<b.endsAt&&b.startsAt<a.endsAt;
export function evaluateWorkingTime(target:ShiftInput,all:ShiftInput[],availability:AvailabilityInput[],policy:PolicyInput){const issues:WorkingException[]=[];const duration=hours(target.startsAt,target.endsAt);if(duration>policy.maximumShiftHours)issues.push({exceptionType:"maximum_shift",severity:"block",detail:`Shift is ${duration.toFixed(2)} hours; policy maximum is ${policy.maximumShiftHours.toFixed(2)} hours.`});const clashes=all.filter(item=>item.id!==target.id&&item.userId===target.userId&&overlaps(item,target));if(clashes.length)issues.push({exceptionType:"overlap",severity:"block",detail:`Shift overlaps ${clashes.length} other assigned shift${clashes.length===1?"":"s"}.`});const previous=all.filter(item=>item.id!==target.id&&item.userId===target.userId&&item.endsAt<=target.startsAt).sort((a,b)=>b.endsAt-a.endsAt)[0];if(previous){const rest=hours(previous.endsAt,target.startsAt);if(rest<policy.minimumRestHours)issues.push({exceptionType:"minimum_rest",severity:"block",detail:`Rest is ${rest.toFixed(2)} hours; policy minimum is ${policy.minimumRestHours.toFixed(2)} hours.`});}const weekStart=new Date(target.startsAt);const day=(weekStart.getUTCDay()+6)%7;weekStart.setUTCHours(0,0,0,0);weekStart.setUTCDate(weekStart.getUTCDate()-day);const weekEnd=weekStart.getTime()+7*24*3_600_000;const weekly=all.filter(item=>item.userId===target.userId&&item.startsAt<weekEnd&&item.endsAt>weekStart.getTime()).reduce((sum,item)=>sum+Math.max(0,hours(Math.max(item.startsAt,weekStart.getTime()),Math.min(item.endsAt,weekEnd))),0);if(weekly>policy.maximumWeeklyHours)issues.push({exceptionType:"maximum_weekly",severity:"block",detail:`Assigned weekly hours total ${weekly.toFixed(2)}; policy maximum is ${policy.maximumWeeklyHours.toFixed(2)}.`});const blocked=availability.filter(item=>item.userId===target.userId&&["active","approved"].includes(item.status)&&["unavailable","annual_leave","sickness","training","agency_constraint"].includes(item.availabilityType)&&overlaps(item,target));if(blocked.length)issues.push({exceptionType:"availability",severity:"block",detail:`Shift overlaps active ${blocked[0].availabilityType.replaceAll("_"," ")} availability.`});const startHour=new Date(target.startsAt).getUTCHours(),endHour=new Date(target.endsAt).getUTCHours();if((startHour>=23||startHour<6||endHour<=6)&&duration>policy.maximumNightHours)issues.push({exceptionType:"night_work",severity:"warning",detail:`Night shift is ${duration.toFixed(2)} hours; night-work threshold is ${policy.maximumNightHours.toFixed(2)} hours.`});if(duration>policy.breakAfterHours)issues.push({exceptionType:"break",severity:"warning",detail:`Shift exceeds ${policy.breakAfterHours.toFixed(2)} hours; confirm the required break is planned and recorded.`});return issues;}
export function staffingChangeStrategy(type:"replacement"|"additional"|"emergency"){return type==="replacement"?"reassign_existing" as const:"create_linked_shift" as const;}
export function staffingAcknowledgementRecipients(type:"replacement"|"additional"|"emergency",originalUserId:number|null,newUserId:number){return Array.from(new Set([newUserId,...(type==="replacement"&&originalUserId&&originalUserId!==newUserId?[originalUserId]:[])]));}
export function workedSummaryState(clockedMinutes:number|null){return clockedMinutes===null?{exceptionState:"missing_clock" as const,payrollState:"not_ready" as const}:{exceptionState:"none" as const,payrollState:"ready" as const};}
